### ISSUE TITLE
CANDACE OWENS: End of Year Video

### ISSUE THREAD

**Issue by rioslumstudio** [rioslumstudio/Design#1]
Pat. A pedido do Jesse. Ele gostaria que fizessemos o seguinte:

- Inserir no segundo bloco, quando ela fala "Welcome to the candace owens show"
![Screen Shot 2019-10-30 at 15 32 46](https://user-images.githubusercontent.com/47640466/67887690-88925380-fb2a-11e9-9000-9c0fbec46c1f.png)

**Comment by Patricia-Torres** [comment]
![image](https://user-images.githubusercontent.com/43677737/67887760-a8c21280-fb2a-11e9-80d2-a1724316f3f3.png)


Segundo bloco vc quer dizer essa parte da direita?

**Comment by rioslumstudio** [comment]
Correto Pat.

**Comment by Patricia-Torres** [comment]
https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv
esse ajuste está na versão 10

**Comment by Patricia-Torres** [comment]
https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv
esse ajuste está na versão 10

**Comment by Patricia-Torres** [comment]
DONE

**Comment by Patricia-Torres** [comment]
Aplicar mais vozes da Candace. Começar adicionando uma voz

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv
v11

**Comment by pedrojovelli** [comment]
Retira essa parte que ela diz **"i'm getting tired of the democrat party .... blah blah blah"** 

e coloca no lugar essa parte aqui de audio e vídeo:
3:46  ( pega a parte que ela diz .... **"I trully believe that the black and latinos ...blah blah"**
...pega até parte em que as pessoas estão celebrando, batendo palmas...

https://www.youtube.com/watch?v=0_83MD60y4k&t=603s

**Comment by Patricia-Torres** [comment]
**DONE**


V12

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/file/d/1c_51VdLgGBO5KQeAF5JMWtM3VRjX5Jyk/view?usp=sharing

**Comment by pedrojovelli** [comment]
Pat. Checar os seguintes pedidos:

1. Há vídeos repetindo:
![Screen Shot 2019-10-31 at 13 31 27](https://user-images.githubusercontent.com/15367213/67966545-d2d70b80-fbe2-11e9-96ea-0ee9d238e221.png)

2. Gostaria de pedir pra você para... próximo dos 12 segundos, quando fica somente uma voz.... deixar mais uma voz para o som ainda ficar um pouco bagunçado ....

3. Quando a Candace diz ... "I believe that black and latino ... " aí tem tipo o grito de uma pessoa ... se você puder tentar apagar este grito.

**Comment by Patricia-Torres** [comment]
**DONE**
v 14
https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv

**Comment by Patricia-Torres** [comment]
ajuste no audio:

v 15
https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv

**Comment by Patricia-Torres** [comment]
- Quando ela terminar de falar SHOW entrar a divisão de 4.

- Inserir mais sons para sujar um pouco mais a trilha. Nada sobressaindo entre 7s - 11/12

- Depois de "going to save America" mais claro.

**Comment by Patricia-Torres** [comment]
- every single person ( aí corta )

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/file/d/1ZM1O8XmYB5mWCZNqvlk0t2WyV69_sgW3/view?usp=sharing

**Comment by pedrojovelli** [comment]
Pra mim está perfeito !

**Comment by Patricia-Torres** [comment]
https://drive.google.com/file/d/1VbBxLFoBBEaXdwKdIAsuTT431X7WDxr-/view?usp=sharing
**DONE**
