### ISSUE TITLE
CANDACE OWENS: Adicionar evento no site dela

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#10]
Por favor, adicionar evento com base nas informações deste flyer abaixo.

Seguir estrutura de texto dos eventos atuais do site dela.

![Super FIX-1](https://user-images.githubusercontent.com/15367213/68147044-fcac6d00-ff17-11e9-9966-e56d7e397337.jpg)

**Comment by Patricia-Torres** [comment]
**DONE**

https://candaceowens.com/events/

**Comment by pedrojovelli** [comment]
Bacana Pat !

Por favor.

Altere a ordem (mudando a data), para que este evento seja apresentado com o último.

![Screen Shot 2019-11-04 at 15 51 35](https://user-images.githubusercontent.com/15367213/68148562-fff52800-ff1a-11e9-958a-b3e50b5c7afa.png)

**Comment by Patricia-Torres** [comment]
**Done**

https://candaceowens.com/events/
