### ISSUE TITLE
Blexit Charlotte - Intro (Walk-on video) videos

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#101]
Referência:
https://drive.google.com/file/d/1qGCKsxrQNpDRl3h_1Ohvau65MmRKMCC9/view

**Cliente ainda não proveu os sons**

Nomes:

- Mark Robinson
- Will Witt 
- Larry Elder

**Comment by Patricia-Torres** [comment]
**[WILL WITT](https://drive.google.com/file/d/1hf_jJID4NjaNqdN487DCFeWCZ2VzGHib/view?usp=sharing)**

**[MARK ROBINSON](https://drive.google.com/file/d/1KFlfVDIkI--4_shF23lKzW4Oxavoz3Lp/view?usp=sharing)**

**[LARRY ELDER](https://drive.google.com/file/d/1koRj6-tJ_J6aMzp03OpiokSYWAwIZJse/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Pat. Por favor, faça com que os nomes fiquem maiores ... tome como referência este aqui do Brandom Tatum:

https://drive.google.com/file/d/1qGCKsxrQNpDRl3h_1Ohvau65MmRKMCC9/view?usp=sharing

**Comment by Patricia-Torres** [comment]
Eu já havia aumentado.
Quer que aumente mais?

**Comment by pedrojovelli** [comment]
Vale buscarmos checar se os seguintes nomes estão grandes na tela. Se estiverem pequenso, vale aumentar um pouco mais...

- Larry Elder
- Brandon Tatum
- Mark Robinson
- KingFace
- Will Witt 
- Candace Owens
