### ISSUE TITLE
BLEXIT - Speaker Graphic Loop Video

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#102]
Referência:
https://drive.google.com/file/d/1u8cJBgdPQezELC8yX6dUZddm3X6rIjeY/view

**Para estes nomes aqui:**
Mark Robinson
Will Witt
Larry Elder

**Comment by Patricia-Torres** [comment]
**[WILL WITT](https://drive.google.com/file/d/1SCmoQSBmG8ws2shnRJ8BrnfTDFg9WfFH/view?usp=sharing)**

**[MARK ROBINSON](https://drive.google.com/file/d/10EXUbTrwLIq4AZYrt3Yzsun0QGR-PZ7i/view?usp=sharing)**

**[LARRY ELDER](https://drive.google.com/file/d/1x_16pvbQCGqHs72gTrnCJ2idM6HACQC_/view?usp=sharing)**
