### ISSUE TITLE
Charlie Kirk - Gif 3d

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#103]
![Screen Shot 2020-01-13 at 17 27 51](https://user-images.githubusercontent.com/15367213/72289426-de56a200-3629-11ea-9550-d2fa4d0086a5.png)

**Comment by pedrojovelli** [comment]
**Alterar a data para:**

3.3.20

**Comment by Patricia-Torres** [comment]
ON SALE
MAR. 03rd ?

**Comment by pedrojovelli** [comment]
ON SALE
MAR. 3rd

Se quiser eu posso preparar a JPG pra você.

**Comment by Patricia-Torres** [comment]
Acho que não precisa pois acho que já tenho o psd editável :) amanhã te falo

**Comment by pedrojovelli** [comment]
Obrigadão Pat :)

**Comment by Patricia-Torres** [comment]
Done
![MAR 3 Maga Doctrine](https://user-images.githubusercontent.com/43677737/72339591-48605d00-36a5-11ea-8f73-1ffa4f4238d1.gif)
