### ISSUE TITLE
BLEXIT - Elaborar Testes nos WALK-ON Videos

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#107]
Inserir cenas da cidade em overlay no início dos walk-ons.

Testar também se é possível inserir cenas da cidada na parte que mostra o nome do speaker.

Vídeo a ser inserido:
https://drive.google.com/file/d/1dUBDQIJYLSSh6tDf8Oa6ksNe1qbwOvrX/view?usp=sharing

Vídeo para testar do WALK-ON GRAPHIC:
https://drive.google.com/file/d/1_wZYQ0BF1QDXqLipi7DpGLHCb9iJg-OX/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[Done](https://drive.google.com/drive/folders/1uAT-rzPJN7VQbO5Kgxzi1xst8plPuhBD?usp=sharing)**

**Comment by pedrojovelli** [comment]
V3

**No início usar:**
Starts with the building (rotating camera)
Cenas noturnas
Cena noturna de drone vista por cima

**Comment by pedrojovelli** [comment]
Vamos elaborar mais uma variação de cidades. Assim poderemos variar entre essas 2 versões da cidade.

**Comment by Patricia-Torres** [comment]
Por fim, checar o tamanho de todos os nomes:

- Larry Elder
- Brandon Tatum
- Mark Robinson
- KingFace
- Will Witt
- Candace Owens

**Comment by Patricia-Torres** [comment]
> V3
> 
> **No início usar:**
> Starts with the building (rotating camera)
> Cenas noturnas
> Cena noturna de drone vista por cima
> Vamos elaborar mais uma variação de cidades. Assim poderemos variar entre essas 2 versões da cidade.

**[Opção da cidade 01](https://drive.google.com/file/d/1NkqE7A2FRJLIracKA7GfmkbqJW-yusRw/view?usp=sharing)**
**[Opção da cidade 02](https://drive.google.com/file/d/101DMR9w4WJNlPmzA5Q8wBaIezFj-ZbnG/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[Done](https://drive.google.com/file/d/1K9wNyZW7z6k_2_B-LX-rjIFAP4SbmjkE/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Pat. Por favor, crie o segundo vídeo com estas footages aqui em destaque e um pouco das outras do outro vídeo:

https://www.pond5.com/stock-footage/item/111438277-charlotte-downtown-mainstreet-1

https://www.pond5.com/stock-footage/item/100221328-north-carolina-charlotte-aerial-v40-panning-around-downtown

**Comment by pedrojovelli** [comment]
**Sobre o primeiro vídeo. Este aqui:**
https://drive.google.com/file/d/1K9wNyZW7z6k_2_B-LX-rjIFAP4SbmjkE/view?usp=sharing

Por favor, se você puder fazer com que comece com esta cena dos prédios por cima aqui:
![Screen Shot 2020-01-14 at 12 34 14](https://user-images.githubusercontent.com/15367213/72357651-16152680-36ca-11ea-8741-29e928ed86ea.png)

Em seguida esta cena aqui:
![Screen Shot 2020-01-14 at 12 35 20](https://user-images.githubusercontent.com/15367213/72357708-2e854100-36ca-11ea-95d2-396aca314ef9.png)

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1fjEynT42kg40rNyXqIoAIecVDIOjgkge/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[V1](https://drive.google.com/file/d/1fjEynT42kg40rNyXqIoAIecVDIOjgkge/view?usp=sharing)**

**[V2](https://drive.google.com/file/d/1AulgAmEMYQ7KfkW5PMKfWp_9T66E2IkU/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Will Witt
https://drive.google.com/file/d/1SJJN7UkhiBP3DPxVQJdjS4W9PzgHru9N/view?usp=sharing

Mark Robinson
https://drive.google.com/file/d/1FhrldQdYByJHZfeyBazfyeMWpRUNKHV-/view?usp=sharing
