### ISSUE TITLE
Real America - Presentation

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#108]
Hi Fellipe. 

I'd like to ask you to put together the Real America presentation based on Poplitics presentation.
Here is the URL:
https://drive.google.com/file/d/1xufxJl-IIJNhk6unPrFbFuzIpjqYIWsc/view?usp=sharing

These are the logos separated by categories to be added on the presentation.
Link here: https://drive.google.com/file/d/1mk6Pa6rsuhF7oP-Zn47P5BRvHBvgx9Wd/view?usp=sharing

We also need to add the realistic versions at the end.

**Comment by felliperinschede** [comment]
Attached the PPT.

Download link
https://wetransfer.com/downloads/55f1f8db26be33fd8f21aa1ddff8e61120200114190306/b7c4d5f8aa3b3c5154eaf5c8f3e0fd8920200114190306/390044

**Comment by pedrojovelli** [comment]
![cover](https://user-images.githubusercontent.com/15367213/72375670-415c3d80-36eb-11ea-9df0-bfb03fdf9863.jpg)

**Comment by felliperinschede** [comment]
Awesome, thanks for the cover.
On the link below, I attached the PPT with the logo options and the new cover.

Download link
https://wetransfer.com/downloads/52edc788f5cdaa701d47256d0aa0e2c020200114194401/a11b1fffc56c2ff25b8f3bc2fa0d308b20200114194401/047a5c

**Comment by pedrojovelli** [comment]
Hi Fellipe !

Here are a few edits remaining Jesse has asked:
https://drive.google.com/file/d/1FjSkpV8hF32QWhaBwHZeLCCdiNgnJeMh/view?usp=sharing

Here is a bit of explanation on what's remaining:
https://drive.google.com/file/d/1jTolwAG5NPBFXLNcsu5wMIS-UV1Lhj9k/view?usp=sharing

**Comment by felliperinschede** [comment]
Opa, segue o link:

Download link
https://wetransfer.com/downloads/ff1211dab9bf2c99f72ff5f2fe4cfe5c20200115154224/cf0e83e7a9a5d943887ea950b01ad28920200115154224/ed8218

**Comment by pedrojovelli** [comment]
Delivered

**Comment by pedrojovelli** [comment]
![Screen Shot 2020-02-17 at 13 19 47](https://user-images.githubusercontent.com/15367213/74670592-3f711880-5188-11ea-8881-9472c43d8b80.png)

**Comment by pedrojovelli** [comment]
[Presentation Real America - Draft 2.pdf](https://github.com/rioslumstudio/Design/files/4233940/Presentation.Real.America.-.Draft.2.pdf)

We have done variations and sent to them.

**Comment by pedrojovelli** [comment]
![Screen Shot 2020-03-05 at 14 25 16](https://user-images.githubusercontent.com/15367213/76007679-2fc63380-5eed-11ea-8a83-a97f34ba82f5.png)

![Screen Shot 2020-03-05 at 14 25 19](https://user-images.githubusercontent.com/15367213/76007683-318ff700-5eed-11ea-9d94-5726bbe5ddc9.png)
