### ISSUE TITLE
Blexit - Charlotte Pre Show

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#109]
**[Done](https://drive.google.com/drive/folders/1y-k9KuNI1cebO__SdoReeJsPmO18Q4fY?usp=sharing)**

**Comment by pedrojovelli** [comment]
Pat.

Desse video. Por favor, retire essas cenas aqui:

![Screen Shot 2020-01-14 at 12 13 17](https://user-images.githubusercontent.com/15367213/72355946-2677d200-36c7-11ea-8850-31416290cc76.png)



Retira esse pedacinho de cena aqui dos bancos:
![Screen Shot 2020-01-14 at 12 14 48](https://user-images.githubusercontent.com/15367213/72356043-52935300-36c7-11ea-80eb-3fd0aa8c67cf.png)

**Comment by pedrojovelli** [comment]
Pat. Por favor, se você puder gerar um render com o escrito no centro #BLEXITCLT  e outro vídeo com o escrito BLEXIT CHARLOTTE

**Comment by Patricia-Torres** [comment]
**[#BLEXITCLT](https://drive.google.com/file/d/1_zF38qxvw6-bnVgNge7cOiDxMtzaQg3f/view?usp=sharing)**

**[BLEXIT CHARLOTTE](https://drive.google.com/file/d/1GMuoXhJdnIoFZQC0A5V3YAeAa5XrzQs8/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
- Less than a minute video
- No Yellow color in it
- Focusing more on City / Night Time Shots

**Comment by Patricia-Torres** [comment]
**[Done](https://drive.google.com/file/d/1h-ySLV_5AWFmPqNF_63VZjohZ6UtjVgU/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[ANTES](https://drive.google.com/file/d/1-u_K7h6jOM9k3_iKTxWmUxPIjLe3K5np/view?usp=sharing)**

**[DEPOIS](https://drive.google.com/file/d/15_An7dCRy5kDJepTYkXG0eYYflVoxAnd/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[Editável](https://drive.google.com/drive/folders/17yxHnSVmvgNyZCNRlpyf6qG-n3BNRcOh?usp=sharing)**

**Comment by pedrojovelli** [comment]
rever alguns posicionamentos de cena comigo depois ... Jesse preferiu opção com mais vibração.

Enviando para o cliente.

**Comment by pedrojovelli** [comment]
**Purchased Footage is here:**
https://drive.google.com/drive/folders/1VofnVgj4HY8ufAQ_bSOl4xJAW2R3xs-w?usp=sharing

**Comment by Patricia-Torres** [comment]
**Vídeo com as footages compradas:**
https://drive.google.com/file/d/1H6MeFkN3qQIRN8XkBQANSYRDHKiZRogJ/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[Last Version:](url)**
https://drive.google.com/file/d/1k-KBMfjS8EAnR50kI2TedTYnT2ilBorz/view?usp=sharing

**Comment by pedrojovelli** [comment]
Perfect !
