### ISSUE TITLE
BLEXIT: Criar banner para evento em Atlanta

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#11]
Criar banner usando o PSD anexo com o logo do BLEXIT e a seguinte hashtag: #BLEXITATL

[Candace.psd.zip](https://github.com/rioslumstudio/Design/files/3805702/Candace.psd.zip)

**Imagens para o fundo com a cidade de Atlanta:**
https://www.google.com/imgres?imgurl=https%3A%2F%2Flive.staticflickr.com%2F143%2F399738561_64a490e5b7_b.jpg&imgrefurl=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Fnate%2F399738561&docid=qh1pEhHCO9PoHM&tbnid=D4C5zcudW20nvM%3A&vet=10ahUKEwjevLqMpNHlAhXrDrkGHU3GBssQMwhSKBAwEA..i&w=1024&h=768&bih=661&biw=1280&q=atlanta%20night&ved=0ahUKEwjevLqMpNHlAhXrDrkGHU3GBssQMwhSKBAwEA&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fa%2Fa2%2FAtlanta%252CGeorgia_at_Night.jpg&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AAtlanta%2CGeorgia_at_Night.jpg&docid=QxD8DH0EQNCDyM&tbnid=woGvoSvFUU8WqM%3A&vet=10ahUKEwjevLqMpNHlAhXrDrkGHU3GBssQMwhCKAAwAA..i&w=3872&h=2592&bih=661&biw=1280&q=atlanta%20night&ved=0ahUKEwjevLqMpNHlAhXrDrkGHU3GBssQMwhCKAAwAA&iact=mrc&uact=8

Algumas referências de banner feito para evento anterior. Se puder gerar um banner sem a hashtag. Somente com o logo do blexit na lateral esquerda:

![Richmond_Poster_1](https://user-images.githubusercontent.com/15367213/68151084-d1c61700-ff1f-11e9-865f-5fb13675d531.jpg)
![Richmond_Poster_2](https://user-images.githubusercontent.com/15367213/68151085-d1c61700-ff1f-11e9-99fb-693273e89fed.jpg)
![Richmond_Poster_3](https://user-images.githubusercontent.com/15367213/68151086-d25ead80-ff1f-11e9-820d-5b2c5882850a.jpg)

**Comment by felliperinschede** [comment]
feito meu caro

**Comment by rioslumstudio** [comment]
Entregue para o cliente
