### ISSUE TITLE
Blexit Walk-On Videos

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#113]
Please, follow the addition of purchased videos from this "storyboard".

[Blexit_storyboard_walkOn.pdf](https://github.com/rioslumstudio/Design/files/4066684/Blexit_storyboard_walkOn.pdf)

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1uAT-rzPJN7VQbO5Kgxzi1xst8plPuhBD?usp=sharing)**
