### ISSUE TITLE
BLEXIT - Backdrop Video (waving flag)

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#114]
PIERRE WILSON

To be just like this one:
https://drive.google.com/file/d/1u8cJBgdPQezELC8yX6dUZddm3X6rIjeY/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1m5UAEAlcxXZLVapUa6OZWdsAr4QDtwZS/view?usp=sharing)**
