### ISSUE TITLE
TPUSA - Event Pages to add

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#115]
**SOUTHEAST REGIONAL CONFERENCE APPLICATION 2020**

**Location:** Charleston Marriott
_Charleston, SC_

**Date:** March 14 & 15

**Embed Code:**
<a name="form214894954" id="formAnchor214894954"></a>
<script src="https://fs21.formsite.com/include/form/embedManager.js?214894954"></script>
<script>
EmbedManager.embed({
	key: "https://fs21.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTC0KL4MVNYdx_RqVWo7ziZ3dgTYVfxeOgg&214894954",
	width: "100%"
});
</script>

**Wordpress Code:**
[formsite host="fs21" key="m_OmK8apOTC0KL4MVNYdx_RqVWo7ziZ3dgTYVfxeOgg" width="100%"]

===============================
===============================
===============================
===============================

**MIDWEST REGIONAL CONFERENCE APPLICATION 2020**

**Location:** Marriott Chicago Downtown
_Chicago, IL_

**Date:** March 21 & 22

**Embed:**
<a name="form650733791" id="formAnchor650733791"></a>
<script src="https://fs21.formsite.com/include/form/embedManager.js?650733791"></script>
<script>
EmbedManager.embed({
	key: "https://fs21.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTC0KL4MVNYdx5yVOhTxx49Y4q0s7ms7jwM&650733791",
	width: "100%"
});
</script>

**Wordpress Embed:**
[formsite host="fs21" key="m_OmK8apOTC0KL4MVNYdx5yVOhTxx49Y4q0s7ms7jwM" width="100%"]

===============================
===============================
===============================
===============================

**NORTHWEST REGIONAL CONFERENCE APPLICATION 2020**

**Location:** Santa Clara Marriott
_Santa Clara, CA_

**Date:** April 4 & 5

**Embed:**
<a name="form451547418" id="formAnchor451547418"></a>
<script src="https://fs21.formsite.com/include/form/embedManager.js?451547418"></script>
<script>
EmbedManager.embed({
	key: "https://fs21.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTC0KL4MVNYdx_RqVWo7ziZ3ngbtbHWZMa4&451547418",
	width: "100%"
});
</script>

**Wordpress embed:**
[formsite host="fs21" key="m_OmK8apOTC0KL4MVNYdx_RqVWo7ziZ3ngbtbHWZMa4" width="100%"]

**Comment by robanquieri** [comment]
https://www.tpusa.com/event/southeast-regional-conference-application-2020
https://www.tpusa.com/event/midwest-regional-conference-application-2020
https://www.tpusa.com/event/northwest-regional-conference-application-2020
