### ISSUE TITLE
BLEXIT: Banners (preparar para impressão)

### ISSUE THREAD

**Issue by rioslumstudio** [rioslumstudio/Design#12]
Fellipe.

Por favor, se puder preparar estes banners para impressão (tamanho, sangria + marcas de corte).

Se puder subir os PDFs nessa pasta aqui:
https://drive.google.com/drive/folders/1c0Kv7ve5_-zLo-G6iRTQTG-07ujPA07R?usp=sharing

Segue banners aprovados pelo cliente:
![Screen Shot 2019-11-05 at 13 43 13](https://user-images.githubusercontent.com/47640466/68228031-76edf780-ffd3-11e9-8de7-17763906a9f9.png)
![Screen Shot 2019-11-05 at 13 43 16](https://user-images.githubusercontent.com/47640466/68228032-76edf780-ffd3-11e9-996b-ba9e212ebc75.png)
![Screen Shot 2019-11-05 at 13 43 26](https://user-images.githubusercontent.com/47640466/68228033-77868e00-ffd3-11e9-87da-efcaf3e7c7cb.png)
![Screen Shot 2019-11-05 at 13 43 35](https://user-images.githubusercontent.com/47640466/68228034-77868e00-ffd3-11e9-8e78-1aff69c0270f.png)

**Comment by felliperinschede** [comment]
Done Mate o/

**Comment by rioslumstudio** [comment]
Delivered to the client
