### ISSUE TITLE
BLEXIT - Ajustar final deste vídeo com a intro da Candace com a cidade

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#120]
Ajustar no final a intro da Candace nesse vídeo do Countdown

https://drive.google.com/file/d/1WSgf8BbLzHYZMse721KfZMBWJ56RCaDU/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**Countdown Charlotte**
[Here](https://drive.google.com/drive/folders/1eF0qjV5l2PYvB3EZAPImYjZCTJ-Z3TDE?usp=sharing)
