### ISSUE TITLE
BLEXIT - Walk-on BLEXIT BREAKDOWN

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#121]
![Screen Shot 2020-01-16 at 15 58 56](https://user-images.githubusercontent.com/15367213/72554205-f839f400-3878-11ea-9397-761591df625d.png)

 BLEXIT BREAKDOWN
PIERRE WILSON

**Comment by Patricia-Torres** [comment]
**BLEXIT BREAKDOWN - Pierre Wilson**
[Here](https://drive.google.com/file/d/1QMV6CpXwYybqGtbt5hIczNRMt1o5qLGh/view?usp=sharing)
