### ISSUE TITLE
TURNING POINT - Benny on The Block Logo

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#124]
Criar uma espécie de template para essa apresentação e possíveis futuras.

1. Adaptar a capa:
![Screen Shot 2020-01-21 at 11 45 15](https://user-images.githubusercontent.com/15367213/72814159-584ae480-3c43-11ea-92d6-68db71881506.png)

2. Criar uma capa genérica que funcione pra qualquer apresentação da TPUSA (faça 2 versões, uma vermelha escura e uma azul.. com algum tipo de textura de concreto) com texto nativo para escrever o nome da categoria (arial black talvez funcione bem)
![Screen Shot 2020-01-21 at 11 46 49](https://user-images.githubusercontent.com/15367213/72814361-b24baa00-3c43-11ea-8a18-e629cf377313.png)

3. Apagar as logos e deixar ao menos uns 3 slides com numeração preparada pra receber novos logos
![Screen Shot 2020-01-21 at 11 49 42](https://user-images.githubusercontent.com/15367213/72814533-f50d8200-3c43-11ea-96e0-edbf42750a05.png)

**Comment by pedrojovelli** [comment]
PPT file:

https://drive.google.com/file/d/1T1cvyZFpCifa9PVA37cu2MCjTZSlaFiM/view?usp=sharing

**Comment by pedrojovelli** [comment]
cover's PSD file:
https://drive.google.com/file/d/12yGAymumGzt88k6dn44hm0K4YT7mmc6J/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[Benny on the Block Presentation](https://drive.google.com/drive/folders/1stCbCLtPO6rYoUsjXGllNTCWznPCB2tl?usp=sharing)**

[Generic presentation for TPUSA](https://drive.google.com/file/d/1GRXl_-CpKvDJdbvJp8Hnu1wmf3c1s6SN/view?usp=sharing)

**Comment by Patricia-Torres** [comment]
**[Last version - Presentation](https://drive.google.com/drive/folders/1stCbCLtPO6rYoUsjXGllNTCWznPCB2tl?usp=sharing)**

**Comment by pedrojovelli** [comment]
Perfect !
