### ISSUE TITLE
TPUSA - Benny on the Block Concept graphics

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#125]
Elaborar peças conceito em 2 estilos diferentes com os logos a seguir:

![Screen Shot 2020-01-22 at 11 45 49](https://user-images.githubusercontent.com/15367213/72903883-ca3b3080-3d0c-11ea-8024-b68f83cd14bd.png)

![Screen Shot 2020-01-22 at 11 51 57](https://user-images.githubusercontent.com/15367213/72904318-7715ad80-3d0d-11ea-94b2-91f4aa520334.png)

Fazer duas sugestões em esquema de colagem, como um poster de anúncio do Benny em NY e em San Francisco. 
Inserir somente logo grande e elementos relacionados a cidade espalhados ao fundo.
Vale buscar a predominância das cores vermelho escuro, azul e branco.

Fazer arte nessa dimensão em pixels aqui: 2368 largura x 1456 altura

**Comment by pedrojovelli** [comment]
**Logos**
[logos.zip](https://github.com/rioslumstudio/Design/files/4098011/logos.zip)

**Comment by felliperinschede** [comment]
Seguem as propostas

![BG_01](https://user-images.githubusercontent.com/57017535/72926153-4d1eb400-3d2a-11ea-9065-504a72aa6b0b.jpg)
![BG_02](https://user-images.githubusercontent.com/57017535/72926154-4d1eb400-3d2a-11ea-86b5-2bf9755837f7.jpg)
![BG_03](https://user-images.githubusercontent.com/57017535/72926156-4d1eb400-3d2a-11ea-98e5-c248049b584a.jpg)
![BG_04](https://user-images.githubusercontent.com/57017535/72926157-4d1eb400-3d2a-11ea-9df7-eb599461ff78.jpg)

**Comment by pedrojovelli** [comment]
Great work !
