### ISSUE TITLE
Charlie Kirk - Newsletter

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#126]
Inserir opção com título:

"Message from Charlie"

**Comment by Patricia-Torres** [comment]
[Newsletter Message from Charlie.zip](https://github.com/rioslumstudio/Design/files/4103708/Newsletter.Message.from.Charlie.zip)

**Comment by Patricia-Torres** [comment]
[Newsletter Message from Charlie - Podcast.zip](https://github.com/rioslumstudio/Design/files/4104071/Newsletter.Message.from.Charlie.-.Podcast.zip)

**Comment by Patricia-Torres** [comment]
[Newsletter Message from Charlie - Podcast.zip](https://github.com/rioslumstudio/Design/files/4104312/Newsletter.Message.from.Charlie.-.Podcast.zip)

**Comment by Patricia-Torres** [comment]
**PSD + JPG:**

[Newsletter Message from Charlie - Podcast.zip](https://github.com/rioslumstudio/Design/files/4104362/Newsletter.Message.from.Charlie.-.Podcast.zip)

**Comment by pedrojovelli** [comment]
![More-Podcast-Options](https://user-images.githubusercontent.com/15367213/73010532-5b83d300-3df1-11ea-92ec-3b3013800000.jpg)

![Newsletter-Message-from-Charlie-Podcast](https://user-images.githubusercontent.com/15367213/73011473-0ea0fc00-3df3-11ea-9b63-e1854d15c862.jpg)
