### ISSUE TITLE
Instagram Video #1

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#129]
Storyboard One:

[Storyboard-01.pdf](https://github.com/rioslumstudio/Design/files/4108325/Storyboard-01.pdf)

**Comment by Patricia-Torres** [comment]
**[V1 POST - Houston - Social Media Announcement](https://drive.google.com/file/d/1bGKmvasCOQVMIzaIgCAs4xW0DX6j0OsP/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Blexit has canceled this event.
