### ISSUE TITLE
TPUSA: PRODUCTION PAGE - Gerar Assets para web

### ISSUE THREAD

**Issue by rioslumstudio** [rioslumstudio/Design#13]
Felipão.

Separar os assets de uma página web complexa como esta de PRODUCTIONS requer uma série de separação de elementos.

Isso é algo que eu farei contigo meu caro.

Vou pedir em primeira instância pra você me ajudar gerando um pattern replicável (que funcione replicando em eixo X e Y) deste fundo aqui:

![Screen Shot 2019-11-05 at 16 54 09](https://user-images.githubusercontent.com/47640466/68241267-22f00c80-ffed-11e9-8dda-20de0e749237.png)

**Comment by felliperinschede** [comment]
Done

**Comment by rioslumstudio** [comment]
Fellipão.

Por favor, se puder separar estas imagens aqui:

![Screen Shot 2019-11-06 at 08 55 09](https://user-images.githubusercontent.com/47640466/68296540-a05e6000-0073-11ea-85a5-37699d0e8561.png)

**Acho que esse pattern dos pontinhos no fundo azul vocÊ conseguie fazer replicável**

**Comment by rioslumstudio** [comment]
Fellipão.

Por favor, gerar SVG (em modo de cores RGB) dos seguintes logos:
![Screen Shot 2019-11-06 at 09 37 37](https://user-images.githubusercontent.com/47640466/68298948-6ee89300-0079-11ea-9951-ced7377f4f56.png)
![Screen Shot 2019-11-06 at 09 37 42](https://user-images.githubusercontent.com/47640466/68298949-6ee89300-0079-11ea-8b6a-c8ca208551f0.png)
![Screen Shot 2019-11-06 at 09 37 45](https://user-images.githubusercontent.com/47640466/68298950-6f812980-0079-11ea-8eb6-d98a4dc35763.png)

Gerar PNG deste aqui:
![Screen Shot 2019-11-06 at 09 37 49](https://user-images.githubusercontent.com/47640466/68298959-76a83780-0079-11ea-8a88-63c522601f83.png)

**É importante que estes logos tenham o mesmo formato (altura, largura).**

**Comment by felliperinschede** [comment]
Done

**Comment by pedrojovelli** [comment]
Fellipão !

Excelente trabalho com relação aos assets.

Vou pedir pra você gerar umas 2 versões de imagem para este fundo aqui:

![Screen Shot 2019-11-06 at 13 21 31](https://user-images.githubusercontent.com/15367213/68316577-710e1a00-0098-11ea-94ed-027570b6c3f3.png)


Uma versão como está aqui na screenshot ... e a outra versão mostrando todo o ícone do timer que fica a direita... pois aí talvez o rogério consiga encaixar a imagem de forma mais amigável para design responsivo.

**Comment by felliperinschede** [comment]
Done

**Comment by pedrojovelli** [comment]
Obrigadão !

**Comment by pedrojovelli** [comment]
Pedidos referente aos assets:

![pedido](https://user-images.githubusercontent.com/15367213/69346691-f6292f80-0c51-11ea-8eb8-87b3055297f4.jpg)

**Comment by felliperinschede** [comment]
Done o/

**Comment by pedrojovelli** [comment]
No nome, retirar "ORIGINAL" do título e inserir "original" na primeira linha menor abaixo. 

________________________________________________________________

no título da página interna, retirar a palavra BEST

________________________________________________________________

nos ícones disonívels para TPUSA Originals, inserir somente YOUTUBE (página principal e interna)

________________________________________________________________

para a sessão OTHER TPUSA SHOWS: O Jesse gostaria que criassemos um carrocel mostrando todos os demais shows disponíveis (but this is a later issue)

**Comment by felliperinschede** [comment]
No email ;D
