### ISSUE TITLE
Blexit - Instagram Video #2 - Houston

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#130]
[Storyboard-02.pdf](https://github.com/rioslumstudio/Design/files/4108506/Storyboard-02.pdf)

**Comment by Patricia-Torres** [comment]
**[V2 POST - Houston - Social Media Announcement](https://drive.google.com/file/d/1KIPA4KrwLFeDfxAUqAfWH5H-HGVLYSDo/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Blexit has canceled this event.
