### ISSUE TITLE
KIRK's Hot Sauce - Elaborar proposta

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#131]
Referência para a proposta:
https://drive.google.com/file/d/1L3qdZMQeK0ldxJikAoVS9zNeIIasAx0x/view?usp=sharing

Usar imagens de dividers que usamos neste aqui:
https://drive.google.com/file/d/1TKg-OWXC_N2MFhZbH-UYdsag2orAXTUQ/view?usp=sharing

Estes são os dados para essa proposta:
[ ARQUIVO ENVIADO PELO TEAMS que nõa conseguimos baixar ]

**Comment by Patricia-Torres** [comment]
[Kirk's Hot Sauce Proposal.pdf](https://github.com/rioslumstudio/Design/files/4109806/Kirk.s.Hot.Sauce.Proposal.pdf)
**[Editável](https://drive.google.com/file/d/1ZI9vJ8s9HAtgnS9C59JXVI6gGJaovPwZ/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
[Kirk's Hot Sauce Proposal.pdf](https://github.com/rioslumstudio/Design/files/4109895/Kirk.s.Hot.Sauce.Proposal.pdf)
**[Editável](https://drive.google.com/file/d/1q1Ob_4z4CdgoUjRGmNsHjTzb0G7qYQyA/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
[Kirk's Hot Sauce Proposal.pdf](https://github.com/rioslumstudio/Design/files/4110425/Kirk.s.Hot.Sauce.Proposal.pdf)
**[Edtitável](https://drive.google.com/file/d/1-jOEsxUvanxy_H40JTOyuCNRHiP0QJKC/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
[Kirk.s.Hot.Sauce.Proposal_JGG_Edits_V1.pdf](https://github.com/rioslumstudio/Design/files/4118096/Kirk.s.Hot.Sauce.Proposal_JGG_Edits_V1.pdf)

**Comment by pedrojovelli** [comment]
**Package INDESIGN**

https://drive.google.com/drive/folders/1rK1TgRMMSFIC-AXMxbZHXcavKbJvbc_Q?usp=sharing

**Comment by Patricia-Torres** [comment]
[Kirk's Hot Sauce Proposal.pdf](https://github.com/rioslumstudio/Design/files/4118409/Kirk.s.Hot.Sauce.Proposal.pdf)

[Editável](https://drive.google.com/drive/folders/1kKNIUSpSoxFsPwOsVkZHrqYEA4AyvocD?usp=sharing)

**Comment by Patricia-Torres** [comment]
**[Editável](https://drive.google.com/drive/folders/1kKNIUSpSoxFsPwOsVkZHrqYEA4AyvocD?usp=sharing)**

[Kirk's Hot Sauce Proposal.pdf](https://github.com/rioslumstudio/Design/files/4118892/Kirk.s.Hot.Sauce.Proposal.pdf)

**Comment by pedrojovelli** [comment]
Proposal has been delivered.
