### ISSUE TITLE
TPUSA -  Fazer Vídeo Tutorials

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#132]
**Final Due Date: February 13th**

- Productions ( carrocel from each playlists of each shows )

- Preparar vídeos para a sessão **NEWS**

- Preparar vídeos para a sessão **CULTURE** (( will be aways pulling 3 from each social media )

- Video criando Team Profiles  / Advisory Council / Speaker

- Vídeo sobre registrar Eventos ((( Rogerio vai executar ajuste ainda )))

- Criar páginas

- Criar Vídeo explicando como cadastrar evento com avatar (33x33px)

**Comment by pedrojovelli** [comment]
![Screen Shot 2020-01-29 at 15 26 57](https://user-images.githubusercontent.com/15367213/73385300-b4e57980-42ab-11ea-81e9-c8f19ff3e543.png)

**Comment by pedrojovelli** [comment]
Productions ( carrocel from each playlists of each shows )

Preparar vídeos para a sessão NEWS

Preparar vídeos para a sessão CULTURE (( will be aways pulling 3 from each social media )

Video criando Team Profiles / Advisory Council / 

[ FEITO ] - Video criando Speaker

[ FEITO ] - Vídeo sobre registrar Eventos ((( Rogerio vai executar ajuste ainda )))

Criar páginas

**Comment by Patricia-Torres** [comment]
**[Todos os tutoriais](https://drive.google.com/drive/folders/1vL6cD87pXZwB21ZiXJk6_CzrY9EIp3sL?usp=sharing)**

**Comment by pedrojovelli** [comment]
@robanquieri, por favor. Se você puder validar estes video tutorials acima.

**Comment by robanquieri** [comment]
**12 - Creating Profiles for Governance Page**
- Add a text indicating that the field username is will used as URL.

**Comment by Patricia-Torres** [comment]
**[Todos os tutoriais](https://drive.google.com/drive/folders/1vL6cD87pXZwB21ZiXJk6_CzrY9EIp3sL?usp=sharing)**

- 01 - [TPUSA creates a new Chapter](https://drive.google.com/file/d/1X0WnBiWx1jTyh5mkdKCoulTp7xGvnDSR/view?usp=sharing)
- 02 - [A student edits information of their Chapter profile](https://drive.google.com/file/d/153RM9X34esEgDpc3Ik_Mv886tHma7SX5/view?usp=sharing)
- 03 - [TPUSA reviews and releases the information edited by the student](https://drive.google.com/open?id=1ia7Da0opvW1Z54QqTikcBFTXQUbMyu1-)
- 04 - [A student adds a new event to their Chapter](https://drive.google.com/open?id=1Mi1ZtBbWfEl_1JiDWGvlu3s8SO-JonJJ)
- 05 - [TPUSA reviews and releases the new event added by the student](https://drive.google.com/open?id=1mYlgS9-VGJd-6WBx9Z1zUY8D09HD9_dS)
- 06 - [TPUSA Creates a New Activism Hub](https://drive.google.com/open?id=12yYOfvqAiVYPtAYeg_ttAPv9kQsdh2Yp)
- 07 - [TPUSA Creating User Profile](https://drive.google.com/open?id=1Yh8XL18x57Om24sLfeEcQxx5U6pxD5nr)
- 08 - [Creating an Event](https://drive.google.com/open?id=1cx7LdcPeBU9kuTOomz0NLFLkifSHKzR0)
- 09 - [Adding News to the Stay-on-Point Section](https://drive.google.com/open?id=113DmmTC7HyXY6qRaOcbQ_a8O3ZD7yovh)
- 10 - [Adding Culture Posts to the Stay-on-Point Section](https://drive.google.com/open?id=1MBdNasC8c-tp2KkcGoRlUjUDvES3PZnG)
- 11 - [Creating New Pages on the TPUSA Website](https://drive.google.com/file/d/1-5vdus0tQM7LFB4jM0kfHnDlbYZ4nBUA/view?usp=sharing)
- 12 - [Creating Profiles for Governance Page](https://drive.google.com/open?id=162jq8ur9_IlxkjggC6o6OmWvZZtfUgkn)
- 13 - [Stay on Point Section](https://drive.google.com/open?id=1ZmSEYT3wCxmf4DhVAh6Zd1QXlEc_6ejL)
