### ISSUE TITLE
TPUSA - Adapt image

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#134]
Pat.

Por favor, pode elaborar uma imagem somente com o loguinho do evento (esse da lua e o astronauta) nesse formato aqui:

https://backend.tpusa.com/wp-content/uploads/2019/09/event02.jpg

Essa imagem:
![Americafest_Facebook_Banner (1)](https://user-images.githubusercontent.com/15367213/73183622-de5ea380-40f9-11ea-89e1-885a5fc1130b.jpg)

**Comment by Patricia-Torres** [comment]
![American Fest Logo](https://user-images.githubusercontent.com/43677737/73185464-e0763180-40fc-11ea-8e2d-142b2456c022.jpg)

**Comment by pedrojovelli** [comment]
Hi Jesse!

Could you please create a link on the TPUSA website for AmericaFest? I have included the information below. Please let me know if you need anything else. 

Website: tpusa.com/americafest
Picture banner: Attached
Date: February 27, 2020
Location: Cadillac Ranch, 186 Fleet St, Oxon Hill, MD 20745

Formsite Code:
<a name="form910287608" id="formAnchor910287608"></a>
<script src="https://fs21.formsite.com/include/form/embedManager.js?910287608"></script>
<script>
EmbedManager.embed({
key: "https://fs21.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTC0KL4MVNYdx3SKlBogGjHGizOKwLLamyU&910287608",
width: "100%"
});
</script>

Underneath the formsite form, it should say:
"Interested in sponsoring AmericaFest 2020? Please contact Alex Seavey at alex@tpusa.com. "

Thanks!
Alex

**Comment by Patricia-Torres** [comment]
![American Fest Logo2](https://user-images.githubusercontent.com/43677737/73188559-d4d93980-4101-11ea-95c9-f97e8026d9c2.jpg)

**Comment by Patricia-Torres** [comment]
![American Fest Logo3](https://user-images.githubusercontent.com/43677737/73190624-056ea280-4105-11ea-8ae8-b195e610d59e.jpg)

**Comment by pedrojovelli** [comment]
Image has been adapted.

Delivered.
