### ISSUE TITLE
Kirk's Hot Sauce: Vetorizar imagem

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#135]
![WhatsApp Image 2020-01-21 at 17 39 12](https://user-images.githubusercontent.com/43677737/73192244-82028080-4107-11ea-90b9-bb9ea42d85e6.jpeg)

**Comment by pedrojovelli** [comment]
Pat. Por favor, sobe o logo em vetor aqui.

**Comment by Patricia-Torres** [comment]
@pedrojovelli aqui:
[Kirk's Hot Sauce Logo.zip](https://github.com/rioslumstudio/Design/files/4134231/Kirk.s.Hot.Sauce.Logo.zip)
