### ISSUE TITLE
Diagramar proposta - Atlas Society

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#137]
Olá Fellipão. Tudo bem?

**Gostaria de pedir a ti para diagramar esta proposta:**
[The Atlas Society - Proposal.docx](https://github.com/rioslumstudio/Design/files/4122883/The.Atlas.Society.-.Proposal.docx)

**Com base neste arquivo aqui:**
https://drive.google.com/file/d/1n6FgRb-2rk7wc478oITldiRJMY4qOE6V/view?usp=sharing

Após diagramar. Gostaria de pedir a ti para focar nos dividers da proposta. Para clientes mais especiais como este, nós temos feito algo um pouco mais customizado usando algumas imagens deles. Este é o site deles: https://atlassociety.org/ Se você puder dar uma pesquisada no que eles fazem e possíveis imagens pra usar nos dividers, será de grande ajuda.

**Comment by felliperinschede** [comment]
Fala meu caro, segue o PDF da proposta. Qualquer dúvida to à disposição.
Abraço
[Atlas Society - Proposal.pdf](https://github.com/rioslumstudio/Design/files/4128624/Atlas.Society.-.Proposal.pdf)

**Comment by pedrojovelli** [comment]
Done. Delivered.
