### ISSUE TITLE
TPUSA: Production Page - Criar Páginas internas

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#14]
Fellipe.

Gostaria de pedir a ti, para tomar um tempo para criar os demais mockups de páginas internas da landing-page de PRODUCTIONS.

São elas:

**- Freedom Fights**
**- Poplitics**
**- Only in America**

Segue aqui pasta com os PSDs mais recentes caso necessite:
https://drive.google.com/drive/folders/1Oiuk5h8HCW-_141QdPMfl7g7ZSMhWWMD?usp=sharing

**Comment by felliperinschede** [comment]
Done

**Comment by pedrojovelli** [comment]
Fellipão. Peças estão show.

Nessa parte aqui, tira os pontinhos desse pattern. Deixa ele lisão.

![Screen Shot 2019-11-07 at 13 58 11](https://user-images.githubusercontent.com/15367213/68410016-d3cde700-0166-11ea-9bb4-30fc2e9c2382.png)

**Comment by felliperinschede** [comment]
Done
