### ISSUE TITLE
Blexit Covers

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#145]
AVATAR = Ye man Neon

BACKGROUND COVER = WE THE FREE (maria antoinet style )

Por favor, preparar mockups para apresentar como seria a aplicação destes avatares nas diferentes plataformas: Instagram / Twitter / Facebook.

Usar fundo preto e o YE MAN em neon com cor vibrante (usar as mesmas cores que usamos nos vídeos do evento de Charlotte)

Se puder deixar os PSDs prontos para receber a arte da cover. Eu (Pedro) irei elaborar junto contigo durante o dia hoje.

**Comment by Patricia-Torres** [comment]
**[Cover FB](https://drive.google.com/drive/folders/1I2CV2JOMYRvuYCp_FO7Y339TENahm8G4?usp=sharing)**

**[Avatar FB](https://drive.google.com/drive/folders/1Wd8E3zSAM84FpDF5XfB0xjaOR4jfe5P7?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**Pasta completa:**
[Blexit Social Media](https://drive.google.com/drive/folders/1S6VzjfQa1YOwsqy_pFR06pY5bRsbwZh3?usp=sharing)

**Comment by pedrojovelli** [comment]
Pat. Por favor, alguns pedidos.

- Gere mockups mobile do instagram com as opções do avatar.

- Sobre a capa do facebook, se você puder gerar um render sem som e sem os glitches, somente as mesmas cenas, mas sem os glitches de transição.

- Gostaria de pedir a ti para trabalhar em algumas opções para o vídeo de capa do facebook tendo alguns filtros de cores que vai trocando devagar... algo nessa pegada:
![Screen Shot 2020-02-04 at 12 53 38](https://user-images.githubusercontent.com/15367213/73761395-29edfe80-4745-11ea-8d37-277494cf056e.png)
![Screen Shot 2020-02-04 at 12 54 00](https://user-images.githubusercontent.com/15367213/73761396-29edfe80-4745-11ea-9926-ba6fbc083c46.png)
![Screen Shot 2020-02-04 at 12 54 17](https://user-images.githubusercontent.com/15367213/73761397-29edfe80-4745-11ea-9456-4135259c3580.png)

**Comment by pedrojovelli** [comment]
Pat, gostaria de pedir também pra ti, pra adicionar esse WE THE FREE no final.

![Screen Shot 2020-02-04 at 13 00 57](https://user-images.githubusercontent.com/15367213/73762126-24dd7f00-4746-11ea-9768-3955bc5c406b.png)

**Comment by Patricia-Torres** [comment]
As versões de capa do FB estão aqui:
**[FB COVER](https://drive.google.com/drive/folders/1I2CV2JOMYRvuYCp_FO7Y339TENahm8G4?usp=sharing)**

V1 a que eu já tinha feito
V2 sem glitch
V3 efeito de cor + WE THE FREE

**Comment by pedrojovelli** [comment]
- Retirar color filters do vídeo cover do Facebook
- Gerar uma versão de avatar extremamente simples (fundo branco e YE MAN preto e vice-versa)
- Gerar opções de capa de twitter com fotos de evento (palco do blexit em filtro de cor e sem filtro de cor)

**Comment by Patricia-Torres** [comment]
- **[AQUI](https://drive.google.com/file/d/1wf3HsZhH8HQnCYEYkZK5sdAA-Uf4TtQo/view?usp=sharing)** - Vídeo cover do Facebook sem filtro de cor e fiz esquema de "pop" com o WE THE FREE como sugestão.
- **[Avatar Twitter](https://drive.google.com/drive/folders/18bOqi0Y1l_5QQdGzxLxyKyBtkmtgI-wt?usp=sharing)**
- **[Avatar FB](https://drive.google.com/drive/folders/164RekqrqyXenA1HhefgLgI9i1Uq4Wngl?usp=sharing)** 
- **[Avatar INSTAGRAM](https://drive.google.com/drive/folders/16Th0TB22jW7l4SRflk35w3ht9Z4HUMj_?usp=sharing)**

**Comment by pedrojovelli** [comment]
Feito. Atualizado.
