### ISSUE TITLE
Blexit: My Blexit Film One

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#146]
Video files are here:
https://drive.google.com/drive/folders/1kCDtoxbBIRiqIpQdlk5NyuvdCmMGRqWM?usp=sharing

**Face and flag:**

P1099508.mp4
00:02 — 00:05

P1099507.mp4

00:42 — 00:49

01:14 — 01:18

01:31 — 01:34

_______________________________

**Walking:**

P1099514.mp4

00:14 — 00:19

P1099510.mp4

00:02 — 00:09

**Light video files:**
https://drive.google.com/drive/folders/1kCDtoxbBIRiqIpQdlk5NyuvdCmMGRqWM?usp=sharing

**Versions:**
https://drive.google.com/drive/folders/1_wZ8GrH5oXzj6Nfa0U-Jt1Co04Cn4WmE?usp=sharing

**Comment by pedrojovelli** [comment]
- Informações surgem seco (sem aquele efeitinho) (( como no trailer do filme maria antoinet ))

- A Blexit Production

- Quando ele diz … take-on, revela aquela cena dela dando um leve sorriso …

- Depois tela fica preta e aparece o “BLEXIT IS ABOUT FREEDOM“

- Explorar um pouco mais de trocas de câmera

**Comment by pedrojovelli** [comment]
Most up to date from Patricia:
https://drive.google.com/file/d/1Fc67VflfYQQFSKoAwvmgUbM6vqdUtPk8/view?usp=sharing

**Comment by pedrojovelli** [comment]
**Pedidos Jesse:**

No início… testar MY BLEXIT

testar MY BLEXIT - A Blexit Production (em baixo)


00:14
(( testar com e sem o fade pra mulher ))


Bottom should say:
Blexit North Carolina


Fazer com que o nome dela surja no esquema POP / POP … palavra por palavra



Tudo mudo no início, até o cara bater a palma… para dar pra ouvir de forma mais Limpa o pessoal falando



Avançar só um pouquinho a cena após ele bater palma, pois ele fica parado um tempo antes de ir sentar.


00:51 ((mostrar ela na cadeira….))

Finalizar com ela e a bandeira de fundo quando diz (( BLEXIT is about freedom))

**Comment by Patricia-Torres** [comment]
- testar MY BLEXIT - A Blexit Production (em baixo)
**Não seria MY BLEXIT STORY - A Blexit Production ?**

- 00:14 - (( testar com e sem o fade pra mulher ))
*DONE*

- Bottom should say: Blexit North Carolina

- Fazer com que o nome dela surja no esquema POP / POP … palavra por palavra

- Tudo mudo no início, até o cara bater a palma… para dar pra ouvir de forma mais Limpa o pessoal falando.
**tudo mudo seria a música de fundo sem som?**

- Avançar só um pouquinho a cena após ele bater palma, pois ele fica parado um tempo antes de ir sentar.
**Avançar seria para colocar em camera rápida?**

- 00:51 ((mostrar ela na cadeira….))
**DONE**

- Finalizar com ela e a bandeira de fundo quando diz (( BLEXIT is about freedom))
**DONE**

**Comment by Patricia-Torres** [comment]
Most up to date from Patricia:
https://drive.google.com/file/d/1hxTsaJZUHD_-1oYXkSqS5CMqGkq2cBWR/view?usp=sharing

**Comment by pedrojovelli** [comment]
**Vídeo com pedidos Pat. Estou a disposição para explicar qualquer dúvida.**

https://drive.google.com/file/d/1FvCuY1bX9FTbmIOKlI5Lj57bfBI9eQZf/view?usp=sharing

**Comment by pedrojovelli** [comment]
Vídeo correto:
https://drive.google.com/file/d/1oFLh0sJ6fGrFZ2kiiuH7rlX3Uei1jOHl/view?usp=sharing

**Comment by Patricia-Torres** [comment]
Most up to date: _ajuste de som do AND no começo_
- **[Com palmas aparecendo](https://drive.google.com/file/d/13zzBpzP5GyMfzy4zF5OM3vBQxWCoak6R/view?usp=sharing)**
- **[Sem palmas aparecendo](https://drive.google.com/file/d/1G-N6zYeJMWAXFDP3TkYnqutfFYgUKqjv/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Jesse most liked Option Two. Please, generate that in high quality:
https://drive.google.com/file/d/1G-N6zYeJMWAXFDP3TkYnqutfFYgUKqjv/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[Video em alta](https://drive.google.com/file/d/10DTH_O1IdCoYXB2TcXMz7EiGcXl4q3gh/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[Vídeos em alta - 02-06](https://drive.google.com/drive/folders/1_wZ8GrH5oXzj6Nfa0U-Jt1Co04Cn4WmE?usp=sharing)**

**Comment by pedrojovelli** [comment]
Video approved by Candace!

Please add the purchased music:
https://drive.google.com/drive/folders/1GkOxWzaWitrkoFQWAJVbIKNq6mChaOnv?usp=sharing

**Comment by Patricia-Torres** [comment]
Here is the MY BLEXIT Film One with the purchased music and in High Quality:
[Here](https://drive.google.com/file/d/12cLgOeH7DL7nsTDIsNX5qNwV1u4WjZBE/view?usp=sharing)

**Comment by pedrojovelli** [comment]
Thanks !

Closing the issue.
