### ISSUE TITLE
Subir os arquivos do Adobe Cloud nessa pasta

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#147]
https://drive.google.com/open?id=1k0c5N9HIuzBJ8iibskRcEJ0H3Hi5qd0a

Criar uma pasta chamada HERO **SHOTS and INTERVIES** e subir os arquivos que estão no Adobe Cloud

**Comment by pedrojovelli** [comment]
Pat, me diz novamente depois quantos Gigas você possui dos arquivos baixados. Gostaria de tentar pegá-los contigo semana que vem.

**Comment by Patricia-Torres** [comment]
45,2 GB

**Comment by pedrojovelli** [comment]
Obrigado Pat.
