### ISSUE TITLE
CPI - Economic Mobility Conceptual Direction

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#148]
**DUE DATE: February 17th**

( the shard in london )

Conceptual direction for Economic Mobility

Inspirations:
https://docs.google.com/document/d/1XoUIoPq0eOfx3NBE3Bt72a3jMkCCHYa2Q7y6f3x2A_s/edit?usp=sharing

From this

**Outras sub-brands que eles fizeram:**
https://www.centreforpublicimpact.org/failing-forward/

https://www.centreforpublicimpact.org/futureofcities

**Devemos elaborar um mockup de site com bases nestas sub-páginas acima. Um mockup com umas 3 sessões e latim text**

Brand Assets aqui:
https://drive.google.com/drive/folders/0B_3Wy3pMvxkhdXJZek1aSUhpazQ?usp=sharing

More here:
https://drive.google.com/drive/folders/1OZVJeJdYwi9ZNjDPUoo-dNymyAZirYCJ?usp=sharing

Fonts here:
[Henderson CPI Fonts-20190820T151623Z-001.zip](https://github.com/rioslumstudio/Design/files/4161023/Henderson.CPI.Fonts-20190820T151623Z-001.zip)

**Directions they seem to like best:**
![Screen Shot 2020-02-05 at 14 21 37](https://user-images.githubusercontent.com/15367213/73866475-ace58680-4823-11ea-8eda-c7b0efba0c22.png)

![Screen Shot 2020-02-05 at 14 22 14](https://user-images.githubusercontent.com/15367213/73866482-afe07700-4823-11ea-92e6-5e7b3f46eb11.png)

![Screen Shot 2020-02-05 at 14 21 32](https://user-images.githubusercontent.com/15367213/73866606-e74f2380-4823-11ea-958e-f4e5e10f92ad.png)

------------

City Scape
Small Town
Elaborate people

(( design about 3 different design directions for these ))

Sticking with colours and fonts

Uma opção seria buscar elaborar os prédios / cidades buscando um pouco do esquema de halftone.

They are looking for something visually vibrant / clean, simple design  / people doing things

Not going too dark on the color tone (for the main tone)

------------

Precisamos elaborar 3 versões de ilustrações. Isso significa 3 pra cada:
**(( City Scape
Small Town
Elaborate people ))**

Precisamos elaborar um loguinho para o Economic Mobility?

**Comment by felliperinschede** [comment]
Seguem algumas opções meu caro,

![Style01_City Scape_Shard_01](https://user-images.githubusercontent.com/57017535/74248804-8b224e80-4cbe-11ea-87dc-9148bf121bc3.jpg)
![Style01_People_01](https://user-images.githubusercontent.com/57017535/74248833-96757a00-4cbe-11ea-850a-05c8a1733187.jpg)
![Style01_SmallCity_Shard_01](https://user-images.githubusercontent.com/57017535/74248847-9c6b5b00-4cbe-11ea-9386-5d633b171c27.jpg)
![Style02_City Scape_Shard_01](https://user-images.githubusercontent.com/57017535/74248857-a0977880-4cbe-11ea-91d5-954e1691b78c.jpg)
![Style02_People_01](https://user-images.githubusercontent.com/57017535/74248860-a2613c00-4cbe-11ea-841e-01e54065b125.jpg)
![Style02_SmallCity_Shard_01](https://user-images.githubusercontent.com/57017535/74248862-a2f9d280-4cbe-11ea-9f1b-f0d2b70c757f.jpg)
![Style04_City Scape_Shard_01](https://user-images.githubusercontent.com/57017535/74248869-a4c39600-4cbe-11ea-805b-8128bbf2a9a2.jpg)
![Style04_People_01](https://user-images.githubusercontent.com/57017535/74248870-a55c2c80-4cbe-11ea-8acf-0620c55d298f.jpg)
![Style04_SmallCity_Shard_01](https://user-images.githubusercontent.com/57017535/74248875-a68d5980-4cbe-11ea-93a7-98adaa7f9367.jpg)

**Comment by felliperinschede** [comment]
Segue com as alterações ;D

![Style01_City Scape_Shard_01](https://user-images.githubusercontent.com/57017535/74361850-fdb62b80-4d9d-11ea-9fcc-6097fa5c0dbb.jpg)
![Style01_People_01](https://user-images.githubusercontent.com/57017535/74361863-027adf80-4d9e-11ea-8fcb-59f7725e7f1a.jpg)
![Style01_SmallCity_Shard_01](https://user-images.githubusercontent.com/57017535/74361870-0444a300-4d9e-11ea-92f5-a16764811921.jpg)

**Comment by felliperinschede** [comment]
Segue o layout alterado ;D
![Style01_SmallCity_Shard_01](https://user-images.githubusercontent.com/57017535/74373473-ec2b4e80-4db2-11ea-8aeb-f391b274a949.jpg)

**Comment by felliperinschede** [comment]
Segue anexo alterado ;D
![Style01_City Scape_Shard_02](https://user-images.githubusercontent.com/57017535/74542027-21ea4780-4f19-11ea-9f09-0fb955f094ba.jpg)

**Comment by pedrojovelli** [comment]
**Delivered:**
https://drive.google.com/drive/folders/1D5sJynNwND0jCOnnlu8xoJu6QxhPat5Z?usp=sharing
