### ISSUE TITLE
TPUSA Video Tutorial - Creating User

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#151]
Pat. Por favor, rs

Edite como vocÊ puder esse vídeo tutorial retirando partes que eu repito a mesma coisa um milhão de vezes ....

e no final eu digo "AWESOME"... acho que não tem necessidade...

https://drive.google.com/file/d/1Ye6Q3MdN4OC7SIUis6v7HyluiIZ4gBMc/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[Tutoriais da TPUSA](https://drive.google.com/drive/folders/1vL6cD87pXZwB21ZiXJk6_CzrY9EIp3sL?usp=sharing)**
O Creating User Profile é o número 7

**Comment by pedrojovelli** [comment]
2:10

Tem uma parte que eu falo: "**Right after that, i need to find DAVID JAMES here on my list**".

Eu falo DAVID JAMES numa entonação bem diferente. Isso deve ser resultado de cortes.... gostaria de pedir a ti, pra tentar suavizar essa parte... Do mais está show na minha opinião. Talvez o Jesse peça pra incluir algum comentário no início ou no final... vamos ver.

**Comment by Patricia-Torres** [comment]
Estranho pq eu não fiz nenhum corte nessa parte. E também não achei a entonação diferente. Mas de qualquer forma, eu peguei outro "DAVID JAMES" que vc falou e coloquei no lugar desse de 2:10

**[AQUI](https://drive.google.com/file/d/115IP5bySO2UxNFRyKMt9jKVej7oyMDTn/view?usp=sharing)**
