### ISSUE TITLE
TPUSA Video Tutorial - Creating Events

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#153]
Pat. Por favor, assista com calma e busque ajustar as pausas longas, as mil vezes que eu travei e por aí vai ...  please

VIDEO here:
https://drive.google.com/open?id=1bgCoqA8MD8PYF4ZfbTzOhP2A61-W-HFO

**Comment by Patricia-Torres** [comment]
https://drive.google.com/file/d/18LGVDPt2kmPCVlD58F7SR12Zrt4kcZ4d/view?usp=sharing

**Comment by pedrojovelli** [comment]
Delivered
