### ISSUE TITLE
BLEXIT - My Blexit Film Two

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#162]
We will do with Ariele now:

https://drive.google.com/file/d/13qOeOpUB9R1EJAfY8RsEupC2PT91NtKD/view?usp=sharing

---

**Purchased music is here:**
https://drive.google.com/drive/folders/1GkOxWzaWitrkoFQWAJVbIKNq6mChaOnv?usp=sharing

---

Jesse would like us to test a version of the music starting at 1:20 ( **1:20 from the music** )

---

Script here (Ariele):
https://docs.google.com/document/d/1HRavHVu4IdhDxM939ptC9YF6RyN5O_xENWukCmmBZE8/edit?usp=sharing

**Comment by Patricia-Torres** [comment]
**[Version one](https://drive.google.com/file/d/1gej9HmGHYXMw8U5r6iQ65f0cxH3Y3a79/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
- som da claquete precisa ficar mais alto

- parece que o som da claquete está meio OFF... pode checar ?

- Checar se o som sobe demais ou desce durante o filme. Garantir que haja um equilíbrio. 

- No início, trocar a parte que ela dá risada e fala, por essa parte aqui: (11:58) ... quando ele diz "are you excited?"... e ela diz... "i'm pumped"
https://drive.google.com/file/d/13qOeOpUB9R1EJAfY8RsEupC2PT91NtKD/view?usp=sharing

- Há uma parte, próximo dis 00:47 segundos, que há um corte "errado"... ela está dizendo .. "WE TAKE WHAT WE BELIEVE"... quando na verdade ela disse no video original: "We get to dictate what we believe".

**Comment by Patricia-Torres** [comment]
**[V2](https://drive.google.com/file/d/1Hk79MKXzW-WIXLqKpb5Wk74iHLRpXpHW/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
- Fazer com que o som da batida da claquete seja mais alto 


- Checar sons (jesse está dizendo que o som está estranho)


- Checar segundo 12. Jesse está dizendo que há um corte estranho nessa parte


- Segundo 19 ( the liberal speaks for Blacks) -- Jesse está dizendo que está OFF o corte -- final do segundo 18)


- segundo 41 ... 42 (hey, we are huge ... Jesse está dizendo que rola um corte muito seco nessa parte)

**Comment by Patricia-Torres** [comment]
- _Fazer com que o som da batida da claquete seja mais alto_
**I used the clapperboard sound from the previous video (Lisa). See if it gets better, please.**

- _Checar sons (jesse está dizendo que o som está estranho)_
**I used Adobe Audition again to eliminate noise. Let me know if that sound got better.**

- _Checar segundo 12. Jesse está dizendo que há um corte estranho nessa parte_
**I adjusted the cut**

- _Segundo 19 ( the liberal speaks for Blacks) -- Jesse está dizendo que está OFF o corte -- final do segundo 18)_
**I adjusted the cut**

- _segundo 41 ... 42 (hey, we are huge ... Jesse está dizendo que rola um corte muito seco nessa parte)_
**[I adjusted the cut](url)**

**[My Blexit - Arielle Chamber V3](https://drive.google.com/file/d/1YGrrxP5ljytmb6y9obrYsOeBdf-XQUjE/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
10 ... 12 ------ Blexit "can" finally

retirar a parte que ela diz "i'm ready" no final

**Comment by Patricia-Torres** [comment]
**[My Blexit - Arielle Chamber V4](https://drive.google.com/file/d/1QCyjrgOh5VRfEKX1aUNcwjpeKa0vRM2t/view?usp=sharing)**
