### ISSUE TITLE
BLEXIT - Experience Stage Videos ( Environments )

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#166]
Work on same dimensions as Blexit Atlanta (2 panels on each side // one main panel // one podium )

Liberation
WIlderness
Promised Land

---

**One Idea:**

Colors Associated with each film / An image from that film

Typography of that environment showing up slowly

Remain with the particles for the three environments

———

Other Idea:

**LIBERATION**: (remain the way it is, just change the TEXT and YE MAN color)

Maybe doing just the main screen cracking and the side screens with pieces falling down? Up for testings.

**PROMISED LAND** (Using particles and working around florals and leaves)

———

**Comment by Patricia-Torres** [comment]
- **[DRAFT 01](https://drive.google.com/drive/folders/1lrevXn0Ug8EVTCmog2yjv3b5xL7uqf2G?usp=sharing)**
- **[DRAFT 02](https://drive.google.com/drive/folders/1tJFQhml1dLrhkA_7y2DCfDQv0FnC7cCU?usp=sharing)**
- **[DRAFT 03](https://drive.google.com/drive/folders/1hgkhKfo81PIA_pbsJYcv7f6x4JCEyfAJ?usp=sharing)**

**Comment by pedrojovelli** [comment]
Draft 4 was Jesse and mine's favorite

- Jesse would like to see more small particles .. (maybe white smaller ones)
- Jesse wants us to get rid of the black shadows on the sides that shows up sometimes.
- Devemos aplicar um pedaço da cena do carinha olhando para o mar do vídeo do LIBERATION no final

**Comment by pedrojovelli** [comment]
Jesse quer fazer o esquema de WILDERNESS em neon.

PROMISED LAND para aparecer em algume squema legal de ROOTS / florais

**Comment by pedrojovelli** [comment]
**PEDIDOS MAIS RECENTES PARA CONSIDERAR REFERENTE AO LIBERATION**

Ir um pouco mais próximo do Video 06 daqueles primeiros videos que enviamos.

Talvez ir um pouco mais vivo. Evitar ir muito vivo

Talvez intensificar um pouco mais de azul e turquesa

Talvez adicionar mais particulas pequenas em branco, tentando espelhar mais o vídeo 06.

Talvez ir revelando em fade

Talvez fazer com que a palavra liberation apareça na mesma velocidade do vídeo 6

Ye man aparecer após o LIBERATION e depois começar a rolar o FADE-IN

**Comment by pedrojovelli** [comment]
**WILDERNESS** goes black

Particles start to show up

Wilderness shows up in neon

The particles starts changing Colors slowly

Maybe using some red, orange






Escrever PROMISED LAND usando máscaras de florais crescendo, raízes

**Comment by pedrojovelli** [comment]
**Jesse's link:**
https://docs.google.com/document/d/1xWExbU4j72HjrnFJFnsoR-4DRZ3yJSUcGmrSFK_oXXs/edit?usp=sharing
