### ISSUE TITLE
BLEXIT - Chapter Userflow

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#171]
Mike, tudo bem?

Por favor, pode validar pra mim se seria possível fazer um esquema assim?

Fico a disposição pra conversar sobre qualquer dúvida sua referente a essa idéia do Chapter do Blexit.

Meu objetivo é validar isso contigo antes de enviarmos para o Jesse e darmos sequência.

[Blexit-Chapter-Userflow.pdf](https://github.com/rioslumstudio/Design/files/4177878/Blexit-Chapter-Userflow.pdf)

**Comment by robanquieri** [comment]
@pedrojovelli melhor marcar uma reunião pra validarmos isso.
