### ISSUE TITLE
Blexit - Social Media Announcement 10" Video

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#173]
Purchased videos:
https://drive.google.com/drive/folders/1NlzRTFp56nnzR0TaCUNtBGq9-LvEi1kC?usp=sharing

-----

Elaborar vídeo de 10 segundos com a mesma música dos vídeos de 15 e 30 segundos que fizemos para Fort Lauderdale com os seguintes textos:

(Aparece primeiro somente) New BLEXIT Event
 
(aparece em seguida somente) Our Liberation
(aparece em seguida na linha de baixo) Coming Soon

**Usar as seguintes cenas:**
https://www.pond5.com/pt/stock-footage/item/21946411-fort-lauderdale-beach

https://www.pond5.com/pt/stock-footage/item/113075252-international-flag-alley-way-fort-lauderdale-fl

**Comment by Patricia-Torres** [comment]
**[10'' TEASER](https://drive.google.com/file/d/10RmoQd-YM-DLaYF4iJXEJJ3snmXBTpwV/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[10'' TEASER](https://drive.google.com/file/d/139h3UVU_Q9wBKaK9O-lo6LMG4GLMyjnT/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[v2 10'' TEASE](https://drive.google.com/file/d/10XMvqI8480zAhsE6BZUuiliLlyzX9-F5/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[v3 10'' TEASER](https://drive.google.com/file/d/1vlhyyO7rAckZmigbCi5rD1TqXPEKUhyT/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Mídias compradas aqui:
https://drive.google.com/open?id=1NlzRTFp56nnzR0TaCUNtBGq9-LvEi1kC

Jesse gostou desta versão aqui:
https://drive.google.com/file/d/139h3UVU_Q9wBKaK9O-lo6LMG4GLMyjnT/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[TEASER 10'' for post and stories](https://drive.google.com/drive/folders/1iorSiajOW-aZVnw2sUAsfeOwOF93QQIH?usp=sharing)**

**Comment by pedrojovelli** [comment]
Pat. Amanhã teremos de apresentar mais um desses, mesma estrutura, porém com 2 vídeos diferentes rolando de fundo .. revelando mais a cidade ....

Discutimos isso amanhã.
