### ISSUE TITLE
TPUSA Video Tutorial - Adding News

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#175]
Pat. Por favor, faça usa mágina neste vídeo de tutorial ...

https://drive.google.com/file/d/1SOAuuEjGic4lyje2L9NyNx1cIOwT75uz/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[09 - Adding News](https://drive.google.com/file/d/1vI7xYRFcHoaQATgattvf6RykB3y3g2Eq/view?usp=sharing)**
