### ISSUE TITLE
BLEXIT: Side Square Screen - 2 videos

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#18]
- Um vídeo seria somente de cores vibrantes trocando de forma suave... tipo .... verde limão... passando pra azul... de azul pra amarelo (as cores do pattern).

- Outro vídeo seria listras passando..

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1KBq3vXoyB_lVzv317HnZfD1rsbXvp7ob

**Comment by pedrojovelli** [comment]
Pat ! o vídeo das cores está perfeito !... quanto ao segundo vídeo ...que é o das faixas passando .. eu estava pensando em algo mais nessa pegada aqui:

![teste](https://user-images.githubusercontent.com/15367213/68411456-46d85d00-0169-11ea-9cdb-1f3354c955cb.gif)

(( eu fiz rapidinho no photoshop .... mas a idéia é talvez fazer algo assim ... mais devagar e as faixas indo da esquerda pra direita ...  talvez mantendo aquele mesmo esquema das cores trocando de fundo ... ))

**Comment by Patricia-Torres** [comment]
Vc fez da direita para a esquerda, é para fazer da direita para a esquerda mesmo?
só para saber se vc se confundiu rs

**Comment by pedrojovelli** [comment]
é pra fazer a faixa ir da ESQUERDA para a DIREITA.
 Desculpa .. fiz na correria ...

**Comment by Patricia-Torres** [comment]
![image](https://user-images.githubusercontent.com/43677737/68413475-17c3ea80-016d-11ea-86d4-2e8e96deef9a.png)
![image](https://user-images.githubusercontent.com/43677737/68413492-21e5e900-016d-11ea-93cf-0e078fc504a3.png)
Prefere que fique uma distância assim entre um e outro (a parte branca da primeira imagem é a distancia) ou faz colado um no outro como na segunda imagem?

**Comment by Patricia-Torres** [comment]
**DONE**

me fala o que acha 
https://drive.google.com/drive/folders/1KBq3vXoyB_lVzv317HnZfD1rsbXvp7ob

**Comment by pedrojovelli** [comment]
Pat !

Eu gostei do vídeo ...

Se você puder fazer uma terceira versão ...pegando o primeiro vídeo ... com as cores trocando ... e as barrinhas brancas indo da esquerda pra direita em loop ....

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/drive/folders/1KBq3vXoyB_lVzv317HnZfD1rsbXvp7ob
