### ISSUE TITLE
Pedido The Fashion Connection

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#180]
thefashionconnection.org

![Screen Shot 2020-02-11 at 13 48 27](https://user-images.githubusercontent.com/15367213/74258556-4950d280-4cd5-11ea-9f27-d5c4934a570c.png)

**Comment by pedrojovelli** [comment]
Mike.
Fashion Connection has asked us if we can upload these profiles.

Would you have a chance to put these up?

https://drive.google.com/drive/folders/1y9sfhP6lbLGquh8ExiqSEQ9QI3zyQr_c?usp=sharing

**Comment by robanquieri** [comment]
done

https://www.thefashionconnection.org/
