### ISSUE TITLE
Ryan - Video Editing

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#186]
https://www.dropbox.com/s/0zajb6vt47dl2y6/2004%20Crew%20Boat%20HOF%20speech-.mp4?dl=0

https://www.dropbox.com/s/8sociyr0sb0tuwh/MP%20HOF%202019%20the%202004%20National%20Rowing%20Championship%20Boat.mp4?dl=0

**Comment by pedrojovelli** [comment]
Pat. O Jesse gostaria de fazer alguns cortes nesse documento. Esse seria o primeiro refinamento dele. Após executar estes cortes, o Jesse irá fazer mais cortes pra tentar chegar num ideal desse filme.

https://docs.google.com/document/d/1CWQu9Iq-j7RJprlQbbYtcOeNO76jkoRuyfIDoUi3bM8/edit

**Comment by pedrojovelli** [comment]
Pat, tudo bem ?

Segue aqui algumas seleções do Jesse referente ao vídeo para chegarmos a 1 minuto de vídeo:

**Me chama quando você for pegar estas edições:**

**Cuts here**
https://docs.google.com/document/d/1CWQu9Iq-j7RJprlQbbYtcOeNO76jkoRuyfIDoUi3bM8/edit?usp=sharing

**Comment by Patricia-Torres** [comment]
**Draft Two: 1 minute film**

- [Music one - Ryan Olympic Media - Speech](https://drive.google.com/open?id=1zef5vok0ZSgTdKIg9fZotYnSLoxWlorc)
- [Music two - Ryan Olympic Media - Speech](https://drive.google.com/open?id=1ChBTTb2j6bWFmoXbR9Q2I1j3Yst0DY8y)
- [Music three - Ryan Olympic Media - Speech](https://drive.google.com/open?id=13Mrz1QLDcvjWS-xBzOzHEZoNzwqYvrMR)
- [Music four - Ryan Olympic Media - Speech](https://drive.google.com/open?id=1zeaDAZXQqIs71Ts4uS8aLudptJvgrR43)
- [Music five - Ryan Olympic Media - Speech](https://drive.google.com/open?id=1iBuMLbeZNNSh_xfUnJfuoNXVfdkHnyoQ)
- [Music six - Ryan Olympic Media - Speech](https://drive.google.com/open?id=1gsbpaZjwWj-XDG8cKa6kpS9Lw2J-n3H3)
- [Music seven - Ryan Olympic Media - Speech](https://drive.google.com/open?id=1KMsu7mcyougz2BFoI54FaEqFKNnKTyBf)

**Comment by pedrojovelli** [comment]
**Deixar mais suave:**

Parents part seems to have very hard cuts.
Around 00:20 (( it was my parents blah blah blah … )

Also 00:47 (beginning of the coach section.

**Comment by Patricia-Torres** [comment]
essa parte:
"Parents part seems to have very hard cuts"
Eu não consegui mexer pq os cortes não tem para onde ir pois tem outras palavras grudadas.

**Draft Three:**
https://drive.google.com/file/d/1wKU89fOvxHMLQn8baAxBRUGCkSdq_eKB/view?usp=sharing

**Comment by pedrojovelli** [comment]
Footages para adicionar no vídeo:

**From Jesse:**
I have placed my thoughts on Ryan's B roll at the bottom of this document:

https://docs.google.com/document/d/1CWQu9Iq-j7RJprlQbbYtcOeNO76jkoRuyfIDoUi3bM8/edit?usp=sharing

**Comment by pedrojovelli** [comment]
**Purchased song:**
https://drive.google.com/drive/folders/1rIf_XaSO-gv_oVrvBrAr2ULEjBckiUHd?usp=sharing

**Comment by Patricia-Torres** [comment]
https://drive.google.com/open?id=125aexkRmq-Bxa_jBJg4PxaDSE11EZt3v

**Comment by pedrojovelli** [comment]
![WhatsApp Image 2020-02-19 at 17 56 24](https://user-images.githubusercontent.com/15367213/74875860-b998cd00-5341-11ea-8681-bf709138716b.jpeg)

**Comment by pedrojovelli** [comment]
**Final File here:**
https://drive.google.com/file/d/1E6FGyINEcJ6aS3v6jMBqE90Gh8lHJ4Rb/view?usp=sharing
