### ISSUE TITLE
Blexit - My Blexit Film #3

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#187]
**Wilfred's MY BLEXIT film**

https://docs.google.com/document/d/1HRavHVu4IdhDxM939ptC9YF6RyN5O_xENWukCmmBZE8/edit?usp=sharing

**Comment by Patricia-Torres** [comment]
https://drive.google.com/drive/folders/1QH0ZobaujbmFyeKD07xuUB5w0ue4ijbx?usp=sharing
