### ISSUE TITLE
BLEXIT: Walk-on Video + Backdrop flag

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#19]
Pat. Por favor, se puder elaborar as peças deste novo speaker:

**Bishop E.W Jackson**

**Comment by Patricia-Torres** [comment]
**DONE**

Todos os Backdrops só da bandeira estão aqui:
https://drive.google.com/drive/folders/1W_hVA8yEk-6ZjFuEpSB5k8hxN1yqSsTa

Walk-on do Bishop E.W. Jacksonpronto para receber o áudio.

**Áudios que faltam:**

- David Harris Jr.
- Terrence Williams
- Maj Toure
- KingFace
- Bishop E.W. Jackson

**Comment by pedrojovelli** [comment]
Ok. Obrigadão Pat.

Me passa o link específico do vídeo do WALK-ON do BISHOP E.W.

**Comment by Patricia-Torres** [comment]
Não está renderizado, esperando áudio.

**Comment by pedrojovelli** [comment]
Ok.

**Comment by pedrojovelli** [comment]
Audios novos estão aqui:

OK - David Harris Jr.
OK - Terrence Williams
OK - Maj Toure
OK - KingFace
OK - Bishop E.W. Jackson
