### ISSUE TITLE
BLEXIT - Neon Bracelet Designs - DUE Feb 26th

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#195]
Font: DIN PRO BLACK

Message from the bracelet:

Text: Blexit We The Free

Text: We The Free

Logo: Blexit

![Screen Shot 2020-02-21 at 14 47 14](https://user-images.githubusercontent.com/15367213/75058067-14086980-54b9-11ea-8bea-b7bb767f0dab.png)

**Comment by felliperinschede** [comment]
Segue ai meu querido, é por ai?

![Blexit_Bracelet_04](https://user-images.githubusercontent.com/57017535/75063881-364fb680-54bc-11ea-9231-18b5fe287cd0.jpg)
![Blexit_Bracelet_02](https://user-images.githubusercontent.com/57017535/75063877-3485f300-54bc-11ea-997d-20c000493cba.jpg)
![Blexit_Bracelet_03](https://user-images.githubusercontent.com/57017535/75063879-35b72000-54bc-11ea-9bed-123b2405553f.jpg)
![Blexit_Bracelet_01](https://user-images.githubusercontent.com/57017535/75063869-30f26c00-54bc-11ea-9417-c16a63e00ecb.jpg)

**Comment by felliperinschede** [comment]
Ta na mão o/

![Blexit_Bracelet_06](https://user-images.githubusercontent.com/57017535/75065461-4e750500-54bf-11ea-9c98-03205bd60f38.jpg)
![Blexit_Bracelet_05](https://user-images.githubusercontent.com/57017535/75065451-4a48e780-54bf-11ea-96c1-3f377032b9e2.jpg)

**Comment by felliperinschede** [comment]
Ta ai meu caro o/
![Blexit_Bracelet_06](https://user-images.githubusercontent.com/57017535/75068375-71a2b300-54c5-11ea-8287-4c56ce43b541.jpg)

**Comment by pedrojovelli** [comment]
Files sent to candace. Waiting more specs from the merchandising company in case they need.

[Bracelet.zip](https://github.com/rioslumstudio/Design/files/4264220/Bracelet.zip)
