### ISSUE TITLE
BLEXIT - Live Stream Transition

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#198]
Pat. Isso é o que o Luke, responsável pelo evento ao vivo falou sobre o vídeo que fizemos do YE MAN em 3d:

**"Nice, but I can’t match the wipe.  I need a few frames where the entire screen is covered so I can cut underneath between sources."**

Eu estava pensando que talvez pudessemos fazer um esquema co uma barra inteira na mesma cor do ye man cobrir a tela rapidinho de fundo.

**Comment by Patricia-Torres** [comment]
Example:
https://drive.google.com/open?id=1y1jdkojlT1w2IVnh7B1Js1s0x1NFcnV1
Application:
https://drive.google.com/open?id=16ZschHBUSOijbdGCIQOInS2tAleDyDgC

**Comment by Patricia-Torres** [comment]
Example:
https://drive.google.com/open?id=1iP567bYqp5P0f4OhHsfnd9lGvgVZkm1y
Application: 
https://drive.google.com/open?id=1LBG0sCtgfhDxcGPug2JnqrJ3KEaQMmTC

**Comment by Patricia-Torres** [comment]
Green Example:
https://drive.google.com/open?id=1lLYqDyugNamiXtv7Yl174TCBETUEzslN
Green Application:
https://drive.google.com/open?id=16DXg1KvVWZ1I6ppFkDSWJengJTpCX_Wr

**Comment by Patricia-Torres** [comment]
Teal Example:
https://drive.google.com/open?id=1JaexlMEEhT-JeWEZmuVVYqf2C2Hpj105
Teal Application:
https://drive.google.com/open?id=12VW0ZK9RiOF_mYhz9C_yuOepH3HfFYxD

**Comment by Patricia-Torres** [comment]
Pink Example:
https://drive.google.com/open?id=1jCzuIlhjOkxN_nhFZDFn9VO0yt0E4lVF
Pink Application:
https://drive.google.com/open?id=1CJ8iBPpPW2_ejOZn1GHU8Jj6mYaERhp-
