### ISSUE TITLE
TPUSA: Flag Designs

### ISSUE THREAD

**Issue by rioslumstudio** [rioslumstudio/Design#2]
**AMERICA FIRST Feedback**

- Elaborar versões com bordas nas laterais e sem a linha. (Posso explicar melhor)

- Elaborar versões com bordas nas laterais e com as linhas

- Criar verão com fundo branco com AMERICA FIRST em navy blue

- Criar verão com fundo branco com AMERICA FIRST em red

- Criar verão com fundo navy blue com AMERICA FIRST em branco

- Criar uma versão mais livre usando as cores acima e esta ilustra:
https://comps.canstockphoto.com/number-1-one-sports-fan-foam-hand-with-eps-vectors_csp40841437.jpg

________________________________

**SOCIALISM SUCKS**
- Fazer com que as artes no mockup fiquem um pouco mais pra baixo. Jesse achou que estão muito altos
- Criar mais uma versão escrevendo Socialism Sucks em 1 linha (seguindo estilo de fonte mais suave).

**Comment by felliperinschede** [comment]
Done

**Comment by pedrojovelli** [comment]
Fellipão. 

Esta é uma referência de apresentação para camisetas. Sugiro que a gente use essa base ... tipo 2 mockups por página.

[TPUSA Freedom Design.pptx](https://github.com/rioslumstudio/Design/files/3793681/TPUSA.Freedom.Design.pptx)


Por hora, vou pedir pra você não alterar as capas. Vou checar com o Jesse o título do PPT.

**Comment by pedrojovelli** [comment]
Por favor, inserir este logo pequenininho na lateral direita superior.

![rioslum_logo](https://user-images.githubusercontent.com/15367213/67946880-16208280-fbc1-11e9-827d-88c2d405f06c.jpg)

**Comment by pedrojovelli** [comment]
Divider PSDs:
https://drive.google.com/drive/folders/1aRT5XLTxN1-6rwxeIkgHUukA2vfV5sYs?usp=sharing

**Comment by felliperinschede** [comment]
Done ;D

**Comment by pedrojovelli** [comment]
Fellipão !

Por favor, altera o texto dessa capa aqui:

![Screen Shot 2019-10-31 at 13 34 30](https://user-images.githubusercontent.com/15367213/67966796-3e20dd80-fbe3-11e9-9d4f-aa7d81041ace.png)

Para este aqui:
**FLAG** Designs

**Comment by felliperinschede** [comment]
Feito

**Comment by pedrojovelli** [comment]
Excellent !

Enviado para o cliente !

**Comment by pedrojovelli** [comment]
Cliente não respondeu mais. Fechando issue por falta de retorno.
