### ISSUE TITLE
BLEXIT: WE GOT LOVE ajustes

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#20]

**Comment by Patricia-Torres** [comment]
**DONE**
We Got Love V1 - Final Edited
https://drive.google.com/drive/folders/1Ged2Tvkixoo_N6-xnm2IShWsrzTOYvg_

**Comment by pedrojovelli** [comment]
Algum erro com o link

![Screen Shot 2019-11-07 at 15 59 10](https://user-images.githubusercontent.com/15367213/68418734-8f971280-0177-11ea-95bb-e60e3cd0e752.png)

**Comment by pedrojovelli** [comment]
Revisar em 3:03

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/drive/folders/1Ged2Tvkixoo_N6-xnm2IShWsrzTOYvg_

**Comment by Patricia-Torres** [comment]
**Done**
https://drive.google.com/drive/folders/1Ged2Tvkixoo_N6-xnm2IShWsrzTOYvg_

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1Ged2Tvkixoo_N6-xnm2IShWsrzTOYvg_?usp=sharing

**Comment by Patricia-Torres** [comment]
Mudar para Kill the hate.

**Comment by Patricia-Torres** [comment]
**DONE**

WE GOT LOVE
https://drive.google.com/drive/folders/1Ged2Tvkixoo_N6-xnm2IShWsrzTOYvg_?usp=sharing

WE GOT LOVE OUTRO
https://drive.google.com/drive/folders/1SHQFQBIWYC2RkwGr76QJs1XCviWbWsFe?usp=sharing
