### ISSUE TITLE
BLEXIT - 3d Ye man on the corner - DUE March 3rd

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#205]
Generate a sequence of numbered PNGs for this animation.

Also, generate one version with alpha channel.

---

**This came from Luke (the guy who takes care of the live streaming):

I will need these in numbered PNGs with alpha on a 5 or 10 second loop.   1080p 29.97 sized to position.   Animation will tie up CPU resources on the switcher.  If that causes a resource issue, then I’ll simply use a static png from the animation.

File that was approved:
https://drive.google.com/file/d/1Ec95-tNRfYQ0OraybLL8BuU3yEEXxjjU/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**[3D Ye Man Lower Third](https://drive.google.com/open?id=1pgPJpSx_5GrkthBoW0Ohg3uCSoehpOWb)**
