### ISSUE TITLE
BLEXIT - Generate transitions with alpha channel - DUE TODAY (March 2nd)

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#207]
Generate all color transitions we have created.

**Please follow these instructions from Luke:**

From a design stand point these are awesome.   Can you send me a folder of numbered png’s or a  QT Movie with embedded alpha channel so I can test on my system today?   (QT 4444)

**Comment by Patricia-Torres** [comment]
- [3D Ye Man Transition](https://drive.google.com/file/d/1UdaxZWqC7Dkx2Pd5qLZywcXyvYsVlrx7/view?usp=sharing)
- [Colorful Transition](https://drive.google.com/open?id=19jybd0SWydqVk40pwXKofUs0rKhH8ANz)
- [Pink Transition](https://drive.google.com/open?id=1MLoiXCldOmNiwo0cEtw7EG8ZWVdgRNfh)
- [Teal Transition](https://drive.google.com/open?id=1SCum54IkwlEx66JDnAY_NR0jN1HyzdoE)
- [Green Transition](https://drive.google.com/open?id=1CH_-5HU2PehS_bB-S_fbbRlw6OFz5o6W)

**Comment by pedrojovelli** [comment]
Thanks so much !!!
