### ISSUE TITLE
BLEXIT: Walk-on music edit TERRANCE

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#21]
música de intro do **TERRANCE**:

https://www.youtube.com/watch?v=AOBQkHy8_p8

musica partindo dessa parte: 01:11

Audio do Terrance:
https://drive.google.com/file/d/1_-CTnWnSu_Y6gqsoh4Rrb_Xvubqt-qM3/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F?usp=sharing

**Comment by pedrojovelli** [comment]
Lindo
