### ISSUE TITLE
OLYMPIC MEDIA - Website in Adobe XD

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#214]
Hi Thiago.

As we have discussed. We are in need switch the website from Photoshop to Adobe XD.

**This is the most recent editable file in Adobe XD:**
[Website 2.zip](https://github.com/rioslumstudio/Design/files/4283250/Website.2.zip)

**This is where you can find the PSD files:**
https://drive.google.com/drive/folders/1mUJLb-CW0odl994ILCwk1JhpirWaVc88?usp=sharing

Please, let me know if you need any other information.

**Comment by thipele** [comment]
I already sent it to Rogerio. It seems to be ok.
