### ISSUE TITLE
BLEXIT: Walk-on music edit DAVID HARRIS JR

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#22]
música de intro do DAVID HARRIS:

https://www.youtube.com/watch?v=PH3KD2bb_yc

musica partindo dessa parte: 00:05

Audio do Harris:
https://drive.google.com/file/d/1Ny5pKY99fIgHSQjG0QsP2ubGz7edxnOs/view?usp=sharing

**Comment by Patricia-Torres** [comment]
'**DONE**

https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F?usp=sharing

**Comment by pedrojovelli** [comment]
Pat.

 Este audio está errado. Ele está com música de fundo.... por favor, insira o audio RAW. Que é o que eu adicionei no link acima:
https://drive.google.com/file/d/1Ny5pKY99fIgHSQjG0QsP2ubGz7edxnOs/view?usp=sharing

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F?usp=sharing

**Comment by pedrojovelli** [comment]
Enviado para o Jesse
