### ISSUE TITLE
TPUSA - Video tutorials - March 6th

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#220]
Hi Patricia.

Please, would you mind editing these two tutorials I did for TPUSA ?

The suggestions for titles are:

- Adding Sidebars

- Adding Image Galleries

**Files for us**
https://drive.google.com/drive/folders/1CyEKNpjEafXNfFLTleshuk_qZSpTinxu?usp=sharing

**Comment by Patricia-Torres** [comment]
- [Adding Sidebars](https://drive.google.com/open?id=1Bp_VaMjYqtPBM2-IC_j2MldRK_dn057K)

- [Adding Image Galleries](https://drive.google.com/open?id=1zmMYSvk-_oyFkYs9jf1ctDOnLk1x6c08)
