### ISSUE TITLE
TPUSA - Image replacement

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#227]
**The client has asked Rio to change this image:**
https://www.tpusa.com/_next/static/static/images/hero-banner/2b635c005dae89e25b052bed2bce5714.jpg

**The new images from TPUSA are here:**
https://drive.google.com/drive/folders/1rJyvhLg9P-4Bf8uNG8PK5c0iSkYvKqhj?usp=sharing

**Comment by Patricia-Torres** [comment]
![Banner-Chapters](https://user-images.githubusercontent.com/43677737/76235794-63b19980-620a-11ea-94ae-ca1ef627f558.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters02](https://user-images.githubusercontent.com/43677737/76237141-85138500-620c-11ea-84a5-feb595e3f1e5.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters03](https://user-images.githubusercontent.com/43677737/76240799-9fe8f800-6212-11ea-95ae-6cf51feaad6f.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters04](https://user-images.githubusercontent.com/43677737/76241124-41704980-6213-11ea-8d1d-c51794d8c1be.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters05](https://user-images.githubusercontent.com/43677737/76241976-a2e4e800-6214-11ea-9abb-0a25546b130b.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters06](https://user-images.githubusercontent.com/43677737/76245032-f3127900-6219-11ea-94d4-508c127e6ae1.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters06](https://user-images.githubusercontent.com/43677737/76245607-f0fcea00-621a-11ea-82d3-40110c2354ca.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters07](https://user-images.githubusercontent.com/43677737/76246139-e7c04d00-621b-11ea-97ce-869d33562162.jpg)
![mockup](https://user-images.githubusercontent.com/43677737/76246143-e8f17a00-621b-11ea-8f71-d48664a0b598.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters08](https://user-images.githubusercontent.com/43677737/76247067-ac268280-621d-11ea-8d61-f5ff4426b70a.jpg)
![old](https://user-images.githubusercontent.com/43677737/76247071-ad57af80-621d-11ea-9cc4-34e71d3467b3.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters08](https://user-images.githubusercontent.com/43677737/76247087-b6488100-621d-11ea-97c3-33e3f5b210d9.jpg)
![mockup8](https://user-images.githubusercontent.com/43677737/76247090-b779ae00-621d-11ea-96d4-e49bbc0346f5.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters09](https://user-images.githubusercontent.com/43677737/76248493-31ab3200-6220-11ea-9f8b-2e44c95e8c39.jpg)
![mockup9](https://user-images.githubusercontent.com/43677737/76248495-32dc5f00-6220-11ea-944e-c9c3c7e5e07d.jpg)

**Comment by Patricia-Torres** [comment]
![Banner-Chapters-new](https://user-images.githubusercontent.com/43677737/76255366-d5024400-622c-11ea-9253-29c55464a1f9.jpg)
![Banner-Chapters-new02](https://user-images.githubusercontent.com/43677737/76255376-d6cc0780-622c-11ea-86b3-150b54a3f25b.jpg)

**Comment by Patricia-Torres** [comment]
![Mockup-Banner-Chapters-new](https://user-images.githubusercontent.com/43677737/76313877-91ebb380-62b4-11ea-9e2d-0a0c3184a5a4.jpg)
![Mockup-Banner-Chapters-new2](https://user-images.githubusercontent.com/43677737/76313885-944e0d80-62b4-11ea-962c-c4b545e0420a.jpg)

**Comment by Patricia-Torres** [comment]
![Mockup-Banner-Chapters-new](https://user-images.githubusercontent.com/43677737/76315298-2fe07d80-62b7-11ea-8dd4-9f95f092d569.jpg)
![Mockup-Banner-Chapters-new2](https://user-images.githubusercontent.com/43677737/76315303-31aa4100-62b7-11ea-8e81-8f3b2cd51e25.jpg)
