### ISSUE TITLE
BLEXIT: Walk-on: Brandon - Bishop - KingFace - Maj

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#23]
Aplicar os audio e retirar a música do Singularity. Deixar os vídeos no mesmo tempo dos audios

- Brandon Tatum
- Bishop
- KingFace
- Maj

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F

**Comment by pedrojovelli** [comment]
Pat.

Por favor, faça com que o FADE-OUT do MAJ TOURE saia antes... está demorando muito pra sair após a música acabar ....

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F?usp=sharing

**Comment by pedrojovelli** [comment]
Enviado para o Jesse
