### ISSUE TITLE
TPUSA - Tutorial Neon Over White

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#232]
**Sugestão para título do vídeo:**
Neon Typography on White

**Videos here:**
https://drive.google.com/drive/folders/1tFwamIRVPAdPsltD2jNBsioJCTAMwKiH?usp=sharing

---

Pat. Estou enviando dois vídeos. Por favor, se você puder editar os dois ... assistir e ouvir / editar as minhas cagadas ....rs

**Comment by pedrojovelli** [comment]
[Typography Reference.psd.zip](https://github.com/rioslumstudio/Design/files/4319212/Typography.Reference.psd.zip)

**Comment by Patricia-Torres** [comment]
https://drive.google.com/open?id=1QcC4s56PKOj3GxxoLZJ5LyKKjezQVGxx

**Comment by pedrojovelli** [comment]
Delivered
