### ISSUE TITLE
TPUSA - Organizing Freedom - Home page Banner

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#240]
- https://www.pond5.com/pt/stock-footage/item/42185022-mount-rushmore-zoom

- https://www.pond5.com/pt/stock-footage/item/112306739-mountrushmore-timelapse

- https://www.pond5.com/pt/stock-footage/item/87228278-statue-liberty-aerial-pulling-back-daytime-manhattan-skyline

- https://www.pond5.com/pt/stock-footage/item/71072088-abraham-lincoln-memorial-sliding-shot-washington-dc

- https://www.pond5.com/pt/stock-footage/item/21877176-abraham-lincoln-memorial-estatua-em-washington-dc

- https://www.pond5.com/pt/stock-footage/item/98348168-time-lapse-washington-dc-people-visit-memorial-monument-obel

- https://www.pond5.com/pt/stock-footage/item/76919411-washington-monument-tower-landmark-flags-dc-america-4k-stock

- https://www.pond5.com/pt/stock-footage/item/173448-monumento-de-washington-dc

- https://www.pond5.com/pt/stock-footage/item/87863795-aerial-view-golden-gate-bridge-san-francisco-california-usa

- https://www.pond5.com/pt/stock-footage/item/82677887-indianapolis-indiana-usa

- https://www.pond5.com/pt/stock-footage/item/10715740-vista-aerea-do-sol-sob-o-iluminado-oakland-bay-bridge-san-fr

- https://www.pond5.com/pt/stock-footage/item/79013026-night-aerial-chicago-usa-4k

**Comment by pedrojovelli** [comment]
https://www.pond5.com/pt/stock-footage/item/71072088-abraham-lincoln-memorial-sliding-shot-washington-dc

https://www.pond5.com/pt/stock-footage/item/79013026-night-aerial-chicago-usa-4k

https://www.pond5.com/pt/stock-footage/item/87863795-aerial-view-golden-gate-bridge-san-francisco-california-usa

https://www.pond5.com/pt/stock-footage/item/119423359-united-states-capital-building-view-water-washington-dc

https://www.pond5.com/pt/stock-footage/item/71357266-panning-shot-dc-capitol-building-trees-blue-skies-4k

https://www.pond5.com/pt/stock-footage/item/76919411-washington-monument-tower-landmark-flags-dc-america-4k-stock

**Comment by Patricia-Torres** [comment]
**[Mockup](https://drive.google.com/open?id=1ni9m3lB4enwYPWgVt-2Qn96_ajy_2g-a)**

**Comment by Patricia-Torres** [comment]
https://drive.google.com/open?id=1zDdzlnweRDrH3M1ry5bGYVGKg8HP6eV4

**Comment by pedrojovelli** [comment]
Great work !
