### ISSUE TITLE
Brian Kolfage - Banner video + Mockup

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#245]

**Comment by Patricia-Torres** [comment]
**[Version 01](https://drive.google.com/open?id=1Ib44wJGNGcTW8V7MgWoKMBYTh6vY1n-l)**

**Comment by thipele** [comment]
Preciso que você faça com a informação final e um render com qualidade para apresentar pro cliente. Eu vou jogar um link com os arquivos finais.

**Comment by thipele** [comment]
https://drive.google.com/open?id=1gY5dOT8QTqgv9G-SV-5oO71b1Vc68t_V

**Comment by Patricia-Torres** [comment]
[Brian Face Banner](https://drive.google.com/open?id=1ml9O1Tsipp9miokjYQbQ_b-qUeytQiRY)

[Full Screen Banner](https://drive.google.com/open?id=1RVuD88c_YGVcZhVIRxt1oOMbFFvSsJ7c)
