### ISSUE TITLE
TPUSA: Chapter Video tutorial

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#25]
Arquivos e explicação aqui:

https://drive.google.com/drive/folders/1ddFLd7VDuJbIvYYWI09jfm6d-4E63-c2?usp=sharing

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/file/d/1eltk-FDfX7azI9dcZZqHps9YF1F20VTK/view?usp=sharing

**Comment by pedrojovelli** [comment]
Pat. Por favor...

separe os vídeos e insira intro e outro para cada um deles.

Aqui estão os tempos de corte + nomes de cada vídeo:

**NOME:**
1. TPUSA creates a new Chapter
2. A student edits information of their Chapter profile
3. TPUSA reviews and releases the information edited by the student
4. A student adds a new event to their Chapter
5. TPUSA reviews and releases the new event added by the student

**TEMPOS:**
VÍDEO 1 - 0:00 — 3:45

VÍDEO 2 - 3:45 — 6:48

VÍDEO 3 - 6:48 — 7:55

VÍDEO 4 - 7:55 — 9:44

VÍDEO 5 - 9:44 — 9:44

**Comment by Patricia-Torres** [comment]
Estou jogando os vídeos aqui:
https://drive.google.com/drive/folders/1vL6cD87pXZwB21ZiXJk6_CzrY9EIp3sL?usp=sharing

**Comment by pedrojovelli** [comment]
Video 1:

00:58 --- ajustar quando eu falo ... "a, an e-mail as a test".. ajustar pra ficar "**an e-mail**" tirar esse A.


01:26 --- desfocar a senha que aparece


Inserir uma pausa de 1 segundo após 00:10 e inserir este audio aqui:
https://drive.google.com/file/d/11_FDQTG0_cO4Xe2dFzsXRdwU5rK0uo-i/view?usp=sharing

**Comment by pedrojovelli** [comment]
Video 2:

02:42 até 03:22 (( cortar essa parte ... é uma daquelas partes que eu faço FLUSH-CACHE ))

04:02 -- mantém a tela parada no mapa e insere somente o audio desse arquivo aqui para encerrar o vídeo:
https://drive.google.com/file/d/1vWd-jMYSZV91jCC5W27Z5feQMOyhb8rI/view?usp=sharing

**Comment by pedrojovelli** [comment]
Video 3:
O título no início aparece muito rápido e meio que nõa dá tempo de ler ... se você puder estender por mais 1 segundo ...

No final do vídeo 3.. mantendo aquela últma tela do mapa... inserir somente o audio deste vídeo aqui: https://drive.google.com/file/d/1D8BpDp_xazMeggI790ZRKBEwwIWcXm0w/view?usp=sharing

**Comment by pedrojovelli** [comment]
Video 4:

00:04 -- 00:07 - manter o mapa de fundo nessa parte... tirar esse audio atual e inserir o audio desse arquivo aqui:

**Comment by Patricia-Torres** [comment]
> Video 2:
> 
> 02:42 até 03:22 (( cortar essa parte ... é uma daquelas partes que eu faço FLUSH-CACHE ))
> 
> 04:02 -- mantém a tela parada no mapa e insere somente o audio desse arquivo aqui para encerrar o vídeo:
> https://drive.google.com/file/d/1vWd-jMYSZV91jCC5W27Z5feQMOyhb8rI/view?usp=sharing

Você está vendo o video certo? O vídeo 02 não tem mais que 3 minutos e nessa parte   02:42 até 03:22  nao tem FLUSH-CACHE.

**Comment by pedrojovelli** [comment]
VIDEO 2

ignore o primeiro pedido e considere somente o segundo pedido da adição do audio. No caso é pra inserir o audio logo após eu dizer "once again" lá no final, bem antes de acabar.

**Comment by pedrojovelli** [comment]
VIDEO 05:

00:33 (parar o vídeo nessa cena ... .logo após eu dizer  "**and now it's published**"

**Comment by Patricia-Torres** [comment]
**DONE** (Falta o video 5)
do 1 ao 4
https://drive.google.com/drive/folders/1vL6cD87pXZwB21ZiXJk6_CzrY9EIp3sL?usp=sharing

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1vL6cD87pXZwB21ZiXJk6_CzrY9EIp3sL?usp=sharing
