### ISSUE TITLE
CANDACE: Pitch Presentation

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#26]

**Comment by Patricia-Torres** [comment]
Slide 03 - Culture

Criar uma animação em looping das letras trocando

**Comment by Patricia-Torres** [comment]
Coloquei a apresentação adaptada para o formato 16:9 [AQUI](https://drive.google.com/drive/folders/1ocf-HLu67KdHZh3Ru6cU10Dppds9_4Og?usp=sharing)

Também coloquei uma pasta destro desta para eu ir jogando os vídeos dos slides.

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1ocf-HLu67KdHZh3Ru6cU10Dppds9_4Og?usp=sharing

**Comment by Patricia-Torres** [comment]
Slides feitos:
01 - 02 - 03 - 06 - 07 - 08 - 09 - 10 - 11 - 12 - 14 - 15 - 16 - 17

[Video Slides](https://drive.google.com/drive/folders/1pq9aRugBwp6MqWLtwJ-SyThpPT2rjFwA?usp=sharing)

**Comment by Patricia-Torres** [comment]
Slide 21 [**DONE**](https://drive.google.com/drive/folders/1pq9aRugBwp6MqWLtwJ-SyThpPT2rjFwA?usp=sharing)

**Comment by Patricia-Torres** [comment]
Slides feitos:
01 - 02 - 03 - 06 - 07 - 08 - 09 - 10 - 11 - 12 - 14 - 15 - 16 - 17-19-20-21

**Comment by pedrojovelli** [comment]
👍
