### ISSUE TITLE
CANDACE OWENS: 20pointsby

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#29]
Pat. 

Para substituirmos o slide do 20% by 2020.

Devemos fazer 20 POINTS BY 2020.

Sendo assim.. gostaria de pedir pra você fazer com base neste arquivo aqui (com o vídeo rolando de fundo ... ):
https://drive.google.com/file/d/1374PkyYPnclTOjBaaEuWbNqZq6jkQTam/view?usp=sharing

Gostaria de pedir pra você começar o vídeo dessa forma (sem o texto):
![Screen Shot 2019-11-13 at 14 56 58](https://user-images.githubusercontent.com/15367213/68790320-d6788280-0625-11ea-9768-936e487347b3.png)

Em seguida vai aparecendo em FADE-IN... cada parte do texto:

- 20
- POINTS
- BY
- 2020

**Comment by Patricia-Torres** [comment]
[**Done**](https://drive.google.com/file/d/1N5Z6MaSTpph2jprCxc7MAm3sapGyNyfU/view?usp=sharing)
