### ISSUE TITLE
TPUSA: TShirt Designs

### ISSUE THREAD

**Issue by rioslumstudio** [rioslumstudio/Design#3]
**DON’T TOUCH MY GUNS**
- Criar uma versão com fonte BOLD/BLACK somente escrito “DON’T TOUCH MY GUNS”

_________________________________

**SOCIALISM SUCKS Feedback**
- Criar mais uma versão inserindo a assinatura da TPUSA somente ao centro abaixo do logo

**Comment by felliperinschede** [comment]
Done

**Comment by pedrojovelli** [comment]
Fellipe.

Por favor. Se puder criar um esquema de apresentação para as camisetas, seguindo um pouco da estrutura que fez para as bandeiras....  no caso das camisetas, acho que vale apresentar a arte + o mockup.

![Screen Shot 2019-11-01 at 10 06 02](https://user-images.githubusercontent.com/15367213/68026705-37e83b00-fc8f-11e9-9ff7-3b2193e3f5ee.png)

Outra coisa.. a Patricia elaborou algumas opções para a arte do "DON'T TOUCH MY GUNS".

As imagens estão aqui:
https://drive.google.com/drive/folders/1vIud-TWlg3ofWdfhBylSS2mSdMDfgqqJ?usp=sharing
mas caso precise, vale pedir pra ela.

**Comment by felliperinschede** [comment]
Done ;D

**Comment by pedrojovelli** [comment]
Fellipe !

great work on the presentation!

I do have just one request for the SOCIALISM SUCKS mockups.

Jesse has asked us to lower a bit the artwork on the mockups... he said it looks too high.

![Screen Shot 2019-11-01 at 13 05 33](https://user-images.githubusercontent.com/15367213/68038258-4abb3980-fca8-11e9-86b4-90c7594ad626.png)

**Comment by felliperinschede** [comment]
Done

**Comment by pedrojovelli** [comment]
Por favor, elaborar umas versões de costas para a roupa SOCIALISM SUCKS.

Segue assinatura em vetor como referência:

[logo_signature.ai.zip](https://github.com/rioslumstudio/Design/files/3804337/logo_signature.ai.zip)

**Comment by felliperinschede** [comment]
Done :D

![TPUSA_Shirt_Socialism_Mockup1](https://user-images.githubusercontent.com/57017535/68127485-631b9600-feec-11e9-85e8-eec1ecfa3de7.jpg)
![TPUSA_Shirt_Socialism_Mockup2](https://user-images.githubusercontent.com/57017535/68127486-631b9600-feec-11e9-811f-b907bbd70aba.jpg)
![TPUSA_Shirt_Socialism_Mockup3](https://user-images.githubusercontent.com/57017535/68127487-631b9600-feec-11e9-8e30-787796b804eb.jpg)

**Comment by rioslumstudio** [comment]
[TPUSA.Tshirt.Design_JGG_Edits.pptx.zip](https://github.com/rioslumstudio/Design/files/3809628/TPUSA.Tshirt.Design_JGG_Edits.pptx.zip)

Segue pedidos do Jesse referente as peças.

Por favor, se puder também adicionar uma versão de verso com assinatura do logo da turning point em branco para cada uma das opções do SOCIALISM SUCKS

**Comment by pedrojovelli** [comment]
Cliente não respondeu mais. Fechando a issue por falta de retorno.
