### ISSUE TITLE
Colagem sobre tema AMERICAN CULTURE

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#30]
Formato da imagem 1920 x 1080px

Gostariamos de fazer uma colagem num esquema parecido com este:

![Screen Shot 2019-11-13 at 15 43 32](https://user-images.githubusercontent.com/15367213/68793863-923cb080-062c-11ea-8f97-aa65d239ee45.png)

Algumas imagens que já cortamos:
https://drive.google.com/drive/folders/1NoI8DK7DRgTclnW_IMHJeG9PgZ3lwBTe?usp=sharing

Se vocÊ puder pegar imagens (não precisa cortar) do tipo:

- Fresh Prince of Bel Air (Will Smith)
- Family Matters
- PopArt (talvez alguma peça do ANDY WARHOL)
- Michael Jordan (talvez recortar alguma imagem)

**Comment by felliperinschede** [comment]
Feito :D
