### ISSUE TITLE
TPUSA: Productions videos

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#33]
Criar um vídeo de 15 segundos (tam 400x400) para cada um desses abaixo:

- POPLITICS
- ONLY IN AMERICA
- FREEDOM FIGHTS
- 180

Página da TPUSA para procurar pelas footages:
https://www.youtube.com/user/theturningpointusa/videos

**Comment by Patricia-Torres** [comment]
**[Done](https://drive.google.com/drive/folders/1xRv-VNEFn1N66MU-HBAaBoBh5K79RkDG?usp=sharing)**

**Comment by pedrojovelli** [comment]
Rogerio. Por favor, veja se estes vídeos sÃo úteis pra ti:

https://drive.google.com/open?id=1xRv-VNEFn1N66MU-HBAaBoBh5K79RkDG

**Comment by robanquieri** [comment]
Obrigado pessoal, faltou só o de introdução, da página "productions".

<img width="872" alt="Screen Shot 2019-11-19 at 10 14 36" src="https://user-images.githubusercontent.com/4391611/69149569-88e09780-0ab5-11ea-8d3c-2544fc7b095b.png">

**Comment by pedrojovelli** [comment]
Iremos providenciar.

**Comment by pedrojovelli** [comment]
Pat. Por favor, pode adicionar em sua agenda para quinta-feira?

**Comment by robanquieri** [comment]
Caros podem regerar os vídeos no formato 280x300?

**Comment by Patricia-Torres** [comment]
> Caros podem regerar os vídeos no formato 280x300?

Estão aqui: **[link](https://drive.google.com/drive/folders/1tt7q5GotIOn2pZy7ugp6ueQjvKOkFAr5?usp=sharing)**

**Comment by pedrojovelli** [comment]
100% !

Iremos focar nisso logo após arrematarmos os vídeos da CANDACE.

**Comment by Patricia-Torres** [comment]
**[Banner da home](https://drive.google.com/file/d/1US7vmLmzRVT84h-yLEL-pLpORG3_T7cl/view?usp=sharing)**
