### ISSUE TITLE
CANDACE OWENS: Criar bandeira do blexit escrito WE THE FREE

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#34]
Aquela bandeira que aparece no telão atrás dos palestrantes, com o nome deles.

Nesse caso, escrever WE THE FREE e renderizar a bandeira em LOOP ou com uns 30 ..40 segundos....

**Comment by Patricia-Torres** [comment]
[**Done**](https://drive.google.com/file/d/1xP6nDun5rYcFAhRVo8Zwwt6bkZSwd2uu/view?usp=sharing)
