### ISSUE TITLE
CANDACE PPT: Ye Man

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#35]
Eu gostaria de fazer com esse YE man, o mesmo que fizemos com aquela cena do rosto da Candace aparecendo e indo para o lato ....

![Screen Shot 2019-11-13 at 19 43 27](https://user-images.githubusercontent.com/15367213/68810822-ead07580-064d-11ea-930a-f857b440a3cb.png)

Por favor.. faça ele aparecendo em FADE-IN no centro da tela (YE MAN com o TM no pézinho)

e aí ele vai para a esquerda... pois colocaremos bullets igual fizemos com a candace ...

Se você puder gerar uma IMAGEM do último frame da animação para eu replicar nos slides seguintes ...

**Comment by Patricia-Torres** [comment]
**[video](https://drive.google.com/file/d/1IJjfd5e7xuck_3ZNgmHBIz4-j7fLAdJl/view?usp=sharing)**
**[imagem](https://drive.google.com/file/d/1hNFZvfObzq1lUTxd3D-F2s3uClLTlqE6/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[imagem](https://drive.google.com/file/d/16nVPblse7HIJENk4f55Y6034wrQbe4qz/view?usp=sharing)**
**[video](https://drive.google.com/file/d/1TacwOTmY9s_TilKrmSWv3wSxIgQ5zqI4/view?usp=sharing)**
