### ISSUE TITLE
CANDACE PPT: Mais um video da Beyonce

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#36]
Mesmo vídeo em loop que fizemos da BEYONCE, porém, com o logo do BLEXIT ao centro e NEW ORLEANS em baixo.

Segue aqui o vetor:
[blexit_neworleans.ai.zip](https://github.com/rioslumstudio/Design/files/3843797/blexit_neworleans.ai.zip)

Sugestão (talvez escurecer um pouquinho o vídeo, só pra dar mais destaque para o escrito em branco:

![Screen Shot 2019-11-13 at 19 52 19](https://user-images.githubusercontent.com/15367213/68811315-20c22980-064f-11ea-9f58-0ea96613ba3c.png)

**Comment by Patricia-Torres** [comment]
**[AQUI](https://drive.google.com/file/d/1cpOyrsYLCAmhftc_mnZHP1D16qF6xjRu/view?usp=sharing)**
