### ISSUE TITLE
CANDACE PPT: Cenas de speakers do Blexit

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#37]
Pat. Por favor.

Se puder puxar um vídeo com cenas de speakers que temos .. (possivelmente cenas com camera mexendo e tal ...)

Não incluir cenas da Candace !

A idéia é um video em loop com uns 4, 5 speakers .... preferencia cenas de perto e com câmera em movimento.

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1BsihFtN-IIRz3MoJvpdFgTw76AsWiIqH/view?usp=sharing)**
