### ISSUE TITLE
CANDACE PPT: Stage Design Slide

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#38]
https://www.youtube.com/watch?v=Mq7FsJhlGjM

https://www.youtube.com/watch?v=e6qPnbQzfYI

https://www.youtube.com/watch?v=1eHCq3y1ZjA&list=PLR2A7tbdqZdTCuS7Ox6MTY4qumppo9ojk

https://www.youtube.com/watch?v=ArDLyxIRJGk

**Comment by Patricia-Torres** [comment]
Me dá mais informações sobre esse slide please

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1apcVEGjD2DhY86j3SqJFE9RMEySwaFBm/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
[stage-design.psd.zip](https://github.com/rioslumstudio/Design/files/3846568/stage-design.psd.zip)

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1o2g7Y1n3FyQ_v6IPWC0VJspIHPuon5TI/view?usp=sharing)**
