### ISSUE TITLE
CANDACE PPT: 20 points by 2020

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#39]
Esse vídeo aqui ... Por favor. Se puder fazer um fade-out no final ... pra ficar bacananinha no esquema de loop..

![Screen Shot 2019-11-14 at 09 34 52](https://user-images.githubusercontent.com/15367213/68857631-fa89a180-06c1-11ea-9243-c3dbbf2b257a.png)

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1njWhET_thgRme7Lced3HTR2AHfTrlxwi/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
Pat. Eu não havia percebido antes .... mas esse vídeo começa com uma piscada de uma cena com mãos segurando celular. .. se você puder eliminar esse pedacinho de cena no início ...

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1q6o7T5GaaQOgrcd1zqEuA5FOV5C4rPUA/view?usp=sharing)**
