### ISSUE TITLE
Candace - End of Year Film - Trocar as cenas dramáticas

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#4]
Pedro, você pode verificar se esses vídeos que eu escolhi no Youtube são bons para colocarmos no vídeo?

**Comment by Patricia-Torres** [comment]
![cena 01](https://user-images.githubusercontent.com/43677737/67891399-46b8db80-fb31-11e9-8c91-7a609f0b5603.JPG)

Trocar essa imagem da esquerda inferior por esse video (3:35)
https://www.youtube.com/watch?v=BSAoitd1BTQ

**Comment by Patricia-Torres** [comment]
![cena 02](https://user-images.githubusercontent.com/43677737/67891759-0443ce80-fb32-11e9-90a7-eba09fbb4bad.JPG)
Trocar a cena do meio inferior por esse vídeo (0:26)
https://www.youtube.com/watch?v=qW7ObGMEo8I

**Comment by Patricia-Torres** [comment]
![cena 03](https://user-images.githubusercontent.com/43677737/67891897-4bca5a80-fb32-11e9-8c28-372506bbbbd6.JPG)

Trocar essa cena marcada por esse vídeo (14:15)
https://www.youtube.com/watch?v=oJOuO9IxTdE

**Comment by Patricia-Torres** [comment]
@pedrojovelli estou esperando o seu ok para trocar essas cenas que eu escolhi. Vc está de acordo? Peguei 3 vídeos da Candace do Youtube.

**Comment by pedrojovelli** [comment]
https://www.youtube.com/watch?v=BSAoitd1BTQ
3:42

____________________________________________________

Perfeito! Quando ela diz: "i'm talking about me here " 
Trocar a cena do meio inferior por esse vídeo (0:26)
https://www.youtube.com/watch?v=qW7ObGMEo8I

______________________________________________________

Bacana esse também !!
Trocar essa cena marcada por esse vídeo (14:15)
https://www.youtube.com/watch?v=oJOuO9IxTdE

**Comment by Patricia-Torres** [comment]
**DONE**
