### ISSUE TITLE
CANDACE PPT: Vídeo Speakers

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#40]
Inserir Speakers ao centro do vídeo.

![speakers](https://user-images.githubusercontent.com/15367213/68857988-d4183600-06c2-11ea-81be-550d179e1357.png)

![Screen Shot 2019-11-14 at 09 40 52](https://user-images.githubusercontent.com/15367213/68857998-d8445380-06c2-11ea-8fda-c3300867bce3.png)

**Comment by Patricia-Torres** [comment]
O Speakers veio bem pequeno
![image](https://user-images.githubusercontent.com/43677737/68858498-f2cafc80-06c3-11ea-8bf4-77ed62159636.png)

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/file/d/1fku2ya9NZs-2P-7X-jYVNw2PYokdriui/view?usp=sharing)**
