### ISSUE TITLE
CANDACE PPT: Social Media Slide

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#41]
![Screen Shot 2019-11-14 at 11 45 37](https://user-images.githubusercontent.com/15367213/68867250-47767380-06d4-11ea-8b6b-8638c279aece.png)

O Jesse gostaria de fazer algo usando tiras ... seguindo um pouco a linha desse poster do NYNPHOMANIAC:
![Screen Shot 2019-11-14 at 11 46 43](https://user-images.githubusercontent.com/15367213/68867318-5f4df780-06d4-11ea-98ea-f7aa6b735d85.png)

Bom...creio que isso não vai funcionar, concorda comigo? hehe...

Temos de aplicar tipo... uns mockups de mídias sociais da Candace ... 

- INSTAGRAM
- TWITTER
- FACEBOOK

e o título em cima... ou na frente, que é: **TARGET MARKETING**

Penso em de repente algo assim...

![Screen Shot 2019-11-14 at 11 50 31](https://user-images.githubusercontent.com/15367213/68867628-ed29e280-06d4-11ea-859f-39893bb5a3ba.png)

Sobre o esquema do título... estamos usando um esquema assim em cores vibrantes:

![Screen Shot 2019-11-14 at 11 51 18](https://user-images.githubusercontent.com/15367213/68867701-0f236500-06d5-11ea-810e-f4cb29d2f998.png)
![Screen Shot 2019-11-14 at 11 51 27](https://user-images.githubusercontent.com/15367213/68867704-0f236500-06d5-11ea-8b93-9ffdb0db6774.png)
![Screen Shot 2019-11-14 at 11 51 31](https://user-images.githubusercontent.com/15367213/68867706-0fbbfb80-06d5-11ea-9769-3fcc37289eba.png)
![Screen Shot 2019-11-14 at 11 51 37](https://user-images.githubusercontent.com/15367213/68867707-0fbbfb80-06d5-11ea-8f9c-454a8518435d.png)

A fonte é essa aqui:
![Screen Shot 2019-11-14 at 11 52 17](https://user-images.githubusercontent.com/15367213/68867787-295d4300-06d5-11ea-88d2-5043824f9041.png)

BOLD ITALIC

**Comment by felliperinschede** [comment]
Done ;D
