### ISSUE TITLE
CANDACE PPT: Patronizing the Arts

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#42]
Pedido do Jesse:

Fazer um arranjo com 3 tiras... talvez uma cor predominante pra cada tira ....

- tira 1: imagem relacionada a música... talvez algo mais voltado a instrumentos clássicos ...violino ...cello... arpa... saxofone ... algo assim .... ( penso que se inserirmos um instrumento como uma guitarra vai remeter mais as categorias rock'n roll ou pop do que música em si)

- tira 2: painting (talvez alguma foto mais macro de pincel em ação na tela... paleta de cores + pincel.

- tira 3: Movies (talvez uma câmera, algo que remeta a gravação de um filme ... )

Ao centro e na frente dessas 3 tiras o seguinte escrito: 

PATRONIZING THE ARTS

**Segue um rascunhozão:**
![Screen Shot 2019-11-14 at 13 01 35](https://user-images.githubusercontent.com/15367213/68873746-d7b9b600-06de-11ea-8d72-85dde918cd31.png)

![Screen Shot 2019-11-14 at 12 54 14](https://user-images.githubusercontent.com/15367213/68873182-04210280-06de-11ea-80a7-cc16632907b8.png)

**Comment by felliperinschede** [comment]
Done
