### ISSUE TITLE
CANDACE PPT: Slide 'Media Projects'

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#43]
Tentar criar um esquema de fitas, mais ou menos naquela pegada do que você fez para **PATRONIZING THE ARTS**

https://drive.google.com/file/d/1knLAY8_KTa5-ZDFcxyakdTkubbq79nIW/view?usp=sharing

https://drive.google.com/file/d/1Bay-_PRgaoDurerHhuZsDO9u10h6W4GO/view?usp=sharing

https://drive.google.com/file/d/1NyKJArj7C2dKN4GF-b4aAa8mvdYLVXZa/view?usp=sharing

https://drive.google.com/file/d/1eKoh5z-Fg5YiN0oPjVMzW42GcbNxaNBN/view?usp=sharing

**Comment by felliperinschede** [comment]
Done
