### ISSUE TITLE
FASHION CONNECTION: Pesquisar plataformas para criar websites

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#45]
Gostariam de recomendação nossa sobre plataformas para criar sites.

WIX seria uma delas.

Por favor, pode dar uma pesquisada em outras 2 plataformas para apresentarmos 3?

**Comment by felliperinschede** [comment]
Bro, algumas opções que encontrei/conheço:
https://www.squarespace.com/
www.cargocollective.com
www.wix.com
https://www.weebly.com/

**Comment by pedrojovelli** [comment]
Já comunicamos o cliente :)
