### ISSUE TITLE
CANDACE OWENS: End of Year film

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#46]
Por favor, baixe o vídeo e daremos sequência em breve:

https://drive.google.com/drive/folders/19ssuvtIRAPvaAy8lbx7ffbESpGKM6kb8?usp=sharing

**Comment by Patricia-Torres** [comment]
**Done**

**Comment by Patricia-Torres** [comment]
**[Here](https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[Video completo com intro e miolo](https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv?usp=sharing)**

**Comment by Patricia-Torres** [comment]
Colocar a parte cantada da música depois do discurso.
**[AQUI](https://drive.google.com/file/d/11zS5B0VYcE4StPuEuyAtehQ6And4Dfnc/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
Colocar a voz depois do Thank you guys.
**[AQUI](https://drive.google.com/file/d/11Bs7RiFMJaBQCZMqt0OrR7M7RzqwCnL6/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
- 1:03 — deletar parte que ela diz “OF COURSE” e fazer com que comece quando ela diz: THERE IS

- 1:59 — 2:01 (Deletar ) — deve ficar: DEFFEND TRUMP in front of a very unlikely audience

- 2:03 — Tirar este “AND OF COURSE“ e deixar a parte que ela diz: YOU PROBABLY’VE SEEM ME PROMOTING MY

**Comment by pedrojovelli** [comment]
Congress

https://www.youtube.com/watch?v=PX89pxjQeQU

2:14 — 2:27







Candace Owens Show:

01:06 — 01:09

https://www.youtube.com/watch?v=bvwwCxQOVXk&t=29s



02:13 — 02:15

https://www.youtube.com/watch?v=-T_ZsTh4ueQ




00:58 — 01:01

11:07 — 11:09

https://www.youtube.com/watch?v=PC082KBq5Rs



_______________________

**Comment by Patricia-Torres** [comment]
O video completo -> **[Here](https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv?usp=sharing)**
V2

**Comment by Patricia-Torres** [comment]
Vídeo completo ->**[Here](https://drive.google.com/drive/folders/1Z1KLu2KSrQlF851UO-KqtqtTVt1V6KLv?usp=sharing)**
V3

**Comment by Patricia-Torres** [comment]
- 2:38 (som de fundo fica mudo de repente) final da música com um glitchzinho após som abaixar... talvez não deixar som tãaao baixo ... talvez dar uma subidinha de leve no volume   ((  talvez deixar no volume que está nos 00:27 ))

- todas as cenas da candace de lado, deixar em preto e branco e talvez aumentar um pouquinho contraste ... (talvez, rs ..precisamos testar o lance do contraste )

- Aplicar algumas tipografias quando ela diz números ...  (vou repassar e ver onde rola isso )

- 00:40 -- quando mostra a candace no CANDACE OWENS SHOW.. .mostrar mais entrevistados do que ela

- Próximo dos 00:47 ... 00:55 (quando ela diz: aswell as 49 blah blah blah ...) ... irá tomar a tela inteira mostrando arranjos tipográficos..

- from 00:49 to 00:55 ( é possível agilizar a voz da candace nessa parte ? )


- TALVEZ inserir tipografia sobre o vídeo apresentando alguns projetos / eventos que aconteceram conforme ela fala

**Comment by Patricia-Torres** [comment]
**DONE:**
todas as cenas da candace de lado, deixar em preto e branco e talvez aumentar um pouquinho contraste ... (talvez, rs ..precisamos testar o lance do contraste )

**Comment by Patricia-Torres** [comment]
**DONE**
2:38 (som de fundo fica mudo de repente) final da música com um glitchzinho após som abaixar... talvez não deixar som tãaao baixo ... talvez dar uma subidinha de leve no volume (( talvez deixar no volume que está nos 00:27 ))

**Comment by Patricia-Torres** [comment]
**DONE**
00:40 -- quando mostra a candace no CANDACE OWENS SHOW.. .mostrar mais entrevistados do que ela

**Comment by Patricia-Torres** [comment]
> from 00:49 to 00:55 ( é possível agilizar a voz da candace nessa parte ? )

só fazendo cortes. Pode?

**Comment by pedrojovelli** [comment]
///- 2:38 (som de fundo fica mudo de repente) final da música com um glitchzinho após som abaixar... talvez não deixar som tãaao baixo ... talvez dar uma subidinha de leve no volume   ((  talvez deixar no volume que está nos 00:27 ))

///- todas as cenas da candace de lado, deixar em preto e branco e talvez aumentar um pouquinho contraste ... (talvez, rs ..precisamos testar o lance do contraste )

///- Aplicar algumas tipografias quando ela diz números ...  (vou repassar e ver onde rola isso 

///- 00:40 -- quando mostra a candace no CANDACE OWENS SHOW.. .mostrar mais entrevistados do que ela

**- Próximo dos 00:47 ... 00:55 (quando ela diz: aswell as 49 blah blah blah ...) ... irá tomar a tela inteira mostrando arranjos tipográficos..**

- (((( não é possível )))) from 00:49 to 00:55 ( é possível agilizar a voz da candace nessa parte ? )


**- TALVEZ inserir tipografia sobre o vídeo apresentando alguns projetos / eventos que aconteceram conforme ela fala**


///- 01:13 -01:15, young black leaders from accross the States to meet the president of the United States - tentar tirar a parte que ela diz "from accross the states" - Aí vai ficar "young black leaders to meet the president of the United States"

/// Inserir vídeo CPAC Paris  ((enviei video via whatsapp )) - Aplicar o vídeo quando ela diz Paris em 01:20

**- 1:39 (ARRANJO DIZENDO I WON THAT DEBATE )**

///-1:45 (mostrar outros 2 speakers desse evento sem ser a candace )

**- Após 1:45 --- Arranjo tipográfico dizendo: FAIRY AFTERNOON** 

- 2:09 - Talvez mudar parte do livro.. inserir só mockup do livro

- 2:21 ((( adicionar cenas da candace no congresso )))

- 2:29 Adicionar arranjo tipográfico para SHATTERED ALL RECORDS

- 2:45 -- 2:46 (Começar a mostrar cenas do casamento)


**Último ajuste por hoje:**
- Deletar parte que ela diz "time to hire a book writer"

**Comment by Patricia-Torres** [comment]
[**V4 com esses ajustes feitos acima**](https://drive.google.com/file/d/1lLc0LzwjbIUec6fgGWR_K0CzCPobzCDO/view?usp=sharing)

**Comment by pedrojovelli** [comment]
**MOST RECENT LIST:**

- 00:33 — Pegar o logo do Candace Owens Show (buscar centralizar melhor /// Outro pedido, é para fazer um zoom in devagar… para o logo dar uma crescidinha de leve.


- 00:39 — Nessa parte, o Jesse gostaria de mostrar mais entrevistados. Sendo assim, vamos inserir mais este vídeo aqui: https://www.youtube.com/watch?v=qC-r0izU4j0 (23:40 — 23:42) e este vídeo aqui: https://www.youtube.com/watch?v=wR2lK36Tc4M (21:10 — 21:12)



- 00:54 — eu errei na última parte da tipografia … não é IN … é AND. Segue aqui o vetor: https://drive.google.com/file/d/15AIpDCqJ4Qzlyq9a0AHvlzTcPMw4fG_m/view?usp=sharing


- 01:06 — Black Leadership Summit (sincronizar a aparição das palavras com a fala dela (mandei no seu e-mail o vetor)



- 01:26 — Mantendo o tempo que você já tem (que é o da candace andando … inserir um pouco dela discursando. Vídeo aqui: https://www.youtube.com/watch?v=blV4K2plDQk&t=783s (10:10 — até o final do seu tempo no vídeo )



- 01:32 — 01:36 (quando ela diz … “at the oxford union“) ..inserir esta foto aqui:
https://drive.google.com/file/d/1tBB_VtZpPkdhGS2MB-cwRnt2xI0_2UEx/view?usp=sharing


2:20 — 02:29 - Inserir vídeo lateral da Candace no congresso — https://www.youtube.com/watch?v=0cUQqPxw3hc&t=176s (04:20 — 04:29 — 04:32  // 02:11 — 02:13        —        https://www.youtube.com/watch?v=PX89pxjQeQU (02:38 — 02:40 // 02:26 — 02:28


02:46 — 02:47 - (Acho que essa cena da aliança de diamantes com o preço de 3 apartamentos em Moema é muito pretensiosa…. Se puder substituir essa cena por outra cena do casal, seria melhor … )



Pat. Se vocÊ puder fazer um fade-out mais suave na música no final …. Não sei se faremos aquele final do storyboard or not.

**Comment by Patricia-Torres** [comment]
- [ ] 00:33 — Pegar o logo do Candace Owens Show (buscar centralizar melhor /// Outro pedido, é para fazer um zoom in devagar… para o logo dar uma crescidinha de leve.

- [ ] 00:39 — Nessa parte, o Jesse gostaria de mostrar mais entrevistados. Sendo assim, vamos inserir mais este vídeo aqui: https://www.youtube.com/watch?v=qC-r0izU4j0 (23:40 — 23:42) e este vídeo aqui: https://www.youtube.com/watch?v=wR2lK36Tc4M (21:10 — 21:12)

- [ ] 00:54 — eu errei na última parte da tipografia … não é IN … é AND. Segue aqui o vetor: https://drive.google.com/file/d/15AIpDCqJ4Qzlyq9a0AHvlzTcPMw4fG_m/view?usp=sharing

- [ ] 01:06 — Black Leadership Summit (sincronizar a aparição das palavras com a fala dela (mandei no seu e-mail o vetor)

- [ ] 01:26 — Mantendo o tempo que você já tem (que é o da candace andando … inserir um pouco dela discursando. Vídeo aqui: https://www.youtube.com/watch?v=blV4K2plDQk&t=783s (10:10 — até o final do seu tempo no vídeo )

- [ ] 01:32 — 01:36 (quando ela diz … “at the oxford union“) ..inserir esta foto aqui:

https://drive.google.com/file/d/1tBB_VtZpPkdhGS2MB-cwRnt2xI0_2UEx/view?usp=sharing

- [ ] 2:20 — 02:29 - Inserir vídeo lateral da Candace no congresso — https://www.youtube.com/watch?v=0cUQqPxw3hc&t=176s (04:20 — 04:29 — 04:32 // 02:11 — 02:13 — https://www.youtube.com/watch?v=PX89pxjQeQU (02:38 — 02:40 // 02:26 — 02:28

- [ ] 02:46 — 02:47 - (Acho que essa cena da aliança de diamantes com o preço de 3 apartamentos em Moema é muito pretensiosa…. Se puder substituir essa cena por outra cena do casal, seria melhor … )

- [ ] Pat. Se vocÊ puder fazer um fade-out mais suave na música no final …. Não sei se faremos aquele final do storyboard or not.

**Comment by Patricia-Torres** [comment]
**[Versão 5](https://drive.google.com/file/d/1EUOo4fgd5Iv_X5NTxMIMh1gb11JBtruG/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[Versão 6](https://drive.google.com/file/d/1D-BWqP37G6o7D5tY9Zz81CdenMUcWBY0/view?usp=sharing)**
