### ISSUE TITLE
LAST HOPE USA: Landing Page Mobile

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#47]
Olá Fellipe.

Gostaria de pedir a ti, para adaptar para **mobile** este mockup de site feito para desktop.

Este mockup foi feito com base neste site aqui:
http://theatkcompany.com/dev

Veja como está a navegação deste site no mobile e busque adaptar de forma similar.

Segue telas em PSD:
https://drive.google.com/drive/folders/1CiEj08JobdFE__8v73MDdhHB9jZh7XrQ?usp=sharing

**Comment by pedrojovelli** [comment]
Fellipão.

Mantém os 2 botões centralizados só para manter padrão.

![Screen Shot 2019-11-19 at 13 28 29](https://user-images.githubusercontent.com/15367213/69165655-b129bf80-0ad0-11ea-8cd8-458567873f05.png)
![Screen Shot 2019-11-19 at 13 28 34](https://user-images.githubusercontent.com/15367213/69165656-b129bf80-0ad0-11ea-8e94-1397b229d3c7.png)

**Comment by felliperinschede** [comment]
Done
