### ISSUE TITLE
CHARLIE KIRK: Trocar extensão de arquivo e reduzir video

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#5]
Pat.

Por favor, a pedido do Rogério, se puder comprimir um pouco (reduzir peso de arquivo) este vídeo:
https://drive.google.com/file/d/1mRogT5jdTMhrqHprDSQxFj7fffFSxtzl/view?usp=sharing

O Rogério também pediu para gerar o vídeo nas seguintes extensões:

**mp4, ogv** e **webm**

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1LuuJGx7IDT03b2LGZK8a2Se0-CNn63jE

**Comment by robanquieri** [comment]
@Patricia-Torres Um dos vídeos foi gerado como "ogg" você poderia gerar em "ogv"?

**Comment by Patricia-Torres** [comment]
@robanquieri subi lá  ;)

**Comment by robanquieri** [comment]
Muito obrigado @Patricia-Torres :)
