### ISSUE TITLE
LAST HOPE USA: Landing Page Desktop

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#50]
Usando as páginas atuais do PSD para desktop que você já passui.

Peço pra ti, para elaborar uma versão mais conservadora. Mais simples, usando como referência as cores da bandeira dos EUA.

Retirar a imagem lateral do Abraham Lincoln e talvez trabalhar com marca d'agua... pode ser do Abraham Lincoln, mas outra imagem.

Outro caminho para deixar o layout mais simples é retirar os itálicos do texto e linhas que ajudam a compor o layout.

**Comment by pedrojovelli** [comment]
![01](https://user-images.githubusercontent.com/15367213/69251008-79358180-0b8f-11ea-9a7e-dc70b816817e.jpg)
![02](https://user-images.githubusercontent.com/15367213/69251011-79ce1800-0b8f-11ea-8e5e-e1b328b3dbcd.jpg)
![03](https://user-images.githubusercontent.com/15367213/69251012-79ce1800-0b8f-11ea-963e-dde828787dd3.jpg)

**Comment by felliperinschede** [comment]
Done
