### ISSUE TITLE
G&G CONSULTORÍAS ESPECIALIZADAS: Diagramar Proposta

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#55]
Segue dados:
https://docs.google.com/document/d/1OvWPNlVsnnhTkhke0j36v39OdahLSSIaKG6US7eb9EQ/edit?usp=sharing

Segue package com referência:
https://drive.google.com/file/d/1yIV3y-mlm5gG9G82zm8fnTUMKhuN_3na/view?usp=sharing

**Comment by Patricia-Torres** [comment]
[G&G Proposal.pdf](https://github.com/rioslumstudio/Design/files/3887241/G.G.Proposal.pdf)

**Comment by Patricia-Torres** [comment]
Versão com pedidos de edição da Lucia:
[G&G Proposal.pdf](https://github.com/rioslumstudio/Design/files/3887875/G.G.Proposal.pdf)

**Comment by pedrojovelli** [comment]
Perfect ! 

Thanks !! 


We'll continue this document later

**Comment by pedrojovelli** [comment]
Adicionar valores

**Comment by Patricia-Torres** [comment]
[G&G Proposal.pdf](https://github.com/rioslumstudio/Design/files/3891851/G.G.Proposal.pdf)

**Comment by Patricia-Torres** [comment]
[G&G Proposal.pdf](https://github.com/rioslumstudio/Design/files/3892854/G.G.Proposal.pdf)
A última versão
