### ISSUE TITLE
TPUSA: Checar se este arquivo editável é exatamente o mesmo que o arquivo do link

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#58]
Arquivos estão aqui. Por favor, baixe o arquivo do InDesign:
https://drive.google.com/drive/folders/1c95EclgqW-_02zyQFa5BUeavZiqgC-mK?usp=sharing

_________________

Brand Package em PDF mais recente que enviamos para o cliente:
https://drive.google.com/file/d/1cnUWePqotxFUpraHZOiZ7qOKFhHZo4UB/view?usp=sharing

**Comment by felliperinschede** [comment]
Done :D
