### ISSUE TITLE
BLEXIT - Announcement Posts (stories and instagram posts)

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#59]
**Follow the design of these:**

![Screen Shot 2019-11-25 at 15 42 50](https://user-images.githubusercontent.com/15367213/69568345-319d6400-0f9a-11ea-86f7-7be0a6ae6e5f.png)

![Screen Shot 2019-11-25 at 15 42 55](https://user-images.githubusercontent.com/15367213/69568346-3235fa80-0f9a-11ea-8153-93bd0a6367e4.png)

____________________________________

BLEXIT charlotte will be on January 19th 2020. Will need speaker promo posters for me, Brandon Tatum, Will Witt, Larry Elder, KingFace, & Terrence Williams.

- Brandon Tatum
- Will Witt
- Larry Elder
- KingFace
- Terrence WIlliams

**Comment by Patricia-Torres** [comment]
Alguém tem esses editável? Ou temos que refazer?

**Comment by pedrojovelli** [comment]
Vou subir pra ti

**Comment by pedrojovelli** [comment]
Por favor, pegue aqui:
https://drive.google.com/drive/folders/1_Ff_jRpO9_BYEyp_N9UiKj27_bMKZhas?usp=sharing

**Comment by Patricia-Torres** [comment]
Temos foto do KingFace?

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1elnuxWa4HPaLWyy-fdWd8TC3IYsWqDgP?usp=sharing)**

**Comment by pedrojovelli** [comment]
![Screen Shot 2019-11-25 at 18 19 19](https://user-images.githubusercontent.com/15367213/69578838-0756a100-0fb0-11ea-8aac-8ba1c65960d9.png)

Fazero nome **Larry Elder** em 2 linhas, mantendo o mesmo tamanho de fonte dos demais nomes. 

Aplicar para POST e para STORIES.

**Comment by pedrojovelli** [comment]
Aumentar um pouco mais o rosto do KINGFACE para seguir o padrão de tamanho das demais imagens...

![Screen Shot 2019-11-25 at 18 20 57](https://user-images.githubusercontent.com/15367213/69578934-44229800-0fb0-11ea-9df3-1642397c0949.png)

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1BCUP44DPM2hQBGD-Tk0O5yCL5vJPHS2r?usp=sharing)**

**Comment by pedrojovelli** [comment]
Excellent !
