### ISSUE TITLE
CANDACE OWENS: Countdown Video

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#6]
Pat. Dando sequência por aqui.

Segue um video com pedido de ajustes na questão dos filtros de cores.

https://drive.google.com/file/d/10zyj7HLlUw66d2Xz2lsePAeO7uXfAXwt/view?usp=sharing

______________

Creio que o Jesse tenha enviado pra ti também o vídeo comprado do countdown.

**Comment by Patricia-Torres** [comment]
Tem algumas cenas que não tem jeito mesmo...estão piores sem o filtro:
Antes
![1](https://user-images.githubusercontent.com/43677737/68129359-2d7caa00-fef8-11e9-8351-10d40adf2a5d.png)
Depois
![2](https://user-images.githubusercontent.com/43677737/68129382-38cfd580-fef8-11e9-929e-03b7d337186a.png)

**Comment by pedrojovelli** [comment]
De fato..

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/drive/folders/1kj1FNJU9QSaiShQ77Iuc87679-vcX-P1

**Comment by pedrojovelli** [comment]
Sending to Jesse for review

**Comment by Patricia-Torres** [comment]
@pedrojovelli pode me passar um link para subir esse vídeo? Please

**Comment by Patricia-Torres** [comment]
https://drive.google.com/drive/folders/1hQffuJinfe5pw-JFYS_M5ojreSZ5rc9X?usp=sharing

**Comment by rioslumstudio** [comment]
Enviado para o Jesse

**Comment by rioslumstudio** [comment]
Fazer com que o esquema das luzes piscando com o CANDACE OWENS vá para um fade-out.

Depois gerar o vídeo separado da bandeira em loop (tipo uns 20 segundos de video e eles deixam em loop)

**Comment by Patricia-Torres** [comment]
https://drive.google.com/drive/folders/1W_hVA8yEk-6ZjFuEpSB5k8hxN1yqSsTa
Flags Backdrop

**Comment by Patricia-Torres** [comment]
https://drive.google.com/drive/folders/1kj1FNJU9QSaiShQ77Iuc87679-vcX-P1
V2 - Countdown (without flag)

**Comment by rioslumstudio** [comment]
Pat. Está rolando um corte seco no final.

Precisamos que seja um pouco mais suave este final.. .que o som chegue a zero.. nem que você estenda um pouquinho mais o vídeo até ficar tudo preto.

![Screen Shot 2019-11-06 at 11 47 12](https://user-images.githubusercontent.com/47640466/68308173-2b972000-008b-11ea-9dfa-582e2305dbfd.png)

**Comment by Patricia-Torres** [comment]
**DONE**
v2
https://drive.google.com/drive/folders/1kj1FNJU9QSaiShQ77Iuc87679-vcX-P1

**Comment by pedrojovelli** [comment]
Enviado para o cliente

**Comment by Patricia-Torres** [comment]
Acrescentar o "Final Speaker"

**Done**
Blexit Countdown - Final Speaker
https://drive.google.com/drive/folders/1kj1FNJU9QSaiShQ77Iuc87679-vcX-P1

**Comment by pedrojovelli** [comment]
Perfeito !
