### ISSUE TITLE
BLEXIT - Poster 

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#60]
Por favor, fazer o poster para ir para o site do blexit:

### ARQUIVO aqui:
[Poster.psd.zip](https://github.com/rioslumstudio/Design/files/3888136/Poster.psd.zip)

__________________________________________

Dados do evento:
BLEXIT charlotte will be on January 19th 2020. Will need speaker promo posters for me, Brandon Tatum, Will Witt, Larry Elder, KingFace, & Terrence Williams.

__________________________________________

### Aplicar foto da cidade de Charlotte - North Caroline

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1S1IZ8WC1Z4wOAn4UT7TLgmrVzLzvmrcx?usp=sharing)**

**Comment by pedrojovelli** [comment]
Pat. Desculpe. O erro foi meu, mas é NORTH CAROLINA

![Screen Shot 2019-11-25 at 18 17 04](https://user-images.githubusercontent.com/15367213/69578666-b8a90700-0faf-11ea-94e6-2787f5f2e063.png)

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1S1IZ8WC1Z4wOAn4UT7TLgmrVzLzvmrcx?usp=sharing)**

**Comment by pedrojovelli** [comment]
Perfeito.
