### ISSUE TITLE
BLEXIT - Poster Youtube

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#61]
**ARQUIVO aqui:**
[Candace.psd.zip](https://github.com/rioslumstudio/Design/files/3888154/Candace.psd.zip)

Preparar um poster seguindo o mesmo arquivo em PSD acima, porém, com a cidade de  CHARLOTTE - North Carolina a noite.

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1VQVRcAohL85GibsKsCKhOqndUmCAaQWV?usp=sharing)**

**[Pasta raiz desse evento de Charlotte - Jan 19](https://drive.google.com/drive/folders/1k1XYKK6waef8KDqncCeHwbSgojPT5qU1?usp=sharing)**

**Comment by pedrojovelli** [comment]
Pat.

Por favor, use esta opção aqui:

![Screen Shot 2019-11-25 at 18 15 41](https://user-images.githubusercontent.com/15367213/69578567-83041e00-0faf-11ea-9388-a2ff3bd7b2bf.png)

e dê uma leve escurecida em baixo pra ressaltar um pouco o logo do BLEXIT

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1VQVRcAohL85GibsKsCKhOqndUmCAaQWV?usp=sharing)**

**Comment by pedrojovelli** [comment]
Perfeito.
