### ISSUE TITLE
Turning Point - Brand Package Edit

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#62]
Fellipe.

Por favor, identifique todos os mockups de peças de papelaria que possua o endereço do youtube da Turning Point e remova o "The" do início do endereço.

**Comment by felliperinschede** [comment]
done

**Comment by pedrojovelli** [comment]
Fellipão.

Por favor, checar comentários da Lucia no documento. 6 comentários ao todo:

https://drive.google.com/file/d/1FPloFZEOpYA_J1iOHG-FYl-FQ6PGrFwc/view?usp=sharing

**Comment by pedrojovelli** [comment]
Lucia.

Please check if the edits were executed.

File is here:
https://drive.google.com/file/d/1LzYhM0eDC59b3rjDrxYDMiK7yrrutc_q/view?usp=sharing

**Comment by LuciaFurlan1987** [comment]
Hey @pedrojovelli ,

The latest version you sent me looks great. No further comments from my end!

Ready to send to Tyler.

Best,
Lucia

**Comment by pedrojovelli** [comment]
Amazing @LuciaFurlan1987 .

Great work @felliperinschede  !

Closing the issue.
