### ISSUE TITLE
Charlie Kirk - Podcast Backdrop and Table

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#63]
Do 2 versions of the design for the table and wall for Charlie Kirk's podcast / interviews.

This is a reference of what TPUSA's team have done for TPUSA's table and wall:

![Screen Shot 2019-11-25 at 11 58 35 AM](https://user-images.githubusercontent.com/15367213/69584129-31619080-0fbb-11ea-89c5-ada0c34bf695.png)

____________________________

Files from the printer:
[30x42 Round Stretch Wrap - TPUSA General.pdf](https://github.com/rioslumstudio/Design/files/3887901/30x42.Round.Stretch.Wrap.-.TPUSA.General.pdf)

[10x10 Single-side Wall.pdf](https://github.com/rioslumstudio/Design/files/3887897/10x10.Single-side.Wall.pdf)

____________________________

Charlie Kirk's podcast logo and PodcastOne logo:
https://drive.google.com/file/d/17ZwfVAoYCUyDxiRDqUHWNUMb5wFZ75E_/view?usp=sharing

**Comment by pedrojovelli** [comment]
![mesa_](https://user-images.githubusercontent.com/15367213/69662951-11d27280-1064-11ea-804e-14faed9c9a19.jpg)

**Comment by pedrojovelli** [comment]
Logo do Podcast One:

http://ww1.prweb.com/prfiles/2018/01/09/15150493/PC1Logo_Black_Red.png

**Comment by pedrojovelli** [comment]
![Screen Shot 2019-11-26 at 16 01 01](https://user-images.githubusercontent.com/15367213/69663848-e3ee2d80-1065-11ea-9e9d-9c5110e51f34.png)

**Comment by pedrojovelli** [comment]
Fellipão.

Por favor, se puder subir os arquivos editáveis + JPGs nas respectivas pastas:

https://drive.google.com/drive/folders/1ZXRdY6reguYnpgnIgAJn36kCIWDNX8gE?usp=sharing

**Comment by felliperinschede** [comment]
Dona ;D

**Comment by pedrojovelli** [comment]
![cor-logo](https://user-images.githubusercontent.com/15367213/69735030-c032f200-110e-11ea-8f17-ecef329825c0.jpg)

**Comment by pedrojovelli** [comment]
Elaborar 2 versões de parede num esquema assim: 

- Sem logo nenhum...

![Screen Shot 2019-11-27 at 12 13 56](https://user-images.githubusercontent.com/15367213/69735443-74347d00-110f-11ea-8710-27339b5dbd36.png)
![Screen Shot 2019-11-27 at 12 14 08](https://user-images.githubusercontent.com/15367213/69735444-74cd1380-110f-11ea-8226-5de8f5d32df6.png)

**Comment by pedrojovelli** [comment]
Wall PDF:
https://drive.google.com/file/d/1xwMauBQSydfvYq-13ElqpeFRTzZyfb-e/view?usp=sharing

Table PDF:
https://drive.google.com/file/d/1Ei-Yf76l1D9RHRdU09F2FViHiOlieD3a/view?usp=sharing

3d Mockup for preview:
https://drive.google.com/drive/folders/1RNOj-KVN_-QHV84RNrVF6YoJkKu8Kytp?usp=sharing
