### ISSUE TITLE
Charlie Kirk - 3D Mockup of Backdrop and Table

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#64]
Segue especificações das peças

[30x42 Round Stretch Wrap - TPUSA General.pdf](https://github.com/rioslumstudio/Design/files/3887901/30x42.Round.Stretch.Wrap.-.TPUSA.General.pdf)

[10x10 Single-side Wall.pdf](https://github.com/rioslumstudio/Design/files/3887897/10x10.Single-side.Wall.pdf)

**Comment by Patricia-Torres** [comment]
![Table](https://user-images.githubusercontent.com/43677737/69673572-56b4d400-1079-11ea-8d79-29eb95355227.jpg)

**Comment by Patricia-Torres** [comment]
![table and backdrop  01](https://user-images.githubusercontent.com/43677737/69676931-8ddab380-1080-11ea-90c1-7a1f4e874630.jpg)

**Comment by pedrojovelli** [comment]
Lindo Pat !!!

se vocÊ puder só gerar render em algo mais nesse ângulo aqui:

![Screen Shot 2019-11-26 at 19 15 00](https://user-images.githubusercontent.com/15367213/69677125-f9bd1c00-1080-11ea-8d74-852b0eae1065.png)

Com relação ao tamanho da parede com base no tamanho da mesa, estão em proporção?

**Comment by Patricia-Torres** [comment]
![table and backdrop  02](https://user-images.githubusercontent.com/43677737/69677938-ea3ed280-1082-11ea-974e-4e57985b2504.png)
Tinha feito esse ângulo também. Vê se está bom, se não eu preparo outro amanhã.
Estão na proporção

**Comment by Patricia-Torres** [comment]
**[As imagens estão aqui](https://drive.google.com/drive/folders/1OPlia7Te9lgFB_htkfayWGJxaN6bubJF?usp=sharing)**
