### ISSUE TITLE
TPUSA brand package typo correction

### ISSUE THREAD

**Issue by LuciaFurlan1987** [rioslumstudio/Design#66]
Hi @felliperinschede,

Could you correct the following?

From page 65 to page 80 of the brand package, the header title should be STATIONERY instead of STATIONARY.

Thank you!
Lucia

**Comment by LuciaFurlan1987** [comment]
This is the file: https://drive.google.com/file/d/1FRvSjjNL4A32PdufXxLMXcRvdl0pQ1e7/view

**Comment by felliperinschede** [comment]
Hi @LuciaFurlan1987 ! 
Here's the link to the correct PDF.

https://drive.google.com/drive/u/2/folders/1jS0WCU7plFpitQhZfxbrzv2HkPWS4Qh3

Could you please take a look to the edits?

Thanks!

**Comment by LuciaFurlan1987** [comment]
All good! 

Thank you, @felliperinschede .
