### ISSUE TITLE
Add Sponsorship Logos to SAS event page

### ISSUE THREAD

**Issue by LuciaFurlan1987** [rioslumstudio/Design#67]
Hi @Patricia-Torres !

Could you add the logos of the attached folder to the Sponsors section of this page? https://www.tpusa.com/event/studentactionsummit

LOGOS: https://mail.google.com/mail/u/1/?tab=wm&ogbl#inbox/FMfcgxwGBwShChLGKqpRvRwdFJknrhQh

**Comment by Patricia-Torres** [comment]
Hey @LuciaFurlan1987 
I am having some trouble to acess this link of the LOGOS,
could you check if this link is working for you, please?

**Comment by Patricia-Torres** [comment]
**[Aqui](https://drive.google.com/drive/folders/1Ll57GpmWn7Wgk-Qj5W9ECdfeNsW2eeur?usp=sharing)**

**Comment by LuciaFurlan1987** [comment]
Hey @pedrojovelli ,

Could you rearrange the logo order to the following plus add the corresponding URLs?

1st row: Alliance Defending Freedom (https://adflegal.org/) - Students for Trump (https://trumpstudents.org/) - Goldwater Institute (https://goldwaterinstitute.org/url)

2nd row: Crave News (https://cravenews.com/#1543611389871-c51c472b-a6b2) - Fox Nation (https://try.nation.foxnews.com/) - Independent Institute (https://www.independent.org/)

3rd row: Pepperdine (https://publicpolicy.pepperdine.edu/) - Heritage Foundation (https://www.heritage.org/) - EagleFire (https://eaglefiremobile.com/)

4th row: Atlas Society (https://atlassociety.org/) - CFACT (https://www.cfactcampus.org/) - Hoover Institution (https://www.hoover.org/)

5th row: Life Dynamics (https://lifedynamics.com/) - NRA-ILA (https://www.nraila.org/) - PragerU (https://www.prageru.com/)

6th row: US Term Limits (https://www.termlimits.com/) - Clarion Project (https://clarionproject.org/) - Satan's Gambit (https://satansgambit.com/)

7th row: Hillsdale College (https://www.hillsdale.edu/) - Convention of States Action (https://conventionofstates.com/)

You can remove the Leadership Institute's logo.

Thank you!

**Comment by Patricia-Torres** [comment]
Oi @robanquieri 

Você consegue me ajudar com isso?
Estou com dificuldades em colocar as logos separadas lado a lado. Quando subo no WP elas ficam lado a lado mas quando salvo a página e vou verificar, elas ficam uma embaixo da outra.

Já subi todas no WP. **Só precisamos mesmo substituir a imagem inteira que está lá pelas imagens das logos separadas.**

**Acima está o pedido de ordem da Lucia.**

Imagens: 
[Logos Alpha.zip](https://github.com/rioslumstudio/Design/files/3912515/Logos.Alpha.zip)

Página: 
https://www.tpusa.com/event/studentactionsummit

**Comment by Patricia-Torres** [comment]
@LuciaFurlan1987 
Should I remove the Charlie Kirk logo as well?

**Comment by LuciaFurlan1987** [comment]
Hi @Patricia-Torres 
I will email the client and let you know as soon as they answer.

Thank you!

**Comment by LuciaFurlan1987** [comment]
Hey @Patricia-Torres 
We can eliminate Charlie Kirk's logo.

Thank you!

**Comment by LuciaFurlan1987** [comment]
Hey @pedrojovelli 
The client has just asked if we can add three more sponsors to the Sponsor section of SAS (tpusa.com/sas).

Falkirk Center (no hyperlink needed) 
Young Jewish Conservatives (http://www.youngjewishconservatives.org/)
Project Veritas (https://www.projectveritas.com/)

The logos are attached.

Let me know your timeline for this. Thank you!

Lucia
![Project Veritas](https://user-images.githubusercontent.com/58268389/70584690-8c80af00-1b87-11ea-8474-9fc3ba6297da.png)
![Young_Logo](https://user-images.githubusercontent.com/58268389/70584696-8db1dc00-1b87-11ea-8635-924ab833152a.jpg)
![FalkirkLogo_Ampersand](https://user-images.githubusercontent.com/58268389/70584726-a3270600-1b87-11ea-8811-45b9b55640f9.png)

**Comment by Patricia-Torres** [comment]
Oi @robanquieri 
já deixei as logos prontas para serem acrescentadas, subi elas lá no WP.

Você pode adicionar essas 3 logos, por favor?

Falkirk Center (no hyperlink needed)
Young Jewish Conservatives (http://www.youngjewishconservatives.org/)
Project Veritas (https://www.projectveritas.com/)

Link direto do WP: https://backend.tpusa.com/wp-admin/post.php?post=395&action=edit
Link da página: https://www.tpusa.com/event/studentactionsummit

Obrigada!

**Comment by robanquieri** [comment]
Done!

**Comment by Patricia-Torres** [comment]
Thanks!

@LuciaFurlan1987 can you look if it's all right?

**Comment by LuciaFurlan1987** [comment]
Looks great @Patricia-Torres !

Thank you so much!
Lucia

**Comment by LuciaFurlan1987** [comment]
Sorry @Patricia-Torres 
The client has just sent one more logo to add (attached).

This is the name o the sponsor and its website:
Young Americans for Liberty (https://yaliberty.org/)

![YAL-logo-horz-solideagle-white](https://user-images.githubusercontent.com/58268389/70632506-912f7c80-1bf4-11ea-9380-6b781e30069a.png)

**Comment by Patricia-Torres** [comment]
@LuciaFurlan1987 
I just add the Young Americans for Liberty at the end.
Can you check, please?

https://www.tpusa.com/event/studentactionsummit

Thanks!

**Comment by LuciaFurlan1987** [comment]
It looks great, thank you @Patricia-Torres !

**Comment by LuciaFurlan1987** [comment]
Hey @Patricia-Torres 

Could you add this logo to the Sponsor section of tpusa.cpm/sas?

Nine Line Apparel (https://www.ninelineapparel.com/collections/on-sale?gclid=CjwKCAiAis3vBRBdEiwAHXB29E0sdx-DXSciv2QIPuSSCPbA084W1ejxEsDWGQSWpOa9Y5GlS-TMTRoC18AQAvD_BwE)
[DropLine_Front_Black.pdf](https://github.com/rioslumstudio/Design/files/3962483/DropLine_Front_Black.pdf)

**Comment by Patricia-Torres** [comment]
@LuciaFurlan1987
I just add the Nine Line Apparel at the end.
Can you check [here](https://www.tpusa.com/event/studentactionsummit), please?


Thanks!

**Comment by LuciaFurlan1987** [comment]
Thank you @Patricia-Torres , perfect!
