### ISSUE TITLE
TPUSA - Fatiar logos em formatos iguais (PNG)

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#68]
[LOGOS.psd.zip](https://github.com/rioslumstudio/Design/files/3912016/LOGOS.psd.zip)

**Comment by Patricia-Torres** [comment]
[Logos.zip](https://github.com/rioslumstudio/Design/files/3912096/Logos.zip)

**Comment by Patricia-Torres** [comment]
[Logos Alpha.zip](https://github.com/rioslumstudio/Design/files/3912193/Logos.Alpha.zip)

**Comment by pedrojovelli** [comment]
Awesomee !!
