### ISSUE TITLE
TPUSA - Sessão Productions

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#69]
O Rogério terminou de programar o esquema pra puxar automático os shows de TPUSA Productions direto do YOUTUBE.... porém, o loguinho identificando cada canal na direita superior de cada caixinha, está quase que desaparecendo ...

![Screen Shot 2019-12-02 at 13 12 25](https://user-images.githubusercontent.com/15367213/69975295-b130b300-1505-11ea-8927-16b8bcc30545.png)

Devemos buscar fazer em 60x60px em vetor a aplicação dos logos na cor original com um círculo de fundo... espelhando como estão os logos de redes sociais em STAY ON POINT do site da TPUSA hoje:
http://tpusa.com/

**Logos:**

FREEDOM FIGHTS:
https://drive.google.com/drive/folders/1KtBsL7Oi8u__B5_QRYJXIwlR_4W0x3UJ?usp=sharing

POPLITICS:
https://drive.google.com/file/d/19u9J7gfNzfN0wdJIcJWtjFKpedqdoY3v/view?usp=sharing

ONLY IN AMERICA:
https://drive.google.com/file/d/1wycbX9O1k3a9U8JK5AXpLKfhPgSLuZCs/view?usp=sharing

180:
https://drive.google.com/file/d/1LdcxkGIfyBhhAJxAVbAVB3P-BpiIcfGz/view?usp=sharing

**Comment by felliperinschede** [comment]
Done
Sent by email

**Comment by pedrojovelli** [comment]
amazing ! 

thanks so much !
