### ISSUE TITLE
BLEXIT: Walk-On Videos

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#7]
Pat. Por hora, faremos algo no estilo que fizemos com aquela intro do nome da candace:

![Screen Shot 2019-11-04 at 11 41 24](https://user-images.githubusercontent.com/15367213/68129285-0b832780-fef8-11e9-86f5-9881f5d1e0c9.png)

![Screen Shot 2019-11-04 at 11 41 30](https://user-images.githubusercontent.com/15367213/68129286-0b832780-fef8-11e9-8fda-5c5d0bfb525a.png)

- Candace Owens
- Brandon Tatum
- Terrence Williams
- David Harris
- Will Witt

**Comment by Patricia-Torres** [comment]
É para fazer versões com esses outros nomes?
Tanto nessa parte quanto na parte da bandeira?

**Comment by pedrojovelli** [comment]
Correto .. a idéia é que comece com esse esquema das cores e textos piscando ... com a mesma música que usamos para o video do COUNTDOWN ... e vai rolando o FADE-OUT da música ... e vai para a cena da bandeira ;-)

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F

**Comment by pedrojovelli** [comment]
Amazing work !

sending to Jesse.

**Comment by Patricia-Torres** [comment]
- Ajustar cortando o vídeo do Countdown antes (com o Ye piscando na fumaça)

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F

**Comment by rioslumstudio** [comment]
Pat. Por favor, faça um fade-in do som no início do vídeo

**Comment by Patricia-Torres** [comment]
**DONE**
https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F

**Comment by rioslumstudio** [comment]
Aguardando audios de anúncios de cada nome

**Comment by Patricia-Torres** [comment]
Recebemos o áudio do Brandon Tatum

Até agora temos o Walk-on do Brandon e da Candace
**AQUI**
https://drive.google.com/drive/folders/1olX2IzTAVdJV_NxSaWpUjKzKb-j8KS0F

**Comment by rioslumstudio** [comment]
Enviei para o Jesse e estamos aguardando os demais audios...

**Comment by Patricia-Torres** [comment]
Adicionar mais esses dois nomes:

- KingFace 
- Maj Toure

**Comment by Patricia-Torres** [comment]
Tudo pronto, esperando os áudios de:

- David Harris Jr.
- Terrence Williams
- Maj Toure
- KingFace

**Comment by pedrojovelli** [comment]
Ok.
