### ISSUE TITLE
Solicitação de imagens - TPUSA

### ISSUE THREAD

**Issue by robanquieri** [rioslumstudio/Design#71]
Caros, preciso de uma versão do GIF abaixo com fundo transparente:

![shop-now-blue](https://user-images.githubusercontent.com/4391611/70146093-45bf2080-1680-11ea-889a-c50fdbbd365a.gif)

E uma versão dessa imagem para fundos claros, branco por exemplo:

<img width="311" alt="Screen Shot 2019-12-04 at 10 27 15" src="https://user-images.githubusercontent.com/4391611/70146334-b9f9c400-1680-11ea-9859-cfd1d3c33c4d.png">

**Comment by pedrojovelli** [comment]
![sidebar_white_bg](https://user-images.githubusercontent.com/15367213/70162725-e4597a80-169c-11ea-9cff-bda4460fa35b.gif)

**Comment by pedrojovelli** [comment]
![1776](https://user-images.githubusercontent.com/15367213/70163044-837e7200-169d-11ea-9c48-eeb8296b9c3d.png)
