### ISSUE TITLE
Blexit: Selah Video Concept

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#74]
### Download these videos:

REFERENCES:

timelapse flowers:
https://www.pond5.com/pt/stock-footage/item/115318394-flower-motion-time-lapse-red-dahlia-plant-close-5994fps-ntsc

https://www.pond5.com/pt/stock-footage/item/56747741-flor-dente-de-leao-esta-abrindo-espaco-de-tempo

https://www.pond5.com/pt/stock-footage/item/88271282-yellow-sunflower-flower-opening-timelapse-zoom
https://www.pond5.com/pt/stock-footage/item/96390688-flower-motion-time-lapse-zoom-sunflower-opening-bouquet-2997

water
https://www.pond5.com/pt/stock-footage/item/116346694-bubbles-underwater-sliding-and-going-planet-earth-global-wor

https://www.pond5.com/pt/stock-footage/item/116615219-upside-down-bubbles-underwater-sliding-and-going-planet-eart

galaxy:

https://www.pond5.com/pt/stock-footage/item/41294268-interstellar-nebula-space-journey

https://www.pond5.com/pt/stock-footage/item/91588266-flying-space-through-stars-and-nebulas

Sky:
https://www.pond5.com/pt/stock-footage/item/67942598-epic-storm-tropical-clouds-sunset-4k-uhd-timelapse

Trees:
https://www.pond5.com/pt/stock-footage/item/95218496-walking-forest-among-trees

https://www.pond5.com/pt/stock-footage/item/34553649-viajando-pela-sun-lit-floresta

Tornado:
https://www.pond5.com/pt/stock-footage/item/65028630-hurricane-over-earth-3d-animation

Lava:
https://www.pond5.com/pt/stock-footage/item/66527756-close-lava-flowing-kilauea-volcano-hawaii-night

Ballet:
https://www.shutterstock.com/pt/video/clip-31129057-silhouette-ballerina-ballet-tutu-pointe-on-dramatic

https://www.shutterstock.com/pt/video/clip-31129090-silhouette-ballerina-ballet-tutu-pointe-on-dramatic

https://www.shutterstock.com/pt/video/clip-31129105-silhouette-ballerina-ballet-tutu-pointe-on-cloudy

https://www.shutterstock.com/pt/video/clip-31129114-silhouette-ballerina-ballet-tutu-pointe-on-dramatic

https://www.shutterstock.com/pt/video/clip-31129069-close-ballet-dancer%27s-feet-she-practices-pointe

**Comment by Patricia-Torres** [comment]
- [**Timelapse Flowers**](https://drive.google.com/drive/folders/1YMzF5q-NYjFaSIgowHtR6GAXhanArIOM?usp=sharing)
- [**Water**](https://drive.google.com/drive/folders/11TGcxhd-KlvItdCeHWbzPOploAk7vCJK?usp=sharing)
- [**Galaxy**](https://drive.google.com/drive/folders/1LlDtURLT_JZfQWB5lGbKpmQv1IUhfyXG?usp=sharing)
- [**Sky**](https://drive.google.com/drive/folders/17Sw7GjR_duKngOL-chIYLMHGsWUsrZgK?usp=sharing)
- [**Trees**](https://drive.google.com/drive/folders/1Njvxj9ZB1bSqkvnLEZrv8rtenes88zpZ?usp=sharing)
- [**Tornado**](https://drive.google.com/drive/folders/1EJkk0YFQeCM1P-uCiLjMzrTzz6RnbbkH?usp=sharing)
- [**Lava**](https://drive.google.com/drive/folders/1gkBKpp5RsDfHTSKdF7Az7sWqLm0pnqVJ?usp=sharing)
- [**Ballet**](https://drive.google.com/drive/folders/1sIjgnmBeoFW2InwrNYVtmyQGEt7Ycl6W?usp=sharing)

**Comment by Patricia-Torres** [comment]
https://docs.google.com/document/d/1BS45Y1Bt1wH6KHJRDbAXsOhauD_vH-eKUlYdpgqIVIA/edit

Baixar clips

**Comment by Patricia-Torres** [comment]
**[First DRAFT](https://drive.google.com/drive/folders/1l1c0weBuNip1VC8baSavoVyDpyuKtj-0?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[DRAFT 02](https://drive.google.com/drive/folders/1l1c0weBuNip1VC8baSavoVyDpyuKtj-0?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[DRAFT 02](https://drive.google.com/file/d/1XlgSydWIXlpBUqbjQ9Ia1sK9MdIqTJM6/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[DRAFT 03](https://drive.google.com/file/d/1vx-BOAeSZIzIyVis-Py0bLi3z64b-P4l/view?usp=sharing)**

Lyric animados
**God is King, we the soldiers
Ultrabeam out the solar**

**Comment by Patricia-Torres** [comment]
**[DRAFT 04](https://drive.google.com/file/d/1asCwiN5nOH0l02Udw25kT2XrzdkIyOgj/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
**[DRAFT 05](https://drive.google.com/file/d/1_7ehYWShnvC6A4PSrLl9CoclJSqlUZO1/view?usp=sharing)**

**Comment by pedrojovelli** [comment]
![Screen Shot 2019-12-06 at 18 33 47](https://user-images.githubusercontent.com/15367213/70357926-dbaca400-1856-11ea-9d52-ada87a3f9447.png)

- Validating the Concept
- Slowmotion of the guy
- Validate the GUNSHOTS (flashing faces on the beats)
- Validate the cocktail (mix of videos -- man and the universe shots)
- Final track

**Comment by pedrojovelli** [comment]
Tentar fazer uma opção de corte da música da seguinte forma ....

retirar o rap que tem no final após o coral ....

ou seja, tomando como base a música desse vídeo aqui:
https://drive.google.com/file/d/1_7ehYWShnvC6A4PSrLl9CoclJSqlUZO1/view?usp=sharing

retirar música de 1:40 até 2:16

**Comment by Patricia-Torres** [comment]
1:00 - 1:22 Draft 05

[Here](https://drive.google.com/file/d/1pzhnvDE0taFxzC-ecI4O5bVClj3cjue1/view?usp=sharing)
