### ISSUE TITLE
TPUSA: Adding profiles on SAS Event

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#75]
**This is the event we need to add the profiles:**
https://www.tpusa.com/event/studentactionsummit

**We have announced more speakers, if we could get them added to the site that would be great**

-Rudy Giuliani (photo will be in folder by Monday)
-Dinesh D'Souza
-Congressman Matt Gaetz
-Ambassador Richard Grenell (photo will be in folder by Monday)
-Barry Farah
-Jaco Booyens
-Matthew Whitaker
-Senator Ted Cruz
-Dave Rubin
-Rich Lowry
-Judge Ken Starr
-James O'Keefe
-Gregg Jarrett (photo will be in folder by Monday)
-Brent Bozell
-Alex Marlow
-Chad Prather

Here is the link again to the headshot folder so you don't have to search for it!
https://drive.google.com/drive/folders/1U7reLriTXR2b1sQQVRKYEJEfgYIkHbL5?usp=sharing

**Comment by Patricia-Torres** [comment]
-Rudy Giuliani (sem foto)
-Ambassador Richard Grenell (sem foto)
-Gregg Jarrett (sem foto)
