### ISSUE TITLE
TPUSA: Productions Section

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#79]
Elaborar mais uma sessão para a página Productions.

A sessão vai se chamar TPUSA Originals.
Essa sessão irá puxar vídeos antigos com bastante views do Youtube da TurningPoint.

Precisamos elaborar o mockup com a adição dessa sessão Originals e também criar a nova página interna.

Vale elaborar os mockups com base neste vídeo aqui: **TPUSA Productions page:**
https://tpusa-front-staging.herokuapp.com/productions

**Comment by pedrojovelli** [comment]
Fellipão. Por favor, retire o símbolo de fundo. Deixe somente as estrelas para facilitar para o Rogério no desenvolvimento:

![Screen Shot 2019-12-11 at 14 16 46](https://user-images.githubusercontent.com/15367213/70644116-1c266c00-1c21-11ea-94a4-f32682557335.png)

**Comment by LuciaFurlan1987** [comment]
Hey @felliperinschede 

Could you introduce the following text?

1. In the Productions Homepage, in the paragraph below the title and on the right-hand side of the logo: 
TPUSA ORIGINALS 
TPUSA Originals highlights the dangers of leftist thought and its effect on 21st century America. 

2. In the TPUSA Originals page: 
TPUSA ORIGINALS 
TPUSA Originals exposes the dangers and pitfalls of leftist ideology and ultimately highlights the consequences such ideas could have on modern America.

**Comment by felliperinschede** [comment]
Sure @LuciaFurlan1987 ! Give just a few minutes :D

**Comment by felliperinschede** [comment]
Done

**Comment by LuciaFurlan1987** [comment]
Thank you @felliperinschede !

Could you also add the following text to the blue section of the homepage, right below the title?

EXPLORE TPUSA'S ORIGINAL
new media productions and stay up-to-date on all things news and pop culture. From today’s headlines, to timeless truths, to the latest in celebrity gossip, we aim to educate, enlighten, and entertain.

**Comment by felliperinschede** [comment]
Hey @LuciaFurlan1987,
I don't get it, where is this text going? Could you please send me a print?

**Comment by LuciaFurlan1987** [comment]
Hey @felliperinschede 

See the circled section highlighted in the attached image - thank you!
![Productions Homepage](https://user-images.githubusercontent.com/58268389/70653484-301a9f80-1c1a-11ea-9fdb-d3499007b9d6.jpg)

**Comment by felliperinschede** [comment]
Thanks @LuciaFurlan1987 !
Attached with the Edit ;D

![Main-Page_NEW](https://user-images.githubusercontent.com/57017535/70654442-b3dd8780-1c2c-11ea-8134-d02589775de3.jpg)

**Comment by LuciaFurlan1987** [comment]
Perfect, thank you!
