### ISSUE TITLE
BLEXIT: Intro and Outro 

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#8]
Pat. 
Por favor, baixar este vídeo aqui e aplicar aquela intro  e outro que fizemos para o BLEXIT.

https://www.youtube.com/watch?v=IT2UH74ksJ4&app=desktop

Gerar versão em .MP4 e .MOV

**Comment by Patricia-Torres** [comment]
Devo tirar essa parte do video que tem no final e a introdução que ele tb tem no começo?
![image](https://user-images.githubusercontent.com/43677737/68131028-1f7c5880-fefb-11e9-9050-2230f8dcf961.png)

**Comment by pedrojovelli** [comment]
Sim. Por favor. Retire essa ceninha do PRAGER U

**Comment by Patricia-Torres** [comment]
**DONE**

https://drive.google.com/drive/folders/19Jj0w3fWNolnMH2KWB6D7qQkqtM2MGQl

**Comment by rioslumstudio** [comment]
https://www.youtube.com/watch?v=IT2UH74ksJ4&app=desktop

Pat. O Jesse pediu para manter o audio que rola no final do vídeo... só substituir a parte final do PRAGER U pelo do BLEXIT .... mas mantendo o som e tal.. o mais próximo o possível do vídeo original...

**Comment by Patricia-Torres** [comment]
@pedrojovelli Eu vou ter que mudar um pouco a parte do final e do Outro pq ele termina antes do video acabar...Eu corte no tempo que o Outro termina, por isso o audio acaba junto. Eu vou deixar ele mais tempo na tela então.

**Comment by Patricia-Torres** [comment]
**DONE**
O final ficou bem parado pq no vídeo original eles tem uma mensagem junto com o PragerU. Eu cortei isso tudo e deixei a vinheta de encerramento estendida mantendo o som do vídeo original. Está na mesma pasta.
