### ISSUE TITLE
TPUSA: Tutorial Creating Activism Hub

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#81]

**Comment by Patricia-Torres** [comment]
**[Option 01](https://drive.google.com/file/d/1gIiMdk3h2t4M8qNkJaQwrsbqW5UnMMiu/view?usp=sharing)**

**[Option 02](https://drive.google.com/file/d/1yTJ-Ax3L3OTxUUQl-vMaKBgoldtpzBm-/view?usp=sharing)**

**Comment by LuciaFurlan1987** [comment]
Hey @Patricia-Torres 

I like Option 2. Could you change the title at the beginning to the following?

06 - TPUSA Creates a new Activism Hub

Thank you!

**Comment by Patricia-Torres** [comment]
Done -> [TPUSA Creates a new Activism Hub](https://drive.google.com/file/d/1t41cr8fGlUGYMFwRiuFt5H0hwxY1d4M3/view?usp=sharing)

Let me know if this ok, please.

**Comment by LuciaFurlan1987** [comment]
Perfect! Thank you!

**Comment by LuciaFurlan1987** [comment]
Hey @Patricia-Torres 

Could you change the word "new" in the title to "New" with a capital N?

Thank you!

**Comment by Patricia-Torres** [comment]
Sure!

**[Here is](https://drive.google.com/file/d/12yYOfvqAiVYPtAYeg_ttAPv9kQsdh2Yp/view?usp=sharing)**

@LuciaFurlan1987

**Comment by LuciaFurlan1987** [comment]
Thank you @Patricia-Torres !
