### ISSUE TITLE
Charlie Kirk - Newsletter

### ISSUE THREAD

**Issue by felliperinschede** [rioslumstudio/Design#82]
Basicamente, seria um header seguindo o estilo do site/identidade do Charlie Kirk (talvez elaborar uma versao com E uma versao sem foto). Com chamadas para os seguintes conteúdos:
- Media 
- blog
- Podcast
- Event

Aí no caso, vale analisar se seria ideal chamar tipo .... 3 posts de média, 3 posts de blog, 1 podcast e 3 próximos eventos.

E o footer teria links de redes sociais do Charlie  Kirk ... um Visit www.charliekirk.com e só..

**Comment by pedrojovelli** [comment]
Fellipão.

Sobre a conversa que tivemos de elaborarmos 2 versões mais 'sérias' da newsletter do Charlie Kirk.

Segue aqui os PSDs do material que eu fiz pra facilitar pra ti:

https://drive.google.com/drive/folders/11rgORbUMiGh1JAxUZg24xTqRaAfXdlej?usp=sharing

Minha recomendação é você elaborar 2 versões com base na opções 2 que eu fiz (com base no conteúdo).

**Comment by felliperinschede** [comment]
Fala meu caro, 
Fiz alguns testes. Dá uma olhadinha por favor?

![New_Newsletter Option One](https://user-images.githubusercontent.com/57017535/70829519-5bd98900-1dc4-11ea-9071-316e9467c272.jpg)
![Uploading New_Newsletter Option Two.jpg…]()

**Comment by felliperinschede** [comment]
![New_Newsletter Option Two](https://user-images.githubusercontent.com/57017535/70831048-f25b7980-1dc7-11ea-9e9f-7c115e0c35ea.jpg)

**Comment by pedrojovelli** [comment]
**Approved Option**

![Revised Option Three](https://user-images.githubusercontent.com/15367213/71102603-8ac27700-2197-11ea-889a-4b14a94904a9.jpg)
