### ISSUE TITLE
TPUSA Production: Video loop for TPUSA ORIGINALS

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#83]
Caixinha do vídeo em loop

**Comment by Patricia-Torres** [comment]
@pedrojovelli 
Quais vídeos eu devo usar?
É naquele mesmo tamanho que eu fiz os vídeos do 180, Poplitics, etc?
280 x 300 no caso

**Comment by Patricia-Torres** [comment]
**[Here](https://drive.google.com/file/d/1bfvYIAnz5sOYQg8Od7CrlTWMtkFb8aHi/view?usp=sharing)**

**Comment by Patricia-Torres** [comment]
@robanquieri aqui o vídeo do [tpusa originals](https://drive.google.com/file/d/1bfvYIAnz5sOYQg8Od7CrlTWMtkFb8aHi/view?usp=sharing)

**Comment by robanquieri** [comment]
Obrigado!

**Comment by Patricia-Torres** [comment]
![TPUSA Originals image 01](https://user-images.githubusercontent.com/43677737/70923389-93377800-2006-11ea-883f-4d75777a02e2.jpg)

**Comment by Patricia-Torres** [comment]
![TPUSA Originals image 02](https://user-images.githubusercontent.com/43677737/70923405-97fc2c00-2006-11ea-87b0-9c76e2ec96fb.jpg)

**Comment by Patricia-Torres** [comment]
![TPUSA Originals image 03](https://user-images.githubusercontent.com/43677737/70923415-9cc0e000-2006-11ea-91c3-a7f913254af3.jpg)

**Comment by Patricia-Torres** [comment]
![TPUSA Originals image 04](https://user-images.githubusercontent.com/43677737/70923770-2f617f00-2007-11ea-9954-228ddd75247b.jpg)

**Comment by Patricia-Torres** [comment]
![TPUSA Originals image 05](https://user-images.githubusercontent.com/43677737/70923911-72235700-2007-11ea-8ac5-0d32fd4de107.jpg)

**Comment by Patricia-Torres** [comment]
![TPUSA Originals image 06](https://user-images.githubusercontent.com/43677737/70923983-92ebac80-2007-11ea-9d80-1668d2d1c9a1.jpg)
