### ISSUE TITLE
BLEXIT: Meeting Presentation

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#84]
Segunda-feira e terça, temos de arrematar essa apresentação que é basicamente uma cola para o Jesse conduzir a Candace e o marido durante o feedback do evento em que pediram investimentos para 2020.

É importante que essa apresentação seja FODA. Sendo assim, acho que uma forma inteligente de dividirmos tarefas é @felliperinschede  ficar responsável pela direção dos dividers e @pedrojovelli pela diagramação e organização do ppt.

**Presentation outline is here:**
https://docs.google.com/document/d/1Pg0Whgz87gCYRN-26bmKHt_DNJrnKQ7uy1OoUrqsjdw/edit?usp=sharing

**Blexit Logo:**
https://drive.google.com/file/d/1NbxAT57nU6mFqYCmbH766IYx5M_5SBpX/view?usp=sharing

**Comment by felliperinschede** [comment]
Bro, por ai?

![01_Dividers_Template](https://user-images.githubusercontent.com/57017535/70931668-51aacb00-200e-11ea-82cd-04fffbc66112.jpg)
![02_Dividers_Template](https://user-images.githubusercontent.com/57017535/70931669-52436180-200e-11ea-9540-5fee8f2f7ab8.jpg)
![03_Dividers_Template](https://user-images.githubusercontent.com/57017535/70931670-52436180-200e-11ea-8ac5-261a79c51c66.jpg)
![04_Dividers_Template](https://user-images.githubusercontent.com/57017535/70931671-52436180-200e-11ea-8799-c066a5df45da.jpg)
![05_Dividers_Template](https://user-images.githubusercontent.com/57017535/70931673-52436180-200e-11ea-9f65-c53be10f1cea.jpg)

**Comment by felliperinschede** [comment]
Segue alterado meu caro ;D

![04_Dividers_Template](https://user-images.githubusercontent.com/57017535/70933495-77d26a00-2012-11ea-8cad-5b2f76eada04.jpg)

**Comment by felliperinschede** [comment]
Segue o link para os PSDs, Qualquer duvida, só me gritar ;D

Download link
https://wetransfer.com/downloads/b93e021ec261761430f91e5f8cc6485720191216204727/779df3f3453e5b6efffc60ffe1cf4a4620191216204728/7c9020
