### ISSUE TITLE
Baastel: New Year Newsletter

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#85]
**Folder to upload files:**
https://drive.google.com/drive/folders/1VxO4n6nkkfwm5oidTJD80KnJ-PODLOLt?usp=sharing

**Client's request:**
For the content, I would say our logo, one nice picture or various pictures related to our work and the text “happy new year” in our languages of work (English, French, Spanish, Portuguese, etc.). Then they can suggest formats, be innovative, etc.

**Baastel Brand Package:**
https://drive.google.com/file/d/1ln62KLDEcc_h3Wi8g8T3JFn_zEbVt9ah/view?usp=sharing

**This is an e-mail that was sent last year and they want something that has a bit of this look and feel**
![Baastel email Marketing - French](https://user-images.githubusercontent.com/15367213/70920711-caeff100-2001-11ea-94c7-38cfe62120bd.png)

**Comment by pedrojovelli** [comment]
Segue sketches de referência para o e-mail:
![WhatsApp Image 2019-12-17 at 11 08 47](https://user-images.githubusercontent.com/15367213/71002306-bd983c80-20bd-11ea-8b4d-dab17ae5a211.jpeg)

![WhatsApp Image 2019-12-17 at 11 08 55](https://user-images.githubusercontent.com/15367213/71002336-cf79df80-20bd-11ea-940f-a82e4b2b00db.jpeg)

**Comment by felliperinschede** [comment]
Dia meu querido, seguem alguns estudos que fiz ;D
![Baastel_EmailMkt_01-01](https://user-images.githubusercontent.com/57017535/71097435-572b2100-2186-11ea-902c-2b8ba0caa79a.jpg)
![Baastel_EmailMkt_01-02](https://user-images.githubusercontent.com/57017535/71097437-572b2100-2186-11ea-8c4b-6f09fd8130e8.jpg)
![Baastel_EmailMkt_01-03](https://user-images.githubusercontent.com/57017535/71097438-572b2100-2186-11ea-8042-2a31db650b7f.jpg)
![Baastel_EmailMkt_01-04](https://user-images.githubusercontent.com/57017535/71097441-572b2100-2186-11ea-8c79-18885d65dc31.jpg)

**Comment by pedrojovelli** [comment]
Fellipe. Excelente trabalho com o layout.

Eu e a Lucia gostamos mais da seguinte opçõa abaixo:

![Screen Shot 2019-12-18 at 15 31 15](https://user-images.githubusercontent.com/15367213/71112905-4b9e2100-21ab-11ea-89c3-4b2a9406fc55.png)

- Gostaria de pedir pra você adaptar a largura da peça para 600px.
- Gostaria de pedir a ti para trabalhar um pouco mais no arranjo no topo. Trazendo mais detalhes para as fotos. Minha sugestão é aplicar frames em branco com sombra, saindo pra fora do "corpo do e-mail". Segue sugestão:

![Screen Shot 2019-12-18 at 15 40 15](https://user-images.githubusercontent.com/15367213/71113571-a3895780-21ac-11ea-8425-185a34914b25.png)

**Comment by felliperinschede** [comment]
Seguem as novas opções ;D

![Baastel_EmailMkt_01-01](https://user-images.githubusercontent.com/57017535/71121131-3da0ce00-21b4-11ea-984b-0dfc725872de.jpg)
![Baastel_EmailMkt_01-02](https://user-images.githubusercontent.com/57017535/71121134-3e396480-21b4-11ea-8dfd-e9e30ee38540.jpg)
![Baastel_EmailMkt_01-03](https://user-images.githubusercontent.com/57017535/71121136-3ed1fb00-21b4-11ea-9643-4d98a3d7556e.jpg)
![Baastel_EmailMkt_01-04](https://user-images.githubusercontent.com/57017535/71121138-3f6a9180-21b4-11ea-9419-eb30e92580c4.jpg)
![Baastel_EmailMkt_02-01](https://user-images.githubusercontent.com/57017535/71121139-40032800-21b4-11ea-888a-a1c44da382b7.jpg)
![Baastel_EmailMkt_02-02](https://user-images.githubusercontent.com/57017535/71121140-40032800-21b4-11ea-94bd-c61d75f0ef3b.jpg)

**Comment by LuciaFurlan1987** [comment]
Hey @pedrojovelli 

Below is some feedback:

1. Could we make "Happy new year" be "Happy New Year" (first letters capitalized)?

2. I believe the design is missing something festive or celebratory; something that feels a little more like a New Years Party. Could we add an element or two (perhaps in the footer or in the white space around the languages) that has a "New Years" feel to it?

**Comment by pedrojovelli** [comment]
Fellipão. Seguinte. Opção favorita minha, da Lucia e Jesse é a opção 3. Essa aqui:
https://drive.google.com/file/d/1IpaEPieuJ6ru2KTn460fIyhtreXYLxbE/view?usp=sharing

**Segue aqui considerações do Jesse. Gostaria de pedir a ti para trabalhar em cima delas hoje:**

These look great! Thank you so much for sharing them. We should probably show a few options to them; however, I agree with you - I like Option Three. Below are my thoughts and feedback:

- Could we make "Happy new year" be "Happy New Year" (first letters capitalized)?

- I believe the design is missing something festive or celebratory; something that feels a little more like a New Years Party. Could we add an element or two (perhaps in the footer or in the white space around the languages) that has a "New Years" feel to it?

**Comment by felliperinschede** [comment]
Thanks for the feedback!
Attached I'm sending the option three with the edits made o/

![Baastel_EmailMkt_03-01](https://user-images.githubusercontent.com/57017535/71198270-c88fd000-2269-11ea-8b78-814943ceac78.jpg)

**Comment by pedrojovelli** [comment]
Fellipão.

Opção massa. Por favor, estes elementos nas laterais, se puder deixá-los sem esse corte seco, pra dar mais aspecto de que estão flutuando.

![Screen Shot 2019-12-19 at 16 23 18](https://user-images.githubusercontent.com/15367213/71202902-cc2c5280-227b-11ea-847d-92237784bbcf.png)


Outro pedido, é elaborar mais uma versão talvez conectando mais com a identidade deles. Penso que uma saída pode ser bolinhas nas cores da Baastel ao redor do arranjo tipográfico ... talvez pontinhos formando tipo fogos de artifício, algo assim ...

**Comment by felliperinschede** [comment]
Segue alterado e também as novas opções;D

![Baastel_EmailMkt_03-01](https://user-images.githubusercontent.com/57017535/71205887-b4ec6580-2279-11ea-8306-96e5292aa38a.jpg)
![Baastel_EmailMkt_03-02](https://user-images.githubusercontent.com/57017535/71205888-b584fc00-2279-11ea-9dbe-f26c73178ad6.jpg)
![Baastel_EmailMkt_03-03](https://user-images.githubusercontent.com/57017535/71205889-b584fc00-2279-11ea-96dd-163b60b10ebd.jpg)
![Baastel_EmailMkt_03-04](https://user-images.githubusercontent.com/57017535/71205891-b584fc00-2279-11ea-9806-85c57b723783.jpg)

**Comment by LuciaFurlan1987** [comment]
Hi @felliperinschede 
Thanks so much for all the great options.

The client chose the one attached. They are asking to include their 30 year anniversary logo, which is a combination of their latest logo and the ribbons that are saved here (https://drive.google.com/drive/u/1/folders/1_Xv_QuPGru-ofHBhqjTtAcGRSAiqJRrJ.)

Let me know if you have time to run these edits by Monday morning!

Best,
Lucia
![Basstel Option 2](https://user-images.githubusercontent.com/58268389/71279849-61ccee00-231f-11ea-93ee-855fb0fe219e.jpg)

**Comment by felliperinschede** [comment]
Hi @LuciaFurlan1987
Sure, I'll run this edits and send you soon

**Comment by felliperinschede** [comment]
Hey @LuciaFurlan1987 
Attached i'm sending you the layout with the Edits 
Let me know if you need something else ;D

![Baastel_EmailMkt_04-01](https://user-images.githubusercontent.com/57017535/71367512-ab197980-257b-11ea-8f89-31acf8b4c624.jpg)

**Comment by LuciaFurlan1987** [comment]
Thank you so much, @felliperinschede 

One last edit: Could you make the 30 year ribbon more prominent? It looks a little small and I believe they want to emphasize it more.

Thanks!
Lucia

**Comment by felliperinschede** [comment]
Hey @LuciaFurlan1987 
Sure!
Attached with the 30 years ribbon bigger o/

![Baastel_EmailMkt_04-01](https://user-images.githubusercontent.com/57017535/71373868-06a13280-258f-11ea-89ce-4c478a211d00.jpg)

**Comment by LuciaFurlan1987** [comment]
This is great, thank you @felliperinschede 

I will send it now to the client and let you know!

**Comment by pedrojovelli** [comment]
Hi Fellipe.

This is a request from the client:


1. Make the FRENCH Happy New Year to be more emphasized:  **Bonne Année**
![Screen Shot 2019-12-23 at 18 25 05](https://user-images.githubusercontent.com/15367213/71381235-64df0d00-25b1-11ea-81f5-992202ff2f70.png)



2. They have asked us to change the 30 Years on the logo, to be now in French. So it'll be like this:
**30 Ans**

![Screen Shot 2019-12-23 at 18 26 20](https://user-images.githubusercontent.com/15367213/71381286-93f57e80-25b1-11ea-8911-bc42faa318af.png)

**Comment by LuciaFurlan1987** [comment]
Hey @pedrojovelli and @felliperinschede 

They want the 30-year anniversary tagline to be both in English and in French.

Let me know if there is a good artistic way to include both in the same flyer.

**Comment by felliperinschede** [comment]
Hey!
Attached with the edits (with the french tagline). I think that use English and French tagline make the communication confused. So, I would choose to work with tagline in English. o/ @pedrojovelli  @LuciaFurlan1987 

![Baastel_EmailMkt_04-01](https://user-images.githubusercontent.com/57017535/71382247-76261a80-25ad-11ea-8d6d-897f8f6435d9.jpg)

**Comment by pedrojovelli** [comment]
![Screen Shot 2019-12-23 at 19 04 13](https://user-images.githubusercontent.com/15367213/71382488-ec7b4a80-25b6-11ea-93cb-6a43dcead7c8.png)

**Comment by pedrojovelli** [comment]
Outro pedido é o seguinte:
Se você puder buscar a melhor solução dentro desse universo das 2 linguas no mesmo header.

30 Years Promoting
Sustainable Development

30 Ans de Promotion du
Développement Durable



Sugestão da Lucia:

![Screen Shot 2019-12-23 at 19 06 48](https://user-images.githubusercontent.com/15367213/71382711-dc179f80-25b7-11ea-9d66-603ae0e9c7f4.png)

**Comment by felliperinschede** [comment]
Veja se é isso
![Baastel_EmailMkt_04-01](https://user-images.githubusercontent.com/57017535/71382816-09f8e600-25b0-11ea-8da8-e7938fc6a08b.jpg)

**Comment by LuciaFurlan1987** [comment]
Thanks @felliperinschede , it looks awesome!

I sent it to the client, if they have any feedback we will deal with it on January 2nd

Happy Holidays!
