### ISSUE TITLE
TPUSA Productions / TPUSA Originals: Header parallax image

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#86]
Jesse diz que a imagem não está com bom posicionamento, tanto no desktop, quanto no mobile.

Ele gostaria de ver um pouco mais de elementos da imagem.

**Comment by felliperinschede** [comment]
Opa, pode me enviar o print? Pra eu ver como vou precisar diagramar a imagem pra ela ficar melhor.
@pedrojovelli

**Comment by felliperinschede** [comment]
Done ;D

**Comment by pedrojovelli** [comment]
Obrigado Fellipão !
