### ISSUE TITLE
BLEXIT: vídeos de exemplo para a Candace "Dancing Woman"

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#88]
- [Opção 01](https://drive.google.com/file/d/1J0jFv1Gc8dp7qKZg4zjWBzDcCIMv_Ef8/view?usp=sharing) - Música inteira
- [Opção 02](https://drive.google.com/file/d/1i2ksMeiT7cHiMGEeJxiMiPxm-iQArLe_/view?usp=sharing) - Opção 01 com preto no começo
- [Opção 03](https://drive.google.com/file/d/133zfi4KhVn7Ogc9s1S4zWIziGmjIMYJj/view?usp=sharing) - Só o pedaço "that we, as a people will get to the promised land"
- [Opção 04 ](https://drive.google.com/file/d/1yBtYbPZAYCHOVt5c-s2Sps6LC6aPDOze/view?usp=sharing)- Opção 03 com preto no começo
- [Opção 05](https://drive.google.com/file/d/1yKCA4glugCebGV1l0S5MLWikHOAvi9hT/view?usp=sharing) - Só o pedaço "But I want you to know tonight, that we, as a people, will get to the Promised Land."
- [Opção 06](https://drive.google.com/file/d/1ARbvXZVFxR_FnflBxhdvq6ggBTgcDkRW/view?usp=sharing) - Opção 05 com preto no começo
- [Opção 07](https://drive.google.com/file/d/1m_3nGW4Z-V7eYmyDj_Pe7oMLdrucxFsA/view?usp=sharing)
- [Opção 08](https://drive.google.com/file/d/1NOBmRKOxSL_-wISy5-2VTczMZOJne0k0/view?usp=sharing)

**Comment by Patricia-Torres** [comment]
- [Opção 05](https://drive.google.com/file/d/1yKCA4glugCebGV1l0S5MLWikHOAvi9hT/view?usp=sharing) - Só o pedaço "But I want you to know tonight, that we, as a people, will get to the Promised Land."
- [Opção 06](https://drive.google.com/file/d/1ARbvXZVFxR_FnflBxhdvq6ggBTgcDkRW/view?usp=sharing) - Opção 05 com preto no começo

**Comment by pedrojovelli** [comment]
Obrigadão Pat !! 

já está linkado no arquivo que o Jesse apresentará hoje !
