### ISSUE TITLE
TPUSA: Generate Production logos in white

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#9]
A pedido da Turning Point.

Precisamos aplicar pequenos logos dos canais na lateral direita de cada caixinha de novidade de PRODUCTIONS na sessão de STAY ON POINT do site.

**Checar link abaixo:**
http://tpusa-front-staging.herokuapp.com/

**Screenshot de PRODUCTIONS:**
![Screen Shot 2019-11-04 at 12 39 33](https://user-images.githubusercontent.com/15367213/68134095-5b65ec80-ff00-11e9-836a-92acd3f02329.png)

**Devemos aplicar logos em branco na lateral direita, seguindo o estilo da sessão de SOCIAL:
![Screen Shot 2019-11-04 at 12 42 42](https://user-images.githubusercontent.com/15367213/68134352-c6172800-ff00-11e9-9c18-f98e8c5eb381.png)

Os logos dos canais devem ser em branco e em PNG. Segue os logos:
- Freedom Fights
- Poplitics
- 180
- Only in America

_________________________

**Uma informação importante:**

**Comment by felliperinschede** [comment]
Done o/

**Comment by pedrojovelli** [comment]
Thanks a lot
