### ISSUE TITLE
RIOSLUM: Diagramar Proposta

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#90]
Diagramar proposta dentro daquele padrão mais estiloso que temos trabalhado recentemente

[Phoenix Initative.docx](https://github.com/rioslumstudio/Design/files/3978784/Phoenix.Initative.docx)

Site para pegar algumas imagens para topos de página:
https://phoenixzonesinitiative.org/phoenix-zones-initiative-vision-mission/

https://phoenixzonesinitiative.org/

**Comment by Patricia-Torres** [comment]
[Phoenix Zone Initiative Proposal.pdf](https://github.com/rioslumstudio/Design/files/3979320/Phoenix.Zone.Initiative.Proposal.pdf)

**Comment by Patricia-Torres** [comment]
Lucia's request:
[Phoenix.Zone.Initiative.Proposal_LF.pdf](https://github.com/rioslumstudio/Design/files/3979564/Phoenix.Zone.Initiative.Proposal_LF.pdf)

**Comment by Patricia-Torres** [comment]
[Phoenix Zone Initiative Proposal.pdf](https://github.com/rioslumstudio/Design/files/3979603/Phoenix.Zone.Initiative.Proposal.pdf)

**Comment by Patricia-Torres** [comment]
[Phoenix Zone Initiative Proposal.pdf](https://github.com/rioslumstudio/Design/files/3979669/Phoenix.Zone.Initiative.Proposal.pdf)
