### ISSUE TITLE
TPUSA: Erros/Defeitos do site

### ISSUE THREAD

**Issue by Patricia-Torres** [rioslumstudio/Design#91]
Aqui estão os erros/defeitos que eu visualizei ao navegar no site. 
O segundo e o terceiro erro, acontecem também no mobile.
Obs.: talvez o segundo erro não seja um erro realmente. Pode ser que a linguagem se adapte de acordo com o do navegador. Porém como eu não tenho certeza, marquei assim mesmo.
Obs2.: o meu monitor é em full HD. Então é um bom parâmetro para se analisar alguns defeitos como os últimos (dos banners) pois a resolução FHD (1920×1080) é atualmente a principal e mais usada.

![erros site tpusa](https://user-images.githubusercontent.com/43677737/71195788-689b2880-226d-11ea-82dc-277b652626a1.jpg)

**Comment by robanquieri** [comment]
Pessoal, seguem as minhas considerações:

1. Eu subi 2%, por curiosidade, qual o sistema operacional / navegador foi utilizado nos testes?
2. De fato, não é um erro, essa mensagem é padrão do navegador e o idioma é o idioma  padrão do navegador.
3. O Anedot é bloqueado no Brasil
4. Precisa ajustar a imagem, as laterais da imagem precisam ter uma cor sólida, sem interferencias, porque utlizamos um gradiente linear de background, sendo assim se tem a percepção que a imagem ocupa o fundo por completo, ex: https://www.tpusa.com/chapters

Eu subi os ajustes em https://tpusa-front-staging.herokuapp.com/

**Comment by Patricia-Torres** [comment]
O navegador foi o Chrome
