### ISSUE TITLE
BLEXIT: Add event

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#92]
Artwork client sent:
[gala flier v4 color (1).pdf](https://github.com/rioslumstudio/Design/files/3985024/gala.flier.v4.color.1.pdf)

URL: 
https://www.eventbrite.com/e/caap-reclaiming-the-dream-fundraiser-gala-tickets-83734136055

**Comment by Patricia-Torres** [comment]
https://candaceowens.com/events/

**Comment by pedrojovelli** [comment]
![Screen Shot 2019-12-19 at 16 13 18](https://user-images.githubusercontent.com/15367213/71202170-64293c80-227a-11ea-9f1d-cd7077a07f3f.png)

Por gentileza, altere para March 13th
