### ISSUE TITLE
RioSlum - End of Year Card 2019

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#93]

**Comment by pedrojovelli** [comment]
![ChristmasCard_Rio](https://user-images.githubusercontent.com/15367213/71374994-82a17780-259b-11ea-80ed-86fc15a93a28.jpg)

**Comment by pedrojovelli** [comment]
Editável de 2018.

Eu não encontrei o editável de 2019, mas por favor. Se você puder usar o mesmo texto do cartão de 2019 e aplicar outra imagem.

[NewYear_2018_05.psd.zip](https://github.com/rioslumstudio/Design/files/3995918/NewYear_2018_05.psd.zip)

**Comment by felliperinschede** [comment]
![NewYear_2019_01](https://user-images.githubusercontent.com/57017535/71376779-f42bf680-2598-11ea-9296-3e3a1509443c.jpg)
![Uploading NewYear_2019_02.jpg…]()
![Uploading NewYear_2019_03.jpg…]()

**Comment by felliperinschede** [comment]
![NewYear_2019_01](https://user-images.githubusercontent.com/57017535/71376794-0312a900-2599-11ea-8b4b-680253b4aa62.jpg)
![NewYear_2019_02](https://user-images.githubusercontent.com/57017535/71376795-0312a900-2599-11ea-8b6b-0b552c5d7599.jpg)
![NewYear_2019_03](https://user-images.githubusercontent.com/57017535/71376796-0312a900-2599-11ea-90a2-c0065041df43.jpg)

**Comment by felliperinschede** [comment]
![NewYear_2019_01](https://user-images.githubusercontent.com/57017535/71377141-3bff4d80-259a-11ea-8740-bfaee9a2ed9a.jpg)
![NewYear_2019_02](https://user-images.githubusercontent.com/57017535/71377142-3bff4d80-259a-11ea-8637-144a7db26ae9.jpg)
![NewYear_2019_03](https://user-images.githubusercontent.com/57017535/71377143-3c97e400-259a-11ea-9f5c-abbcb3299013.jpg)

**Comment by felliperinschede** [comment]
![NewYear_2019_01](https://user-images.githubusercontent.com/57017535/71377337-e6777080-259a-11ea-87ee-b73bdb9f0b35.jpg)

Segue

**Comment by felliperinschede** [comment]
![NewYear_2019_01](https://user-images.githubusercontent.com/57017535/71378403-0bb9ae00-259e-11ea-9bdb-d6bec17d1a82.jpg)

**Comment by felliperinschede** [comment]
![NewYear_2019_01_n](https://user-images.githubusercontent.com/57017535/71379340-42dd8e80-25a1-11ea-8578-a127b07a06a9.jpg)

**Comment by pedrojovelli** [comment]
Fellipão.

Por favor, suba o PSD dessas peças aqui:
https://drive.google.com/drive/folders/18QIMy7VXtc63JkZwxIhO7YF7WhIgUSNc?usp=sharing
