### ISSUE TITLE
BLEXIT: Portraits for videos

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#95]
Hi Fellipe.

We are building one more music video to be used on Blexit's event.
In this video. We want to add quick flashes of faces in black from USA icons, such as Martin Luther King and other folks.

We would like to ask you to create the first one with Martin Luther King.

The dimensions would be 1920 x 1080px (HD video dimension). 

Some references of the face in grayscale over black:

**Please, look for an image of the front of his face**

![Screen Shot 2020-01-02 at 12 10 57](https://user-images.githubusercontent.com/15367213/71674035-00624180-2d59-11ea-9591-02ed7cebaaa5.png)
![Screen Shot 2020-01-02 at 12 11 08](https://user-images.githubusercontent.com/15367213/71674037-00624180-2d59-11ea-90c8-e396bd1c057e.png)
![Screen Shot 2020-01-02 at 12 13 26](https://user-images.githubusercontent.com/15367213/71674102-2a1b6880-2d59-11ea-9275-d7ba4019d919.png)

**Comment by pedrojovelli** [comment]
Names for us to discuss later:

- Maya Angelou
- Thomas Sowell 
- Larry Elder
- Condoleezza Rice
- Thurgood Marshall 
- Walter Williams 
- Rosa Parks

**Comment by felliperinschede** [comment]
Hey, attached i'm sending 3 options. Two with the same "low-noise" retouch and one of them with more-noise o/

![Frame_Martin Luther King3](https://user-images.githubusercontent.com/57017535/71675520-4b2d8a80-2d54-11ea-91fb-f3ff8ec0d029.jpg)

![Frame_Martin Luther King](https://user-images.githubusercontent.com/57017535/71675518-4a94f400-2d54-11ea-82cb-d842bb982fac.jpg)
![Frame_Martin Luther King2](https://user-images.githubusercontent.com/57017535/71675519-4a94f400-2d54-11ea-9c53-a883c01da0af.jpg)

**Comment by pedrojovelli** [comment]
Hi fellipe.

From the images presented, this is the best option:

![Screen Shot 2020-01-02 at 14 28 40](https://user-images.githubusercontent.com/15367213/71681674-11687e00-2d6c-11ea-882e-bbe083733034.png)

I'd like to ask you to remain with black background and the face in grayscale.

I just want to ask you to look for bigger front-face and possibly more serious looks. Here are a few other photos of him:

https://jornalggn.com.br/sites/default/files/capa/destaques-secundarios/martin_luther_king_jr1-1280x720.jpg

https://cdn.everydaypower.com/wp-content/uploads/2019/01/martin-luther-king-jr.jpg

**Comment by felliperinschede** [comment]
Attached two new options ;D

![Frame_Martin Luther King4](https://user-images.githubusercontent.com/57017535/71682914-766da500-2d67-11ea-841b-0a29c2413694.jpg)
![Frame_Martin Luther King5](https://user-images.githubusercontent.com/57017535/71682915-766da500-2d67-11ea-821e-dd6838aef64b.jpg)

**Comment by pedrojovelli** [comment]
Amazing options.

Fellipe. Make this face even bigger and drag the face to be on the center, please.

![Screen Shot 2020-01-02 at 15 31 17](https://user-images.githubusercontent.com/15367213/71684658-d3238c80-2d74-11ea-9644-34cbd734e428.png)

**Comment by felliperinschede** [comment]
o/
![Frame_Martin Luther King4](https://user-images.githubusercontent.com/57017535/71684764-b84d1a00-2d6c-11ea-813f-4b1c992aac02.jpg)

**Comment by felliperinschede** [comment]
Attached three options for Maya Angelou frame ;D

![Frame_Maya Angelou1](https://user-images.githubusercontent.com/57017535/71687814-0403c180-2d75-11ea-9d05-da82468f289b.jpg)
![Frame_Maya Angelou2](https://user-images.githubusercontent.com/57017535/71687815-0403c180-2d75-11ea-8efd-ca0a2d1f6812.jpg)
![Frame_Maya Angelou3](https://user-images.githubusercontent.com/57017535/71687817-0403c180-2d75-11ea-9725-a95c4efc1d90.jpg)
