### ISSUE TITLE
Razor City Document

### ISSUE THREAD

**Issue by pedrojovelli** [rioslumstudio/Design#96]
**Proposal from RioSlum just for reference of fonts and margins:**
https://drive.google.com/file/d/1TKg-OWXC_N2MFhZbH-UYdsag2orAXTUQ/view?usp=sharing

The goal of this document is to pitch investors for financing a short version of the film RAZOR CITY.
Is important to bring the look and feel of the conceptual poster (attached here) to the entire document. In order to do that, we do recommend that color and/or watermark be followed.

Please, if you have a chance to re-evaluate the conceptual poster, keeping the sharp/flat feel to it, we'd love to see a version coming from you.

One last point to add. We'd like to add some special photo with effect or illustration at the back cover. If you have the chance to work on something like that, we'll really appreciate aswell.

**Comment by pedrojovelli** [comment]
[Razor City - Booklet.docx](https://github.com/rioslumstudio/Design/files/4025984/Razor.City.-.Booklet.docx)


![WhatsApp Image 2020-01-03 at 20 58 21](https://user-images.githubusercontent.com/15367213/71817644-44a95680-3065-11ea-9436-bf808f679c24.jpeg)

**Comment by pedrojovelli** [comment]
-- ending to be a KKK man or a cross

**Comment by felliperinschede** [comment]
Segue anexo a proposta.
Foquei em trabalhar com a tipografia real das maquinas de escrever, usando texturas mais próximas possíveis das reais (no poster).
Quanto aos elementos, trouxe um estudo de gestalt que trás a máscara, o fogo e fumaça, como elementos que contam a história da KKK pelas suas passagens mais dramáticas.

![Poster_03](https://user-images.githubusercontent.com/57017535/71894464-b1cff100-3124-11ea-840c-040d4542bceb.jpg)
[Proposal - Razor City.pdf](https://github.com/rioslumstudio/Design/files/4030558/Proposal.-.Razor.City.pdf)

**Comment by felliperinschede** [comment]
Bro, dei um tapa aqui. Confere as cruzes por favor?

![Uploading Cover_03_n.jpg…]()
[Uploading Proposal - Razor City.pdf…]()

**Comment by felliperinschede** [comment]
Segue ai meu querido

![Cover_03_n](https://user-images.githubusercontent.com/57017535/71896794-11c99600-312b-11ea-9303-ac7395b4f1a4.jpg)
[Proposal - Razor City.pdf](https://github.com/rioslumstudio/Design/files/4030714/Proposal.-.Razor.City.pdf)

**Comment by pedrojovelli** [comment]
Final document

[Razor City - Film Concept.pdf](https://github.com/rioslumstudio/Design/files/4035189/Razor.City.-.Film.Concept.pdf)
